# Generated by Django 6.0.5 on 2026-09-20 13:25

import django.db.models.deletion
from django.db import migrations, models


def refuse_network_history_loss(apps,schema_editor):
    alias=schema_editor.connection.alias
    for name in ('StockTransfer','PaymentRetention'):
        if apps.get_model('erp',name).objects.using(alias).exists():
            raise RuntimeError('Відкат видалив би історію мережевих операцій; зупинено до DDL.')
    for name,fields in (('Location',{'branch__isnull':False}),('Location',{'lat__isnull':False}),('Location',{'lng__isnull':False}),('Purchase',{'destination__isnull':False}),('SalesOrder',{'fulfillment_location__isnull':False})):
        if apps.get_model('erp',name).objects.using(alias).filter(**fields).exists():
            raise RuntimeError('Відкат видалив би прив’язку мережі; зупинено до DDL.')
    for name,field in (('Location','address'),('Purchase','origin_country'),('SalesOrder','destination_country')):
        if apps.get_model('erp',name).objects.using(alias).exclude(**{field:''}).exists():
            raise RuntimeError('Відкат видалив би мережеві метадані; зупинено до DDL.')


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_fill_short_names'),
        ('erp', '0005_source_corrections'),
        ('operations', '0007_actionproposal_dependency_context'),
    ]

    operations = [
        migrations.AlterField(model_name='item', name='currency', field=models.CharField(default='UAH', max_length=3)),
        migrations.AlterField(model_name='lot', name='currency', field=models.CharField(default='UAH', max_length=3)),
        migrations.AlterField(model_name='salesorder', name='currency', field=models.CharField(default='UAH', max_length=3)),
        migrations.AlterField(model_name='production', name='currency', field=models.CharField(default='UAH', max_length=3)),
        migrations.AlterField(model_name='purchase', name='currency', field=models.CharField(default='UAH', max_length=3)),

        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='location',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.location'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='origin_country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='destination_country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='fulfillment_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.location'),
        ),
        migrations.CreateModel(
            name='PaymentRetention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(default='held', max_length=20)),
                ('reason', models.TextField()),
                ('release_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_retentions', to='operations.invoice')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('currency__in', ['EUR', 'USD', 'UAH'])), name='bos_retention_amount'), models.CheckConstraint(condition=models.Q(models.Q(('released_at__isnull', True), ('status', 'held')), models.Q(('released_at__isnull', False), ('status', 'released')), _connector='OR'), name='bos_retention_state')],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('revision', models.CharField(max_length=40)),
                ('documents', models.JSONField(default=dict)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(default='in_transit', max_length=20)),
                ('reason', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='erp.location')),
                ('dispatch_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_transfer', to='erp.movement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.item')),
                ('receipt_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_transfer', to='erp.movement')),
                ('received_lot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transfer', to='erp.lot')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='erp.location')),
                ('source_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_transfers', to='erp.lot')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('currency__in', ['EUR', 'USD', 'UAH']), ('quantity__gt', 0), ('total_cost__gte', 0), ('unit_cost__gte', 0)), name='bos_transfer_amounts'), models.CheckConstraint(condition=models.Q(('source_location', models.F('destination')), _negated=True), name='bos_transfer_points_distinct'), models.CheckConstraint(condition=models.Q(models.Q(('receipt_movement__isnull', True), ('received_at__isnull', True), ('received_lot__isnull', True), ('status', 'in_transit')), models.Q(('receipt_movement__isnull', False), ('received_at__isnull', False), ('received_lot__isnull', False), ('status', 'received')), _connector='OR'), name='bos_transfer_state')],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, refuse_network_history_loss),
    ]
