# Generated by Django 6.0.5 on 2026-10-04 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("csv", "Excel / CSV"),
                            ("google_sheets", "Google Таблиці"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "dataset",
                    models.CharField(
                        choices=[
                            ("orders", "Замовлення"),
                            ("payments", "Оплати"),
                            ("stock", "Залишки"),
                            ("calls", "Дзвінки"),
                            ("other", "Інше"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Підключено"),
                            ("error", "Помилка"),
                            ("disabled", "Вимкнено"),
                        ],
                        default="connected",
                        max_length=20,
                    ),
                ),
                ("last_error", models.CharField(blank=True, max_length=300)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connectors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ConnectorSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("columns", models.JSONField()),
                ("rows", models.JSONField()),
                ("row_count", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="connectors.connector",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at", "-id"],
            },
        ),
    ]
