# Generated by Django 6.0.5 on 2026-07-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('supplier', 'Постачальник'), ('customer', 'Клієнт'), ('service', 'Послуги'), ('utility', 'Комунальні'), ('other', 'Інше')], default='other', max_length=20)),
                ('edrpou', models.CharField(blank=True, help_text='ЄДРПОУ / ІПН', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('services', 'Послуги'), ('goods', 'Товари'), ('utility', 'Комунальні'), ('rent', 'Оренда'), ('supply', 'Закупівля'), ('other', 'Інше')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Активний'), ('closed', 'Закритий'), ('draft', 'Чернетка')], default='active', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='finance.counterparty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Дохід'), ('out', 'Витрата')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('salary', 'Зарплата'), ('supplier', 'Постачальник'), ('customer', 'Клієнт'), ('utility', 'Комунальні'), ('rent', 'Оренда'), ('tax', 'Податки'), ('other', 'Інше')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.contract')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.counterparty')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('paid', 'Виплачено'), ('cancelled', 'Скасовано')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employees.employee')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_record', to='finance.transaction')),
            ],
            options={
                'ordering': ['-period_year', '-period_month', 'employee__full_name'],
                'unique_together': {('employee', 'period_year', 'period_month')},
            },
        ),
    ]
