# Generated by Django 6.0.5 on 2026-09-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_archived_at'),
        ('finance', '0003_transaction_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_record', to='finance.transaction'),
        ),
    ]
