# Generated by Django 6.0.5 on 2026-09-11 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_fill_short_names'),
        ('finance', '0004_salary_archived_at_transaction_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.contract'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.counterparty'),
        ),
    ]
