# Generated by Django 6.0.5 on 2026-09-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_transaction_branch_alter_transaction_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialIntent',
            fields=[
                ('key', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('payload_hash', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creation_intents', to='finance.salary')),
                ('transaction', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creation_intents', to='finance.transaction')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('transaction__isnull', True), ('salary__isnull', True), _connector='OR'), name='financial_intent_single_source')],
            },
        ),
    ]
