# Generated by Django 6.0.5 on 2026-09-12 15:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def refuse_statement_history_loss(apps,schema_editor):
    for name in ('StatementImport','StatementLine','StatementAllocation'):
        if apps.get_model('finance',name).objects.using(schema_editor.connection.alias).exists():
            raise RuntimeError('Відкат видалив би первинні виписки та погоджену звірку; зупинено до DDL.')


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_source_corrections'),
        ('finance', '0007_money_boundaries'),
        ('operations', '0006_private_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_sha256', models.CharField(max_length=64)),
                ('format', models.CharField(max_length=40)),
                ('parser_version', models.CharField(max_length=10)),
                ('source_system', models.CharField(max_length=48)),
                ('account_ref', models.CharField(max_length=120)),
                ('source_snapshot', models.JSONField()),
                ('first_commit_receipt', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_imports', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_imports', to='operations.document')),
            ],
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(max_length=48)),
                ('account_ref', models.CharField(max_length=120)),
                ('external_id', models.CharField(max_length=120)),
                ('record', models.PositiveIntegerField()),
                ('booking_date', models.DateField()),
                ('direction', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('counterparty_external_id', models.CharField(blank=True, max_length=120)),
                ('invoice_reference', models.CharField(blank=True, max_length=120)),
                ('purpose', models.TextField(blank=True, max_length=2000)),
                ('semantic_sha256', models.CharField(max_length=64)),
                ('bound_at', models.DateTimeField(blank=True, null=True)),
                ('binding_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bound_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bound_statement_lines', to=settings.AUTH_USER_MODEL)),
                ('first_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_lines', to='finance.statementimport')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statement_line', to='finance.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='StatementAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocation_key', models.UUIDField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('mode', models.CharField(max_length=30)),
                ('intent_sha256', models.CharField(max_length=64)),
                ('source_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_allocations', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_allocations', to='operations.invoice')),
                ('payment_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='statement_allocation', to='erp.event')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.statementline')),
            ],
        ),
        migrations.AddConstraint(
            model_name='statementimport',
            constraint=models.UniqueConstraint(fields=('source_system', 'account_ref', 'source_sha256'), name='statement_import_source'),
        ),
        migrations.AddConstraint(
            model_name='statementline',
            constraint=models.UniqueConstraint(fields=('source_system', 'account_ref', 'external_id'), name='statement_line_identity'),
        ),
        migrations.AddConstraint(
            model_name='statementline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('amount__lte', Decimal('999999999999.99'))), name='statement_line_amount'),
        ),
        migrations.AddConstraint(
            model_name='statementline',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ('EUR', 'UAH', 'USD'))), name='statement_line_currency'),
        ),
        migrations.AddConstraint(
            model_name='statementline',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', ('in', 'out'))), name='statement_line_direction'),
        ),
        migrations.AddConstraint(
            model_name='statementline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('binding_snapshot__isnull', True), ('bound_at__isnull', True), ('bound_by__isnull', True), ('transaction__isnull', True)), models.Q(('binding_snapshot__isnull', False), ('bound_at__isnull', False), ('bound_by__isnull', False), ('transaction__isnull', False)), _connector='OR'), name='statement_binding_complete'),
        ),
        migrations.AddConstraint(
            model_name='statementallocation',
            constraint=models.UniqueConstraint(fields=('line', 'allocation_key'), name='statement_allocation_identity'),
        ),
        migrations.AddConstraint(
            model_name='statementallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('amount__lte', Decimal('999999999999.99'))), name='statement_allocation_amount'),
        ),
        migrations.AddConstraint(
            model_name='statementallocation',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ('EUR', 'UAH', 'USD'))), name='statement_allocation_currency'),
        ),
        migrations.AddConstraint(
            model_name='statementallocation',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ('new_payment', 'existing_payment'))), name='statement_allocation_mode'),
        ),
        migrations.RunPython(migrations.RunPython.noop,refuse_statement_history_loss),
    ]
