# Generated by Django 6.0.5 on 2026-09-10 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_employee_branch'),
        ('finance', '0003_transaction_branch'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('payload', models.JSONField()),
                ('result', models.JSONField()),
                ('role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(default='шт.', max_length=20)),
                ('kind', models.CharField(default='product', max_length=20)),
                ('method', models.CharField(default='buy', max_length=20)),
                ('revision', models.CharField(default='A', max_length=40)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('external_codes', models.JSONField(default=dict)),
                ('required_documents', models.JSONField(default=list)),
                ('bom', models.JSONField(default=list)),
                ('routing', models.JSONField(default=list)),
                ('minimum', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('lead_days', models.PositiveIntegerField(default=7)),
                ('planned_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.document')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('target_revision', models.CharField(max_length=40)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='draft', max_length=20)),
                ('disposition', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.document')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(default='warehouse', max_length=20)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('revision', models.CharField(max_length=40)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('quality', models.CharField(default='pending', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('documents', models.JSONField(default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=20)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('produced', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('revision', models.CharField(max_length=40)),
                ('bom', models.JSONField(default=list)),
                ('routing', models.JSONField(default=list)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='planned', max_length=20)),
                ('needs_review', models.BooleanField(default=False)),
                ('planned_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=120)),
                ('result', models.CharField(max_length=20)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('defects', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='erp.production')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('received', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('extras', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('due_date', models.DateField()),
                ('original_due', models.DateField()),
                ('revision', models.CharField(max_length=40)),
                ('status', models.CharField(default='ordered', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.item')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.production')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.procurementrequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='SalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=40)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('shipped', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('invoiced', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='erp.lot')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='erp.production')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='erp.salesline')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.salesline'),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('kind', models.CharField(max_length=30)),
                ('reference', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='erp.lot')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.production')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.purchase')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.salesline')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('due_date', models.DateField()),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(default='quote', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.counterparty')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
            ],
        ),
        migrations.AddField(
            model_name='salesline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.salesorder'),
        ),
        migrations.CreateModel(
            name='InvoiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.JSONField(default=list)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='operations.invoice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.salesorder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='erp_nonnegative_lot'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='erp_nonnegative_reserve'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('line__isnull', False), ('production__isnull', True)), models.Q(('line__isnull', True), ('production__isnull', False)), _connector='OR'), name='erp_reservation_target'),
        ),
        migrations.AddConstraint(
            model_name='salesline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('shipped__gte', 0), ('shipped__lte', models.F('quantity'))), name='erp_line_quantity'),
        ),
    ]
