# Generated by Django 6.0.5 on 2026-09-12 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def refuse_import_history_loss(apps,schema_editor):
    alias=schema_editor.connection.alias
    if apps.get_model('erp','ImportBatch').objects.using(alias).exists() or apps.get_model('erp','ImportIdentity').objects.using(alias).exists():
        raise RuntimeError('Відкат B02 зупинено: він видалив би журнал походження імпорту.')


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_purchase_source'),
        ('finance', '0007_money_boundaries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=48)),
                ('cutover', models.DateField()),
                ('semantic_sha256', models.CharField(max_length=64)),
                ('canonical_source', models.JSONField()),
                ('source_part_sha256', models.JSONField(default=dict)),
                ('receipt', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=48)),
                ('entity', models.CharField(max_length=32)),
                ('external_id', models.CharField(max_length=120)),
                ('row_sha256', models.CharField(max_length=64)),
                ('source_row', models.JSONField()),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.counterparty')),
                ('first_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.importbatch')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.item')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.salesline')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.location')),
                ('lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.lot')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.salesorder')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.purchase')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('namespace', 'entity', 'external_id'), name='bos_import_external_identity'), models.UniqueConstraint(condition=models.Q(('counterparty__isnull', False)), fields=('namespace', 'counterparty'), name='bos_import_target_counterparty'), models.UniqueConstraint(condition=models.Q(('item__isnull', False)), fields=('namespace', 'item'), name='bos_import_target_item'), models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('namespace', 'location'), name='bos_import_target_location'), models.UniqueConstraint(condition=models.Q(('lot__isnull', False)), fields=('namespace', 'lot'), name='bos_import_target_lot'), models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('namespace', 'order'), name='bos_import_target_order'), models.UniqueConstraint(condition=models.Q(('line__isnull', False)), fields=('namespace', 'line'), name='bos_import_target_line'), models.UniqueConstraint(condition=models.Q(('purchase__isnull', False)), fields=('namespace', 'purchase'), name='bos_import_target_purchase'), models.CheckConstraint(condition=models.Q(models.Q(('counterparty__isnull', False), ('entity', 'counterparty'), ('item__isnull', True), ('line__isnull', True), ('location__isnull', True), ('lot__isnull', True), ('order__isnull', True), ('purchase__isnull', True)), models.Q(('counterparty__isnull', True), ('entity', 'item'), ('item__isnull', False), ('line__isnull', True), ('location__isnull', True), ('lot__isnull', True), ('order__isnull', True), ('purchase__isnull', True)), models.Q(('counterparty__isnull', True), ('entity', 'location'), ('item__isnull', True), ('line__isnull', True), ('location__isnull', False), ('lot__isnull', True), ('order__isnull', True), ('purchase__isnull', True)), models.Q(('counterparty__isnull', True), ('entity', 'opening_lot'), ('item__isnull', True), ('line__isnull', True), ('location__isnull', True), ('lot__isnull', False), ('order__isnull', True), ('purchase__isnull', True)), models.Q(('counterparty__isnull', True), ('entity', 'sales_order'), ('item__isnull', True), ('line__isnull', True), ('location__isnull', True), ('lot__isnull', True), ('order__isnull', False), ('purchase__isnull', True)), models.Q(('counterparty__isnull', True), ('entity', 'sales_line'), ('item__isnull', True), ('line__isnull', False), ('location__isnull', True), ('lot__isnull', True), ('order__isnull', True), ('purchase__isnull', True)), models.Q(('counterparty__isnull', True), ('entity', 'purchase_open_balance'), ('item__isnull', True), ('line__isnull', True), ('location__isnull', True), ('lot__isnull', True), ('order__isnull', True), ('purchase__isnull', False)), _connector='OR'), name='bos_import_target_kind')],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=refuse_import_history_loss),
    ]
