# Generated by Django 6.0.5 on 2026-09-12 13:09

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


def refuse_correction_history_loss(apps,schema_editor):
    for name in ('OrderCancellation','CancellationRelease','GoodsReturn','SupplierClaim','InvoiceAdjustment','InvoiceAdjustmentLine'):
        if apps.get_model('erp',name).objects.using(schema_editor.connection.alias).exists():
            raise RuntimeError('Відкат B03 видалив би історію коригувань; операцію зупинено до DDL.')


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_initial_import_ledger'),
        ('operations', '0006_private_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('reason', models.TextField()),
                ('business_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('source_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('source_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocated_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('source_snapshot', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.event')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exact_return', to='erp.movement')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_returns', to='erp.movement')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('reason', models.TextField()),
                ('business_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=12)),
                ('basis', models.CharField(max_length=12)),
                ('basis_snapshot', models.JSONField()),
                ('basis_hash', models.CharField(max_length=64)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.event')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.invoice')),
                ('reversed_credit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='erp.invoiceadjustment')),
                ('source_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.document')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_line_index', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source_snapshot', models.JSONField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.invoiceadjustment')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.salesline')),
                ('returned_goods', models.ForeignKey(db_column='return_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.goodsreturn')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('reason', models.TextField()),
                ('business_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('before_snapshot', models.JSONField()),
                ('after_snapshot', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.event')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.salesline')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='CancellationRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('before_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('after_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.reservation')),
                ('cancellation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.ordercancellation')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('business_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation_id', models.UUIDField(null=True, unique=True)),
                ('payload_hash', models.CharField(max_length=64, null=True)),
                ('code', models.CharField(max_length=60, null=True, unique=True)),
                ('record_kind', models.CharField(max_length=16)),
                ('agreed_amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.event')),
                ('parent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmation', to='erp.supplierclaim')),
                ('returned_goods', models.ForeignKey(db_column='return_id', on_delete=django.db.models.deletion.PROTECT, to='erp.goodsreturn')),
                ('source_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.document')),
            ],
        ),
        migrations.AddConstraint(
            model_name='goodsreturn',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['EUR', 'USD', 'UAH']), ('direction__in', ['supplier', 'customer'])), name='bos_return_kind_currency'),
        ),
        migrations.AddConstraint(
            model_name='goodsreturn',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('quantity__lt', 1000000000000), ('quantity__lte', models.F('source_quantity')), ('source_quantity__gt', 0), ('source_quantity__lt', 1000000000000)), name='bos_return_quantities'),
        ),
        migrations.AddConstraint(
            model_name='goodsreturn',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_cost__gte', 0), ('allocated_cost__lt', 10000000000000), ('allocated_cost__lte', models.F('source_cost')), ('source_cost__gte', 0), ('source_cost__lt', 10000000000000), ('unit_cost__gte', 0), ('unit_cost__lt', 10000000000000)), name='bos_return_costs'),
        ),
        migrations.AddConstraint(
            model_name='goodsreturn',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('result')), _negated=True), name='bos_return_distinct_source'),
        ),
        migrations.AddConstraint(
            model_name='invoiceadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['EUR', 'USD', 'UAH']), ('total__gte', 0), ('total__lt', 1000000000000)), name='bos_credit_amount_currency'),
        ),
        migrations.AddConstraint(
            model_name='invoiceadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('basis__in', ['return', 'commercial']), ('kind', 'credit'), ('reversed_credit__isnull', True)), models.Q(('basis', 'reversal'), ('kind', 'reversal'), ('reversed_credit__isnull', False)), _connector='OR'), name='bos_credit_kind_source'),
        ),
        migrations.AddConstraint(
            model_name='invoiceadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('reversed_credit', models.F('pk')), _negated=True), name='bos_credit_distinct_reverse'),
        ),
        migrations.AddConstraint(
            model_name='invoiceadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('amount__lt', 1000000000000), ('quantity__gte', 0), ('quantity__lt', 1000000000000)), name='bos_credit_line_amount'),
        ),
        migrations.AddConstraint(
            model_name='invoiceadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity__gt', 0), ('returned_goods__isnull', False)), models.Q(('quantity', 0), ('returned_goods__isnull', True)), _connector='OR'), name='bos_credit_line_source'),
        ),
        migrations.AddConstraint(
            model_name='invoiceadjustmentline',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_goods__isnull', False)), fields=('document', 'invoice_line_index', 'returned_goods'), name='bos_credit_return_line_once'),
        ),
        migrations.AddConstraint(
            model_name='invoiceadjustmentline',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_goods__isnull', True)), fields=('document', 'invoice_line_index'), name='bos_credit_commercial_line_once'),
        ),
        migrations.AddConstraint(
            model_name='ordercancellation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('line__isnull', False), ('purchase__isnull', True)), models.Q(('line__isnull', True), ('purchase__isnull', False)), _connector='OR'), name='bos_cancel_target'),
        ),
        migrations.AddConstraint(
            model_name='ordercancellation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('quantity__lt', 1000000000000)), name='bos_cancel_quantity'),
        ),
        migrations.AddConstraint(
            model_name='cancellationrelease',
            constraint=models.UniqueConstraint(fields=('cancellation', 'reservation'), name='bos_cancel_release_once'),
        ),
        migrations.AddConstraint(
            model_name='cancellationrelease',
            constraint=models.CheckConstraint(condition=models.Q(('after_quantity', django.db.models.expressions.CombinedExpression(models.F('before_quantity'), '-', models.F('quantity'))), ('after_quantity__gte', 0), ('after_quantity__lt', 1000000000000), ('before_quantity__gte', models.F('quantity')), ('before_quantity__lt', 1000000000000), ('quantity__gt', 0), ('quantity__lt', 1000000000000)), name='bos_cancel_release_balance'),
        ),
        migrations.AddConstraint(
            model_name='supplierclaim',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['EUR', 'USD', 'UAH'])), name='bos_claim_currency'),
        ),
        migrations.AddConstraint(
            model_name='supplierclaim',
            constraint=models.CheckConstraint(condition=models.Q(('agreed_amount__isnull', True), models.Q(('agreed_amount__gte', 0), ('agreed_amount__lt', 1000000000000)), _connector='OR'), name='bos_claim_amount'),
        ),
        migrations.AddConstraint(
            model_name='supplierclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agreed_amount__isnull', True), ('operation_id__isnull', True), ('parent__isnull', True), ('payload_hash__isnull', True), ('record_kind', 'pending'), ('source_document__isnull', True)), models.Q(('agreed_amount__isnull', False), ('code__isnull', False), ('operation_id__isnull', False), ('parent__isnull', False), ('payload_hash__isnull', False), ('record_kind', 'confirmation'), ('source_document__isnull', False)), _connector='OR'), name='bos_claim_record_shape'),
        ),
        migrations.AddConstraint(
            model_name='supplierclaim',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('pk')), _negated=True), name='bos_claim_distinct_parent'),
        ),
        migrations.RunPython(migrations.RunPython.noop,refuse_correction_history_loss),
    ]
