# Generated by Django 6.0.5 on 2026-10-04 23:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0008_compose_branch_network"),
        ("operations", "0010_supplier_invoice_registration"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="erp_links",
                        to="operations.document",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_links",
                        to="operations.invoice",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_links",
                        to="erp.salesorder",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("invoice__isnull", True), ("order__isnull", False)
                            ),
                            models.Q(
                                ("invoice__isnull", False), ("order__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="bos_document_link_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("order__isnull", False)),
                        fields=("document", "order"),
                        name="bos_document_link_order",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("invoice__isnull", False)),
                        fields=("document", "invoice"),
                        name="bos_document_link_invoice",
                    ),
                ],
            },
        ),
    ]
