const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const filename=process.argv[2],out=process.argv[3],source=fs.readFileSync(filename,'utf8'),root=path.dirname(path.dirname(filename));
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');const rows=[];
async function check(name,fn){try{await fn();rows.push({name,passed:true});}catch(e){rows.push({name,passed:false,error:e.message});}}
const helpers=source.match(/\/\/ B03_HELPERS_BEGIN\n([\s\S]*?)\/\/ B03_HELPERS_END/)[1];const oldDefs=source.match(/const ERP_ACTIONS=\{[\s\S]*?\n\};/)[0];const method=source.split('\n').find(l=>l.includes('async function importAction(){'));
const identities=source.slice(source.indexOf('function bosRole()'),source.indexOf('function bosCanView('));
const entries=[],errors=[],context={JSON,console,raw:'',setError:e=>errors.push(e),setErpAction:e=>entries.push(e),setPayload:()=>{},setTask:()=>{},erpFetch:async()=>({as_of:'2026-09-12'}),window:{BOS_RUNTIME:{role:'ceo',capabilities:{write:true}},crypto:{randomUUID:()=> 'f0000000-0000-4000-8000-000000000001'}}};
vm.createContext(context);vm.runInContext(identities+'\n'+helpers+'\n'+oldDefs+'\n'+method,context);
const op='a0000000-0000-4000-8000-000000000001',base={action:'erp_return_supplier',operation_id:op,code:'КР-1',business_date:'2026-09-12',reason:'Погоджено джерельний результат',receipt_id:23,quantity:'1.000'};
async function run(value,role='ceo',write=true){entries.length=errors.length=0;context.window.BOS_RUNTIME={role,capabilities:{write}};context.raw=JSON.stringify(value);await context.importAction();return {entries:[...entries],errors:errors.filter(Boolean)};}
(async()=>{
 await check('manager operational import retains provided UUID',async()=>{const r=await run(base,'manager');assert.equal(r.entries.length,1,r.errors.join());assert.equal(r.entries[0].preset.operation_id,op);});
 const monetary={credit_invoice:{invoice_id:5,basis:'commercial',source_document_id:4,allocations:[{invoice_line_index:0,amount:'1.00'}]},reverse_credit:{credit_id:20},confirm_supplier_claim:{claim_id:21,amount:'1.31',currency:'EUR',source_document_id:4}};
 for(const [action,fields] of Object.entries(monetary))await check('manager denies '+action,async()=>{const {receipt_id,quantity,...common}=base;const r=await run({...common,action:'erp_'+action,...fields},'manager');assert.equal(r.entries.length,0);assert.ok(r.errors.length);});
 await check('observer denies operational import',async()=>{const r=await run(base,'observer',false);assert.equal(r.entries.length,0);assert.ok(r.errors.length);});
 const invalid={unknown_top_key:{...base,amount:'1.00'},float_quantity:{...base,quantity:0.1},string_source_id:{...base,receipt_id:'23'},invalid_UUID:{...base,operation_id:op.toUpperCase()},cancel_both_sources:{...base,action:'erp_cancel_remaining',line_id:1,purchase_id:2},nested_extra_key:{action:'erp_credit_invoice',operation_id:op,code:'КР-2',reason:'Перевірено документ',business_date:'2026-09-12',invoice_id:5,basis:'return',allocations:[{return_id:1,invoice_line_index:0,quantity:'1.000',amount:'1.00'}]}};
 for(const [name,value] of Object.entries(invalid))await check('reject '+name,async()=>{const r=await run(value);assert.equal(r.entries.length,0);assert.ok(r.errors.length);});
 await check('imported UUID remains fixed after editing reason',()=>{const change=source.split('\n').find(l=>l.includes('function change(key,value){if(pending||receipt||busy)return;'));const c={pending:null,receipt:null,busy:'',retryIntent:false,preset:{operation_id:op},intent:{current:op},current:{},setValues:f=>{},setProposal:()=>{},setError:()=>{}};vm.createContext(c);vm.runInContext(change,c);c.change('reason','Повторна перевірка того самого наміру');assert.equal(c.intent.current,op);});
 await check('compiled app equals exact Babel source output',()=>{const babel=require(path.resolve(root,'assets/babel.js')),match=source.match(/<script type="text\/babel">([\s\S]*?)<\/script>/);const jsx=match[1].replace('{% verbatim %}','').replace('{% endverbatim %}','');const compiled=babel.transform(jsx,{presets:['react'],filename:'bos-app.jsx'}).code;assert.equal(compiled,fs.readFileSync(path.resolve(root,'assets/app.js'),'utf8'));});
 const result={scope:'Source, actual extracted JS closures and exact Babel only; mock snapshot read; no browser/API/DB acceptance',source_sha256:hash(source),compiled_sha256:hash(fs.readFileSync(path.resolve(root,'assets/app.js'))),checks:rows};fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));process.exitCode=rows.some(r=>!r.passed)?1:0;
})();
