// C03_HELPERS_BEGIN
const C03_ACTIONS={erp_statement_import:'Імпорт виписки',erp_statement_reconcile:'Звірка рядка виписки'};
const C03_CURRENCIES=['EUR','USD','UAH'];
const C03_STATUSES={unposted:'Не внесено до журналу',unallocated:'Не рознесено на рахунки',partial:'Частково рознесено',reconciled:'Рознесено повністю',cash_recorded:'Витрату внесено до журналу'};
const c03Own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
const c03UUID=s=>typeof s==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(s);
const c03PK=n=>Number.isSafeInteger(n)&&n>0;
function c03InputID(value){if(typeof value==='number'&&c03PK(value))return value;if(typeof value==='string'&&/^[1-9]\d*$/.test(value)&&c03PK(Number(value)))return Number(value);throw Error('Оберіть фактичний запис зі списку.');}
function c03Shape(o,keys,label){if(!o||Array.isArray(o)||typeof o!=='object'||Object.keys(o).length!==keys.length||keys.some(k=>!c03Own(o,k)))throw Error(label+': перевірте обов’язкові та невідомі поля.');}
function c03Text(s,min,max,label,trim=false){if(typeof s!=='string'||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(s))throw Error(label+': потрібен коректний текст.');const value=trim?s.trim():s;if([...value].length<min||[...value].length>max)throw Error(label+': від '+min+' до '+max+' символів.');return value;}
function c03Money(value){if(typeof value!=='string'||!/^\d+(\.\d{1,2})?$/.test(value))throw Error('Сума має бути рядком із крапкою та не більш ніж двома десятковими знаками.');const [a,b='']=value.split('.'),n=BigInt(a)*100n+BigInt(b.padEnd(2,'0'));if(n<=0n||n>99999999999999n)throw Error('Сума має бути більшою за нуль і не більшою за 999999999999.99.');return (n/100n).toString()+'.'+(n%100n).toString().padStart(2,'0');}
function c03Amount(value,currency){return value==null?'Не отримано':String(value)+(currency?' '+currency:'');}
function c03Payload(value){
 if(!value||!C03_ACTIONS[value.action])throw Error('Підтримуються лише імпорт та звірка виписки.');
 if(value.action==='erp_statement_import'){
  c03Shape(value,['action','document_id','source_sha256','source_system','account_ref','format','parser_version'],'Імпорт');
  if(!c03PK(value.document_id)||typeof value.source_sha256!=='string'||! /^[0-9a-f]{64}$/.test(value.source_sha256))throw Error('Потрібні фактичний документ та його SHA-256.');
  if(typeof value.source_system!=='string'||! /^[a-z0-9][a-z0-9._-]{0,47}$/.test(value.source_system)||typeof value.account_ref!=='string'||! /^[A-Z0-9][A-Z0-9_.:-]{0,119}$/.test(value.account_ref))throw Error('Система: малий регістр; локальний рахунок: великий регістр. Крайні пробіли не допускаються.');
  if(value.format!=='bos_statement_csv_v1'||value.parser_version!=='1')throw Error('Підтримується CSV BoS v1, parser 1.');return {...value};
 }
 c03Shape(value,['action','line_id','transaction','matching','reason','allocations'],'Звірка');
 if(!c03UUID(value.line_id))throw Error('Оберіть збережений рядок виписки.');
 const t={...value.transaction},m={...value.matching};
 if(t.mode==='create_transaction'){c03Shape(t,['mode','category','description'],'Новий запис журналу');if(!['supplier','customer','utility','rent','tax','other'].includes(t.category))throw Error('Оберіть категорію; новий зарплатний платіж тут не створюється.');t.description=c03Text(t.description,3,300,'Опис журналу',true);}
 else if(t.mode==='existing_transaction'){c03Shape(t,['mode','transaction_id'],'Наявний запис журналу');if(!c03PK(t.transaction_id))throw Error('Оберіть наявну транзакцію.');}else throw Error('Оберіть спосіб запису грошей.');
 const mk=m.kind==='manual'?['kind','counterparty_id','counterparty_external_id']:m.kind==='import_identity'?['kind','identity_id','counterparty_id','counterparty_external_id']:m.kind==='salary_source'?['kind','salary_id','counterparty_id','counterparty_external_id']:null;
 if(!mk)throw Error('Оберіть джерело зіставлення контрагента.');c03Shape(m,mk,'Зіставлення');
 c03Text(m.counterparty_external_id,0,120,'Зовнішній код');if(m.counterparty_external_id!==m.counterparty_external_id.trim())throw Error('Зовнішній код зберігається точно, без крайніх пробілів.');
 if(m.counterparty_id!==null&&!c03PK(m.counterparty_id))throw Error('Потрібен ID контрагента або явне null.');
 if(m.kind==='import_identity'&&(!c03PK(m.identity_id)||!c03PK(m.counterparty_id)))throw Error('Оберіть справжню відповідність імпорту.');
 if(m.kind==='salary_source'&&(!c03PK(m.salary_id)||m.counterparty_id!==null||t.mode!=='existing_transaction'))throw Error('Зарплатне джерело потребує наявної транзакції та null контрагента.');
 if(!Array.isArray(value.allocations)||value.allocations.length>50)throw Error('Допускається до 50 рознесень.');
 if((m.counterparty_id===null||m.kind==='salary_source')&&value.allocations.length)throw Error('Для рознесення оплати оберіть контрагента; зарплата не розноситься на клієнтські рахунки.');
 const seen=new Set(),allocations=value.allocations.map(a=>{const keys=['allocation_key','mode','invoice_id','amount','currency','invoice_match','reason'];if(a?.mode==='existing_payment')keys.push('payment_event_id');c03Shape(a,keys,'Рознесення');if(!c03UUID(a.allocation_key)||seen.has(a.allocation_key))throw Error('Кожне рознесення потребує окремого незмінного UUID v4.');seen.add(a.allocation_key);if(!['new_payment','existing_payment'].includes(a.mode)||!c03PK(a.invoice_id)||!C03_CURRENCIES.includes(a.currency)||!['exact_reference','manual'].includes(a.invoice_match)||(a.mode==='existing_payment'&&!c03PK(a.payment_event_id)))throw Error('Перевірте спосіб, рахунок, валюту та джерело оплати.');return {...a,amount:c03Money(a.amount),reason:c03Text(a.reason,3,1000,'Підстава рознесення',true)};});
 return {...value,transaction:t,matching:m,reason:c03Text(value.reason,3,1000,'Підстава звірки',true),allocations};
}
function c03ActionJSON(raw){
 if(typeof raw!=='string'||new TextEncoder().encode(raw).length>30000)throw Error('JSON перевищує 30 000 байтів.');const value=JSON.parse(raw);
 const tokens=raw.match(/"(?:\\.|[^"\\])*"|[{}\[\],:]/g)||[],stack=[];
 for(let i=0;i<tokens.length;i++){const token=tokens[i];if(token==='{')stack.push(new Set());else if(token==='[')stack.push(null);else if(token==='}'||token===']')stack.pop();else if(token[0]==='"'&&tokens[i+1]===':'){const key=JSON.parse(token),set=stack[stack.length-1];if(!set||set.has(key))throw Error('Повторний ключ JSON: '+key);set.add(key);}}
 return c03Payload(value);
}
function c03Stable(value){if(Array.isArray(value))return '['+value.map(c03Stable).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+c03Stable(value[k])).join(',')+'}';return JSON.stringify(value);}
async function c03SourceIdentity(source){if(typeof source.source_sha256!=='string'||! /^[0-9a-f]{64}$/.test(source.source_sha256)||typeof source.source_system!=='string'||! /^[a-z0-9][a-z0-9._-]{0,47}$/.test(source.source_system)||typeof source.account_ref!=='string'||! /^[A-Z0-9][A-Z0-9_.:-]{0,119}$/.test(source.account_ref))throw Error('Не отримано точної ідентичності джерела імпорту.');const bytes=new TextEncoder().encode(JSON.stringify([source.source_sha256,source.source_system,source.account_ref]));return Array.from(new Uint8Array(await window.crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');}
function c03VerifyPreview(response,payload,line){const normalized=c03Payload(response.payload);if(c03Stable(normalized)!==c03Stable(payload))throw Error('Погодження належить іншому наміру. Повторіть перевірку цієї форми.');const e=response.effect;if(payload.action==='erp_statement_import'){if(!e||e.schema!=='bos.statement-import.v1'||!e.source||['document_id','source_sha256','source_system','account_ref'].some(k=>e.source[k]!==payload[k]))throw Error('Джерело попередньої перевірки не збігається з обраним файлом і рахунком.');}else{if(!e||e.schema!=='bos.statement-reconcile.v1'||e.line_id!==payload.line_id||e.currency!==line.currency||e.amount!==line.amount||e.transaction?.mode!==payload.transaction.mode||(payload.transaction.mode==='existing_transaction'&&e.transaction.transaction_id!==payload.transaction.transaction_id))throw Error('Попередня перевірка належить іншому рядку або запису журналу.');if(!Array.isArray(e.allocations)||e.allocations.length!==payload.allocations.length||new Set(e.allocations.map(a=>a.allocation_key)).size!==e.allocations.length||payload.allocations.some(a=>{const row=e.allocations.find(x=>x.allocation_key===a.allocation_key);return !row||['mode','invoice_id','amount','currency'].some(k=>row[k]!==a[k])||(a.mode==='existing_payment'&&row.payment_event_id!==a.payment_event_id);} ))throw Error('Рознесення попередньої перевірки відрізняється від введеного наміру.');}return normalized;}
function c03PendingKey(){return bosStorageKey('statements-pending');}
function c03PendingRead(){const raw=sessionStorage.getItem(c03PendingKey());if(!raw)return [];let rows;try{rows=JSON.parse(raw);}catch{throw Error('Ідентифікатори погоджень не читаються. Їх не видалено.');}if(!Array.isArray(rows)||rows.some(r=>!r||!c03UUID(r.proposal_id)||!C03_ACTIONS[r.action]||(r.line_id!==null&&!c03UUID(r.line_id))||(r.document_id!==null&&!c03PK(r.document_id))||!Array.isArray(r.allocation_keys)||r.allocation_keys.some(k=>!c03UUID(k))))throw Error('Невідомий формат збережених ідентифікаторів. Їх не видалено.');return rows.map(({proposal_id,action,line_id,document_id,allocation_keys,source_identity_sha256})=>({proposal_id,action,line_id,document_id,allocation_keys,...(action==='erp_statement_import'?{source_identity_sha256:source_identity_sha256??null}:{})}));}
function c03PendingSave(entry){if(!c03PK(window.BOS_RUNTIME?.user_id)||bosRole()!=='ceo')throw Error('Потрібна чинна сесія CEO.');if(entry.action==='erp_statement_import'&&(typeof entry.source_identity_sha256!=='string'||! /^[0-9a-f]{64}$/.test(entry.source_identity_sha256)))throw Error('Немає збереженого відбитка джерела. ID погодження не видалено; автоматичний новий імпорт недоступний.');const rows=c03PendingRead();if(!rows.some(r=>r.proposal_id===entry.proposal_id))rows.push({proposal_id:entry.proposal_id,action:entry.action,line_id:entry.line_id??null,document_id:entry.document_id??null,allocation_keys:[...(entry.allocation_keys||[])],...(entry.action==='erp_statement_import'?{source_identity_sha256:entry.source_identity_sha256}:{})});sessionStorage.setItem(c03PendingKey(),JSON.stringify(rows));window.dispatchEvent(new window.Event('bos:statement-pending'));}
function c03PendingRemove(id){sessionStorage.setItem(c03PendingKey(),JSON.stringify(c03PendingRead().filter(r=>r.proposal_id!==id)));window.dispatchEvent(new window.Event('bos:statement-pending'));}
function c03Query(values){const p=new URLSearchParams();Object.entries(values).forEach(([k,v])=>{if(v!==''&&v!==null&&v!==undefined)p.set(k,v);});return p.toString();}
function c03SelectedCurrency(summary,currency){return summary?.currencies?.find(r=>r.currency===currency)||null;}
function c03Scope(){const r=window.BOS_RUNTIME||{};return [r.user_id,r.mode,r.role,r.access_revision].join(':');}
function useC03Requests(onDenied){
 const alive=useRef(true),controllers=useRef(new Set()),scope=useRef(c03Scope());
 useEffect(()=>{alive.current=true;const denied=()=>{onDenied?.();alive.current=false;controllers.current.forEach(c=>c.abort());};window.addEventListener('bos:session-ended',denied);return()=>{alive.current=false;controllers.current.forEach(c=>c.abort());window.removeEventListener('bos:session-ended',denied);};},[]);
 async function request(url,options={}){const c=new AbortController();controllers.current.add(c);const timer=setTimeout(()=>c.abort(),30000);try{const response=await fetch(url,{...options,signal:c.signal});if(scope.current!==c03Scope()){onDenied?.();throw Error('Сесію або права змінено.');}if([401,403,404].includes(response.status))onDenied?.();let body;try{body=await response.json();}catch{const e=Error('Відповідь сервера не прочитано.');e.status=response.status;e.responseUnreadable=true;throw e;}if(!response.ok){const e=Error(body.error||'Сервер повернув '+response.status);e.status=response.status;e.details=body.errors||[];e.code=body.code;throw e;}return body;}finally{clearTimeout(timer);controllers.current.delete(c);}}
 function stop(){alive.current=false;controllers.current.forEach(c=>c.abort());}
 return {alive,request,stop};
}
function c03Post(data){return {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)};}
function C03Errors({error,rows=[]}){return <>{error&&<p role="alert" className="erp-error">{error}</p>}{rows.length>0&&<ERPTable rows={rows} columns={[["Запис CSV",'record'],["Стовпець",'column'],["Код",'code'],["Що виправити",'message']]}/>}</>;}
function C03Totals({rows=[],title='Підсумки джерела'}){return <section><h3>{title}</h3><ERPTable rows={rows} columns={[["Валюта",'currency'],["Надходження",'in'],["Витрати",'out'],["Чистий рух",'net']]}/></section>;}
function C03StatementTotals({summary,title='Поточний стан виписки'}){return summary?.currencies?<section><h3>{title}</h3><ERPTable rows={summary.currencies} columns={[["Валюта",'currency'],["За випискою: + / − / рух",r=>[r.imported.in,r.imported.out,r.imported.net].join(' / ')],["У журналі: + / − / рух",r=>[r.recorded.in,r.recorded.out,r.recorded.net].join(' / ')],["Ще не в журналі: + / −",r=>r.unposted.in+' / '+r.unposted.out],["Надходження: рознесено / залишилось",r=>r.incoming.allocated+' / '+r.incoming.unallocated]]}/><p className="op-muted">Виписка, журнал і рознесення на рахунки — різні виміри. Їхні суми не додаються.</p></section>:null;}
function C03Facts({rows}){return <dl className="c03-facts">{rows.map(([label,value])=><React.Fragment key={label}><dt>{label}</dt><dd>{value??'—'}</dd></React.Fragment>)}</dl>;}
function C03Settlement({value,title}){return value?<section><h4>{title}</h4><C03Facts rows={[["Валюта",value.currency],["Первісна сума",value.amount],["Уже оплачено",value.paid],["Чинний кредит",value.effective_credit],["Скоригована сума",value.net_amount],["До оплати",value.receivable],["Переплата клієнта",value.customer_credit]]}/></section>:null;}
function C03Source({source}){return source?<section className="erp-confirm"><h3>Первісне перевірене джерело</h3><C03Facts rows={[["Документ",source.code+' · версія '+source.revision+' · ID '+source.document_id],["SHA-256",source.checksum],["Статус на момент перевірки",OP_STATUS[source.status]||source.status]]}/>{source.download_url&&bosCan('download_documents')&&<a className="bos-record-link" href={source.download_url}>Завантажити незмінний оригінал</a>}</section>:null;}
function C03PendingLauncher({onOpen}){const [rows,setRows]=useState([]),[error,setError]=useState('');useEffect(()=>{const read=()=>{try{setRows(c03PendingRead());setError('');}catch(e){setError(e.message);}};read();window.addEventListener('bos:statement-pending',read);return()=>window.removeEventListener('bos:statement-pending',read);},[]);return <><C03Errors error={error}/>{rows.length>0&&<details className="erp-confirm"><summary>Погодження без квитанції · {rows.length}</summary><p>Збережено лише ідентифікатори в цій вкладці. Закриття вкладки може видалити їх.</p>{rows.map(r=><div className="erp-row" key={r.proposal_id}><span>{C03_ACTIONS[r.action]} · {r.proposal_id}</span><Button onClick={()=>onOpen(r)}>Перевірити те саме погодження</Button></div>)}</details>}</>;}
// C03_HELPERS_END
