const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto');const root=__dirname,babel=require(path.join(root,'assets/babel.js')),source=fs.readFileSync(process.env.C03_REVIEW_SOURCE||path.join(root,'frontend/boss_app_source.html'),'utf8');const jsx=source.match(/<script type="text\/babel">([\s\S]*?)<\/script>/)[1].replace('{% verbatim %}','').replace('{% endverbatim %}','');
const ast=babel.transform(jsx,{presets:['react'],ast:true,code:false}).ast,body=ast.program.body;function actual(name,expose=[]){const node=body.find(n=>n.type==='FunctionDeclaration'&&n.id.name===name);if(!node)throw Error(name);let text=jsx.slice(node.start,node.end);if(expose.length){const ret=node.body.body.filter(n=>n.type==='ReturnStatement').at(-1);const offset=ret.start-node.start;text=text.slice(0,offset)+'globalThis.probe={'+expose.join(',')+'};'+text.slice(offset);}return text;}
const helper=source.slice(source.indexOf('// C03_HELPERS_BEGIN'),source.indexOf('// C03_HELPERS_END'));const formHelpers=['c03ReconcileValues','c03ReconcilePayload'].map(n=>actual(n)).join('\n');
const UUID='417a9537-3de8-4bf5-b99c-638cefcb96f0',LINE='86d7d23e-e5da-4f68-834e-9302afc56542',PROPOSAL='46dfd4b4-7666-4caa-8284-7d4705ab2cd2',IMPORT='1f54f5e1-2c0b-46a7-bb74-53e6264d8efc';const checks=[];function check(name,pass,actual){checks.push({name,passed:!!pass,...(actual!==undefined?{actual}: {})});}
function env(overrides={}){const storage=new Map(),states=[],refs=[],calls=[],events=[],runtime={user_id:7,role:'ceo',mode:'demo',access_revision:'first',as_of:'2026-09-12'};let i=0;const context={TextEncoder,URLSearchParams,AbortController,Uint8Array,Blob,FormData:class{constructor(){this.parts=[];}append(k,v){this.parts.push([k,v]);}},Set,Map,Date,console,OP:'/api/operations/',API_BASE:'/api',OP_STATUS:{},T:{},TX_CAT_LABELS:{},window:{BOS_RUNTIME:runtime,crypto:crypto.webcrypto,Event:function(type){this.type=type;},addEventListener(){},removeEventListener(){},dispatchEvent(e){events.push(e.type);}},bosRole:()=>runtime.role,bosStorageKey:key=>['bos',runtime.mode,runtime.user_id,runtime.role,key].join(':'),bosCan:()=>true,bosFinanceUUID:()=>crypto.randomUUID(),sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setTimeout,clearTimeout,React:{createElement:(type,props,...children)=>({type,props:props||{},children}),Fragment:'Fragment'},useRef:initial=>{const ref={current:initial};refs.push(ref);return ref;},useState:init=>{const index=i++;const value=Object.prototype.hasOwnProperty.call(overrides,index)?overrides[index]:typeof init==='function'?init():init;states[index]=value;return [value,next=>{states[index]=typeof next==='function'?next(states[index]):next;}];},useEffect(){},fetch:async(url,options={})=>{calls.push({url,options,pendingAtFetch:[...storage.entries()]});return {ok:true,status:200,json:async()=>({})};},C03ActionDialog(){},BoSActionDialog(){},ControlledTask(){},DocViewer(){},C03Effect(){},C03Receipt(){},C03ReconcileForm(){},C03RecordDialog(){},C03Statements(){},Button(){},Input(){},Select(){},ERPTable(){},Card(){},Badge(){},BoSInspector(){},...overrides.globals};vm.createContext(context);vm.runInContext(babel.transform(helper+'\n'+formHelpers,{presets:['react']}).code,context);return {context,storage,states,refs,calls,events,run:code=>vm.runInContext(code,context),load:(name,expose=[])=>vm.runInContext(babel.transform(actual(name,expose),{presets:['react']}).code,context)};}
function rejects(f){try{f();return false;}catch{return true;}}

async function main(){
 const original={action:'erp_statement_import',document_id:27,source_sha256:'a'.repeat(64),source_system:'synthetic-bank',account_ref:'DEMO-EUR',format:'bos_statement_csv_v1',parser_version:'1'},digest=crypto.createHash('sha256').update(JSON.stringify([original.source_sha256,original.source_system,original.account_ref])).digest('hex'),entry={proposal_id:PROPOSAL,action:original.action,line_id:null,document_id:27,allocation_keys:[],source_identity_sha256:digest},firstReceipt={state:'succeeded',schema:'bos.statement-import.v1',import_id:IMPORT,document_id:28,source_sha256:original.source_sha256,source_system:original.source_system,account_ref:original.account_ref,counts:{create:1,reuse:0},lines:[],source_totals:[],erp_event_id:44};
 async function scenario({receipt=firstReceipt,recovery=null,first=true}){const e=env(first?{7:{id:PROPOSAL,payload:original},16:true}:{});if(recovery)e.storage.set(e.context.bosStorageKey('statements-pending'),JSON.stringify([recovery]));e.load('C03ActionDialog',['confirm']);e.context.props={action:original.action,preset:first?original:{},recovery,onClose(){},onDone(){}};e.run('C03ActionDialog(props)');e.context.fetch=async(url,o)=>{e.calls.push({url,payload:JSON.parse(o.body),pending:JSON.parse([...e.storage.values()][0])});return {ok:true,status:200,json:async()=>receipt};};await e.context.probe.confirm();return e;}
 const created=await scenario({});check('import stores exact digest before first POST without raw account metadata',created.calls[0]?.pending[0].source_identity_sha256===digest&&!JSON.stringify(created.calls[0]?.pending).includes('DEMO-EUR')&&!JSON.stringify(created.calls[0]?.pending).includes('synthetic-bank'),created.calls[0]?.pending);check('legal domain replay accepts first Document differing from uploaded Document',created.states[9]?.document_id===28&&created.context.c03PendingRead().length===0);
 const wrong=await scenario({receipt:{...firstReceipt,account_ref:'OTHER-EUR'}});check('first confirm rejects wrong domain receipt and retains same pending ID',wrong.states[9]===null&&wrong.context.c03PendingRead()[0]?.proposal_id===PROPOSAL);
 const recovered=await scenario({recovery:entry,first:false});check('reopened pending uses same proposal and source digest while accepting first Document replay',recovered.calls[0]?.payload.proposal_id===PROPOSAL&&recovered.states[9]?.document_id===28&&recovered.context.c03PendingRead().length===0);
 for(const absent of [null,'invalid']){const missing=await scenario({recovery:{...entry,source_identity_sha256:absent},first:false});check('missing/invalid digest keeps unknown IDs and never sends new confirm '+String(absent),missing.calls.length===0&&missing.states[9]===null&&missing.context.c03PendingRead()[0]?.proposal_id===PROPOSAL);}
 const nc=env({1:{id:27,checksum:original.source_sha256,code:'DEMO',revision:'A'},6:{source_system:original.source_system,account_ref:original.account_ref},16:true});nc.load('C03ActionDialog',['preview']);nc.context.props={action:original.action,preset:original,onClose(){}};nc.run('C03ActionDialog(props)');nc.context.fetch=async()=>({ok:true,status:200,json:async()=>({id:null,state:'no_change',first_commit_receipt:{...firstReceipt,account_ref:'OTHER-EUR'},current_summary:{}})});await nc.context.probe.preview();check('no-change import preview verifies canonical source identity too',nc.states[10]===null);
 const payload={action:'erp_statement_reconcile',line_id:LINE,transaction:{mode:'create_transaction',category:'customer',description:'Ручна звірка'},matching:{kind:'manual',counterparty_id:9,counterparty_external_id:'CUSTOMER-001'},reason:'Звірено джерела',allocations:[]},line={id:LINE,currency:'EUR',amount:'17.39',direction:'in',counterparty_external_id:'CUSTOMER-001'},form=env().context.c03ReconcileValues(line,payload);
 const effectMismatch=env({0:{line},5:form,16:true});effectMismatch.load('C03ActionDialog',['preview']);effectMismatch.context.props={action:payload.action,preset:payload,onClose(){}};effectMismatch.run('C03ActionDialog(props)');effectMismatch.context.fetch=async()=>({ok:true,status:200,json:async()=>({id:PROPOSAL,payload,effect:{schema:'bos.statement-reconcile.v1',line_id:LINE,amount:'999.00',currency:'EUR',transaction:{mode:'create_transaction'},allocations:[]}})});await effectMismatch.context.probe.preview();check('same payload with wrong effect amount cannot expose confirm',effectMismatch.states[7]===null);
 const bytes=new TextEncoder().encode('synthetic bytes'),upload=env({0:{code:'DOC',revision:'A',title:'Source'},1:{name:'demo.csv',size:bytes.length,arrayBuffer:async()=>bytes.buffer}});upload.load('C03SourceDialog',['upload']);upload.context.props={onClose(){},onImport(){}};upload.run('C03SourceDialog(props)');upload.context.fetch=async()=>({ok:true,status:201,json:async()=>{throw Error('HTML body');}});await upload.context.probe.upload();check('unreadable successful upload response preserves unknown source intent',upload.states[2]===null&&upload.states[4]===true);
 const output={scope:'Actual extracted UI closures and independent SHA256 expected identity; controlled responses, no API/browser',source_sha256:crypto.createHash('sha256').update(source).digest('hex'),checks,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length};fs.writeFileSync(path.join(root,process.env.C03_REVIEW_OUTPUT||'IDENTITY_GREEN.json'),JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify({passed:output.passed,failed:output.failed,checks},null,2));process.exitCode=output.failed?1:0;
}main().catch(e=>{console.error(e.stack);process.exitCode=1;});
