const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto');const root=__dirname,babel=require(path.join(root,'assets/babel.js')),source=fs.readFileSync(path.join(root,'frontend/boss_app_source.html'),'utf8');const jsx=source.match(/<script type="text\/babel">([\s\S]*?)<\/script>/)[1].replace('{% verbatim %}','').replace('{% endverbatim %}','');
const ast=babel.transform(jsx,{presets:['react'],ast:true,code:false}).ast,body=ast.program.body;function actual(name,expose=[]){const node=body.find(n=>n.type==='FunctionDeclaration'&&n.id.name===name);if(!node)throw Error(name);let text=jsx.slice(node.start,node.end);if(expose.length){const ret=node.body.body.filter(n=>n.type==='ReturnStatement').at(-1);const offset=ret.start-node.start;text=text.slice(0,offset)+'globalThis.probe={'+expose.join(',')+'};'+text.slice(offset);}return text;}
const helper=source.slice(source.indexOf('// C03_HELPERS_BEGIN'),source.indexOf('// C03_HELPERS_END'));const formHelpers=['c03ReconcileValues','c03ReconcilePayload'].map(n=>actual(n)).join('\n');
const UUID='417a9537-3de8-4bf5-b99c-638cefcb96f0',LINE='86d7d23e-e5da-4f68-834e-9302afc56542',PROPOSAL='46dfd4b4-7666-4caa-8284-7d4705ab2cd2',IMPORT='1f54f5e1-2c0b-46a7-bb74-53e6264d8efc';const checks=[];function check(name,pass,actual){checks.push({name,passed:!!pass,...(actual!==undefined?{actual}: {})});}
function env(overrides={}){const storage=new Map(),states=[],refs=[],calls=[],events=[],runtime={user_id:7,role:'ceo',mode:'demo',access_revision:'first',as_of:'2026-09-12'};let i=0;const context={TextEncoder,URLSearchParams,AbortController,Uint8Array,Blob,FormData:class{constructor(){this.parts=[];}append(k,v){this.parts.push([k,v]);}},Set,Map,Date,console,OP:'/api/operations/',API_BASE:'/api',OP_STATUS:{},T:{},TX_CAT_LABELS:{},window:{BOS_RUNTIME:runtime,crypto:crypto.webcrypto,Event:function(type){this.type=type;},addEventListener(){},removeEventListener(){},dispatchEvent(e){events.push(e.type);}},bosRole:()=>runtime.role,bosStorageKey:key=>['bos',runtime.mode,runtime.user_id,runtime.role,key].join(':'),bosCan:()=>true,bosFinanceUUID:()=>crypto.randomUUID(),sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setTimeout,clearTimeout,React:{createElement:(type,props,...children)=>({type,props:props||{},children}),Fragment:'Fragment'},useRef:initial=>{const ref={current:initial};refs.push(ref);return ref;},useState:init=>{const index=i++;const value=Object.prototype.hasOwnProperty.call(overrides,index)?overrides[index]:typeof init==='function'?init():init;states[index]=value;return [value,next=>{states[index]=typeof next==='function'?next(states[index]):next;}];},useEffect(){},fetch:async(url,options={})=>{calls.push({url,options,pendingAtFetch:[...storage.entries()]});return {ok:true,status:200,json:async()=>({})};},C03ActionDialog(){},BoSActionDialog(){},ControlledTask(){},DocViewer(){},C03Effect(){},C03Receipt(){},C03ReconcileForm(){},C03RecordDialog(){},C03Statements(){},Button(){},Input(){},Select(){},ERPTable(){},Card(){},Badge(){},BoSInspector(){},...overrides.globals};vm.createContext(context);vm.runInContext(babel.transform(helper+'\n'+formHelpers,{presets:['react']}).code,context);return {context,storage,states,refs,calls,events,run:code=>vm.runInContext(code,context),load:(name,expose=[])=>vm.runInContext(babel.transform(actual(name,expose),{presets:['react']}).code,context)};}
function rejects(f){try{f();return false;}catch{return true;}}
async function main(){
 let e=env();check('money retains exact cents',e.run('c03Money("123.40")')==='123.40');check('maximum-money exact string',e.run('c03Money("999999999999.99")')==='999999999999.99');for(const value of ['1.230','1e2','+1','0','1000000000000.00',1.23])check('reject noncanonical amount '+JSON.stringify(value),rejects(()=>e.context.c03Money(value)));
 const payload={action:'erp_statement_reconcile',line_id:LINE,transaction:{mode:'create_transaction',category:'customer',description:'Ручна звірка'},matching:{kind:'manual',counterparty_id:9,counterparty_external_id:'CUSTOMER-001'},reason:'Звірено джерела',allocations:[{allocation_key:UUID,mode:'existing_payment',invoice_id:12,amount:'17.39',currency:'EUR',invoice_match:'exact_reference',reason:'Історична оплата',payment_event_id:42}]};
 e.context.payload=payload;const canonical=e.run('c03Payload(payload)');check('existing payment retains exact Event and does not request new payment',canonical.allocations[0].payment_event_id===42&&canonical.allocations[0].mode==='existing_payment'&&canonical.allocations[0].amount==='17.39');check('imported extra actor rejected',rejects(()=>e.context.c03Payload({...payload,actor_id:7})));check('nested extra paid rejected',rejects(()=>e.context.c03Payload({...payload,transaction:{...payload.transaction,paid:'17.39'}})));
 const duplicate=JSON.stringify(payload).replace('"invoice_id":12','"invoice_id":12,"invoice_id":13');check('nested duplicate JSON key rejected',rejects(()=>e.context.c03ActionJSON(duplicate)));check('multiple allocations same field names valid',!rejects(()=>e.context.c03ActionJSON(JSON.stringify({...payload,allocations:[payload.allocations[0],{...payload.allocations[0],allocation_key:crypto.randomUUID()}]}))));check('duplicate allocation key rejected',rejects(()=>e.context.c03Payload({...payload,allocations:[payload.allocations[0],payload.allocations[0]]})));
 const entry={proposal_id:PROPOSAL,action:'erp_statement_reconcile',line_id:LINE,document_id:null,allocation_keys:[UUID]};e.context.entry=entry;e.run('c03PendingSave(entry)');const saved=e.run('c03PendingRead()');check('ID-only queue no money reason or payload',Object.keys(saved[0]).sort().join(',')==='action,allocation_keys,document_id,line_id,proposal_id');e.context.window.BOS_RUNTIME.access_revision='second';check('permission revision preserves pending IDs',e.run('c03PendingRead()[0].proposal_id')===PROPOSAL);
 const many=Array.from({length:25},()=>({...entry,proposal_id:crypto.randomUUID()}));many.forEach(r=>e.context.c03PendingSave(r));check('pending queue is not truncated',e.run('c03PendingRead().length')===26);
 e=env({7:{id:PROPOSAL,payload,...{}},16:true});e.load('C03ActionDialog',['confirm','close','preview']);e.context.props={action:payload.action,preset:payload,onClose(){},onDone(){}};e.run('C03ActionDialog(props)');e.context.fetch=async(url,o)=>{e.calls.push({url,o,pending:[...e.storage.entries()]});throw Error('simulated lost reply');};await e.context.probe.confirm();check('pending IDs saved before first confirm POST',e.calls.length===1&&JSON.parse(e.calls[0].pending[0][1])[0].proposal_id===PROPOSAL);check('unknown confirm keeps same proposal and allocation key',e.states[8].proposal_id===PROPOSAL&&e.states[8].allocation_keys[0]===UUID&&[...e.storage.values()].join('').includes(UUID));
 const r=env();r.context.c03PendingSave(entry);r.load('C03ActionDialog',['confirm']);r.context.props={action:payload.action,preset:payload,onClose(){}};r.run('C03ActionDialog(props)');check('reopening same line resumes queued intent instead of new keys',r.states[8].proposal_id===PROPOSAL);let sent;r.context.fetch=async(url,o)=>{sent=JSON.parse(o.body);return {ok:false,status:409,json:async()=>({error:'Expired'})};};await r.context.probe.confirm();check('generic 409 retains pending and sends same ID',sent.proposal_id===PROPOSAL&&r.context.c03PendingRead().length===1);
 const quota=env({7:{id:PROPOSAL,payload},16:true});quota.load('C03ActionDialog',['confirm']);quota.context.props={action:payload.action,preset:payload,onClose(){}};quota.run('C03ActionDialog(props)');quota.context.sessionStorage.setItem=()=>{throw Error('quota');};await quota.context.probe.confirm();check('storage failure prevents financial confirm POST',quota.calls.length===0&&quota.states[12].includes('не надіслано'));
 for(const status of [403,404]){const denial=env({0:{line:{id:LINE}},1:{id:8},2:[{source_system:'private',account_ref:'PRIVATE'}],3:[{id:9,name:'Private'}],7:{id:PROPOSAL,payload},16:true});denial.load('C03ActionDialog',['confirm']);denial.context.props={action:payload.action,preset:payload,onClose(){}};denial.run('C03ActionDialog(props)');denial.context.fetch=async()=>({ok:false,status,json:async()=>({error:'Unavailable'})});await denial.context.probe.confirm();check('confirm '+status+' clears source panels and retains IDs',denial.states[0]===null&&denial.states[1]===null&&denial.states[2].length===0&&denial.states[3].length===0&&denial.states[14]===true&&denial.context.c03PendingRead().length===1);}
 const success=env({8:entry});success.load('C03ActionDialog',['confirm']);success.context.props={action:payload.action,recovery:entry,onClose(){},onDone(){}};success.run('C03ActionDialog(props)');success.context.fetch=async()=>({ok:true,status:200,json:async()=>({state:'succeeded',schema:'bos.statement-reconcile.v1',line_id:LINE,transaction_id:18,no_change:true,allocation_ids:[],current_summary:{allocated:'17.39',unallocated:'0.00'}})});await success.context.probe.confirm();check('confirmed no-change receipt accepts without invented Event ID',success.states[9]?.no_change===true&&success.context.c03PendingRead().length===0);
 const late=env();late.load('C03ActionDialog',['load','close']);late.context.props={action:'erp_statement_import',preset:{document_id:19},onClose(){}};late.run('C03ActionDialog(props)');late.refs[0].current={close(){}};let resolveDoc,resolveSummary;late.context.fetch=url=>new Promise(resolve=>{if(url.includes('documents'))resolveDoc=resolve;else resolveSummary=resolve;});const loading=late.context.probe.load();late.context.probe.close();resolveDoc({ok:true,status:200,json:async()=>({id:19,format:'bos_statement_csv_v1',parser_version:'1',status:'approved'})});resolveSummary({ok:true,status:200,json:async()=>({accounts:[]})});await loading;check('late read after close cannot apply source data',late.states[1]===null);
 e=env();e.context.summary={currencies:[{currency:'EUR',in:'17.39',out:'0.00',net:'17.39'},{currency:'USD',in:'123.45'},{currency:'UAH',in:'9801.07'}]};check('selected EUR total never sums USD/UAH',e.run('c03SelectedCurrency(summary,"EUR").in')==='17.39');
 const bank=actual('Bank');check('truthful net label replaces bank balance',bank.includes('Чистий рух періоду')&&!bank.includes('Баланс місяця'));const b=env({8:{direction:'in',amount:'17.39',currency:'EUR',date:'2026-09-12',description:'Синтетичний запис',category:'customer',counterparty:'7'}}); // correct index discovered below by actual hooks
 b.context.useFinanceCreateIntent=()=>({isPending:()=>false,begin:p=>({key:'test-key',body:JSON.stringify(p)}),complete(){},release(){},reset(){return true;}});b.load('Bank',['addTx']);b.context.props={settings:{currency:'EUR'},transactions:[],counterparties:[],refetch(){}};b.run('Bank(props)');
 // Bank state index 10 is form; rerender with an exact form override.
 const formIndex=b.states.findIndex(s=>s&&s.direction==='out'&&s.currency==='EUR'&&s.category==='other');const manual=env({[formIndex]:{direction:'in',amount:'17.39',currency:'EUR',date:'2026-09-12',description:'Синтетичний запис',category:'customer',counterparty:'7'}});manual.context.useFinanceCreateIntent=b.context.useFinanceCreateIntent;manual.load('Bank',['addTx']);manual.context.props=b.context.props;manual.run('Bank(props)');manual.context.fetch=async(url,o)=>{manual.calls.push({url,payload:JSON.parse(o.body)});return {ok:true,status:201,json:async()=>({id:71})};};await manual.context.probe.addTx();check('manual journal explicitly submits selected currency and exact amount',manual.calls[0]?.payload.currency==='EUR'&&manual.calls[0]?.payload.amount==='17.39',manual.calls[0]?.payload);
 const privateBytes=new TextEncoder().encode('synthetic private CSV bytes'),privateSHA=crypto.createHash('sha256').update(privateBytes).digest('hex');
 const upload=env({0:{code:'STMT-DEMO',revision:'A',title:'Синтетичний файл'},1:{name:'demo.csv',size:privateBytes.length,arrayBuffer:async()=>privateBytes.buffer}});upload.load('C03SourceDialog',['upload','choose','find','close']);upload.context.props={onClose(){},onImport(){}};upload.run('C03SourceDialog(props)');upload.context.fetch=async(url,o)=>{upload.calls.push({url,o});return {ok:false,status:502,json:async()=>({error:'Reply unavailable'})};};await upload.context.probe.upload();check('unknown source upload is separate from accounting pending',upload.states[4]===true&&upload.context.c03PendingRead().length===0&&upload.calls[0].url==='/api/statements/sources/');check('private upload exact multipart keys only',upload.calls[0].o.body.parts.map(p=>p[0]).sort().join(',')==='code,file,revision,title');check('expected original SHA kept only in dialog memory',upload.refs[3].current===privateSHA&&upload.storage.size===0);
 const mismatch=env({4:true});mismatch.load('C03SourceDialog',['choose']);mismatch.context.props={onClose(){},onImport(){}};mismatch.run('C03SourceDialog(props)');mismatch.refs[3].current=privateSHA;mismatch.context.fetch=async()=>({ok:true,status:200,json:async()=>({id:27,format:'bos_statement_csv_v1',checksum:'0'.repeat(64)})});await mismatch.context.probe.choose(27);check('source recovery rejects same code/revision with wrong SHA',mismatch.states[2]===null&&mismatch.states[4]===true&&mismatch.states[6].includes('SHA-256'));
 const uploadLocked=env({4:true});uploadLocked.load('C03SourceDialog',['upload']);uploadLocked.context.props={onClose(){},onImport(){}};uploadLocked.run('C03SourceDialog(props)');await uploadLocked.context.probe.upload();check('unknown upload cannot automatically POST another copy',uploadLocked.calls.length===0);
 const imports={action:'erp_statement_import',document_id:27,source_sha256:privateSHA,source_system:'synthetic-bank',account_ref:'DEMO-EUR',format:'bos_statement_csv_v1',parser_version:'1'};
 for(const input of [imports,payload]){const assistant=env({6:JSON.stringify(input)});assistant.context.useLocalState=(key,initial)=>assistant.context.useState(initial);assistant.load('OperationsAssistant',['importAction']);assistant.context.props={refetchTasks(){}};assistant.run('OperationsAssistant(props)');await assistant.context.probe.importAction();check('actual Assistant dispatches '+input.action+' to dedicated C03 form',assistant.states[9]?.action===input.action&&assistant.calls.length===0);}
 const manager=env({6:JSON.stringify(payload)});manager.context.window.BOS_RUNTIME.role='manager';manager.context.useLocalState=(key,initial)=>manager.context.useState(initial);manager.load('OperationsAssistant',['importAction']);manager.context.props={refetchTasks(){}};manager.run('OperationsAssistant(props)');await manager.context.probe.importAction();check('actual Assistant denies C03 to manager before reads',manager.states[9]===null&&manager.calls.length===0&&manager.states[7].includes('CEO'));
 const output={scope:'Actual extracted candidate JavaScript and React closures, controlled state/storage/transport; no browser/API/DB execution',source_sha256:crypto.createHash('sha256').update(source).digest('hex'),checks,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length};fs.writeFileSync(path.join(root,'UI_PROOF.json'),JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify({passed:output.passed,failed:output.failed,failures:checks.filter(c=>!c.passed)},null,2));process.exitCode=output.failed?1:0;
}main().catch(e=>{console.error(e.stack);process.exitCode=1;});
