const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto');const root=__dirname,babel=require(path.join(root,'assets/babel.js')),source=fs.readFileSync(path.join(root,'frontend/boss_app_source.html'),'utf8');const jsx=source.match(/<script type="text\/babel">([\s\S]*?)<\/script>/)[1].replace('{% verbatim %}','').replace('{% endverbatim %}','');
const ast=babel.transform(jsx,{presets:['react'],ast:true,code:false}).ast,body=ast.program.body;function actual(name,expose=[]){const node=body.find(n=>n.type==='FunctionDeclaration'&&n.id.name===name);if(!node)throw Error(name);let text=jsx.slice(node.start,node.end);if(expose.length){const ret=node.body.body.filter(n=>n.type==='ReturnStatement').at(-1);const offset=ret.start-node.start;text=text.slice(0,offset)+'globalThis.probe={'+expose.join(',')+'};'+text.slice(offset);}return text;}
const helper=source.slice(source.indexOf('// C03_HELPERS_BEGIN'),source.indexOf('// C03_HELPERS_END'));const formHelpers=['c03ReconcileValues','c03ReconcilePayload'].map(n=>actual(n)).join('\n');
const UUID='417a9537-3de8-4bf5-b99c-638cefcb96f0',LINE='86d7d23e-e5da-4f68-834e-9302afc56542',PROPOSAL='46dfd4b4-7666-4caa-8284-7d4705ab2cd2',IMPORT='1f54f5e1-2c0b-46a7-bb74-53e6264d8efc';const checks=[];function check(name,pass,actual){checks.push({name,passed:!!pass,...(actual!==undefined?{actual}: {})});}
function env(overrides={}){const storage=new Map(),states=[],refs=[],calls=[],events=[],runtime={user_id:7,role:'ceo',mode:'demo',access_revision:'first',as_of:'2026-09-12'};let i=0;const context={TextEncoder,URLSearchParams,AbortController,Uint8Array,Blob,FormData:class{constructor(){this.parts=[];}append(k,v){this.parts.push([k,v]);}},Set,Map,Date,console,OP:'/api/operations/',API_BASE:'/api',OP_STATUS:{},T:{},TX_CAT_LABELS:{},window:{BOS_RUNTIME:runtime,crypto:crypto.webcrypto,Event:function(type){this.type=type;},addEventListener(){},removeEventListener(){},dispatchEvent(e){events.push(e.type);}},bosRole:()=>runtime.role,bosStorageKey:key=>['bos',runtime.mode,runtime.user_id,runtime.role,key].join(':'),bosCan:()=>true,bosFinanceUUID:()=>crypto.randomUUID(),sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setTimeout,clearTimeout,React:{createElement:(type,props,...children)=>({type,props:props||{},children}),Fragment:'Fragment'},useRef:initial=>{const ref={current:initial};refs.push(ref);return ref;},useState:init=>{const index=i++;const value=Object.prototype.hasOwnProperty.call(overrides,index)?overrides[index]:typeof init==='function'?init():init;states[index]=value;return [value,next=>{states[index]=typeof next==='function'?next(states[index]):next;}];},useEffect(){},fetch:async(url,options={})=>{calls.push({url,options,pendingAtFetch:[...storage.entries()]});return {ok:true,status:200,json:async()=>({})};},C03ActionDialog(){},BoSActionDialog(){},ControlledTask(){},DocViewer(){},C03Effect(){},C03Receipt(){},C03ReconcileForm(){},C03RecordDialog(){},C03Statements(){},Button(){},Input(){},Select(){},ERPTable(){},Card(){},Badge(){},BoSInspector(){},...overrides.globals};vm.createContext(context);vm.runInContext(babel.transform(helper+'\n'+formHelpers,{presets:['react']}).code,context);return {context,storage,states,refs,calls,events,run:code=>vm.runInContext(code,context),load:(name,expose=[])=>vm.runInContext(babel.transform(actual(name,expose),{presets:['react']}).code,context)};}
function rejects(f){try{f();return false;}catch{return true;}}

async function main(){
 const node=body.find(n=>n.type==='FunctionDeclaration'&&n.id.name==='App');const render=node.body.body.find(n=>n.type==='VariableDeclaration'&&n.declarations.some(d=>d.id.name==='renderContent')).declarations[0].init;const renderSource=jsx.slice(render.start,render.end);const routing=env({globals:{section:'finance',sub:'bank',bosCanView:()=>true,transactions:[{id:17,currency:'EUR'}],contracts:[],refetchTransactions(){},BoSReadOnlyRecords:function LegacyManagerJournal(){},Bank:function FinancialBank(){}}});routing.context.window.BOS_RUNTIME.role='manager';routing.run('globalThis.renderContent='+babel.transform('const route='+renderSource,{presets:['react']}).code.replace(/^const route = /,'').replace(/;$/,''));const rendered=routing.context.renderContent();check('manager actual App bank route preserves legacy read-only component without Bank',rendered.type===routing.context.BoSReadOnlyRecords&&routing.calls.length===0);
 for(const status of [403,404]){let denials=0;const e=env();e.context.onDenied=()=>denials++;const hooks=e.run('useC03Requests(onDenied)');e.context.fetch=async()=>({ok:false,status,json:async()=>{throw Error('HTML denial body');}});try{await hooks.request('/api/statements/lines/'+LINE+'/');}catch{}check('non-JSON '+status+' invokes source clearing before parser error',denials>0,{denials});}
 const payload={action:'erp_statement_reconcile',line_id:LINE,transaction:{mode:'create_transaction',category:'customer',description:'Ручна звірка'},matching:{kind:'manual',counterparty_id:9,counterparty_external_id:'CUSTOMER-001'},reason:'Звірено джерела',allocations:[{allocation_key:UUID,mode:'existing_payment',invoice_id:12,amount:'17.39',currency:'EUR',invoice_match:'exact_reference',reason:'Історична оплата',payment_event_id:42}]};
 const line={id:LINE,currency:'EUR',amount:'17.39',direction:'in',counterparty_external_id:'CUSTOMER-001'},form=env().context.c03ReconcileValues(line,payload);
 const preview=env({0:{line},5:form,16:true});preview.load('C03ActionDialog',['preview']);preview.context.props={action:payload.action,preset:payload,onClose(){}};preview.run('C03ActionDialog(props)');preview.context.fetch=async()=>({ok:true,status:200,json:async()=>({id:PROPOSAL,payload:{...payload,line_id:'c7d2e0b0-b6f1-4a57-a962-8a8cb0b50c54'},effect:{schema:'bos.statement-reconcile.v1',line_id:'c7d2e0b0-b6f1-4a57-a962-8a8cb0b50c54',amount:'17.39',currency:'EUR'}})});await preview.context.probe.preview();check('preview refuses another line intent before exposing confirm',preview.states[7]===null,{proposalAccepted:!!preview.states[7]});
 const bytes=new TextEncoder().encode('synthetic source'),upload=env({0:{code:'STMT-DEMO',revision:'A',title:'Синтетичний файл'},1:{name:'demo.csv',size:bytes.length,arrayBuffer:async()=>bytes.buffer}});upload.load('C03SourceDialog',['upload']);upload.context.props={onClose(){},onImport(){}};upload.run('C03SourceDialog(props)');upload.context.fetch=async()=>({ok:true,status:201,json:async()=>({id:27,code:'STMT-OTHER',revision:'B',format:'bos_statement_csv_v1',checksum:'0'.repeat(64)})});await upload.context.probe.upload();check('upload201 refuses mismatched source SHA and metadata',upload.states[2]===null&&upload.states[4]===true,{sourceAccepted:!!upload.states[2],unknown:upload.states[4]});
 const output={scope:'Actual extracted source closures and actual App route, controlled responses; no browser/API',source_sha256:crypto.createHash('sha256').update(source).digest('hex'),checks,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length};fs.writeFileSync(path.join(root,process.env.C03_REVIEW_OUTPUT||'REVIEW_GREEN.json'),JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify(output,null,2));process.exitCode=output.failed?1:0;
}main().catch(e=>{console.error(e.stack);process.exitCode=1;});
