# Generated by Django 6.0.5 on 2026-08-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
