# Generated by Django 6.0.5 on 2026-08-23 13:33

from django.db import migrations

# Короткие названия по коду филиала. Словарь из ТЗ, берётся как есть:
# украинские падежи и областные центры эвристикой из полных названий
# не выводятся.
SHORT = {
    # Обласні управління → обласний центр
    'UA-05': 'Вінниця',        'UA-07': 'Луцьк',
    'UA-12': 'Дніпро',         'UA-14': 'Донецьк',
    'UA-18': 'Житомир',        'UA-21': 'Ужгород',
    'UA-23': 'Запоріжжя',      'UA-26': 'Івано-Франківськ',
    'UA-32': 'Київська обл.',  'UA-35': 'Кропивницький',
    'UA-44': 'Луганськ',       'UA-46': 'Львів',
    'UA-48': 'Миколаїв',       'UA-51': 'Одеса',
    'UA-53': 'Полтава',        'UA-56': 'Рівне',
    'UA-59': 'Суми',           'UA-61': 'Тернопіль',
    'UA-63': 'Харків',         'UA-65': 'Херсон',
    'UA-68': 'Хмельницький',   'UKRAINE': 'Україна',

    # Закордонні представництва → країна в називному відмінку
    'FR-CA': 'Канада',         'FR-CZ': 'Чехія',
    'FR-DE': 'Німеччина',      'FR-ES': 'Іспанія',
    'FR-FR': 'Франція',        'FR-GB': 'Велика Британія',
    'FR-HU': 'Угорщина',       'FR-IT': 'Італія',
    'FR-MD': 'Молдова',        'FR-NL': 'Нідерланди',
    'FR-PL': 'Польща',         'FR-PT': 'Португалія',
    'FR-RO': 'Румунія',        'FR-SE': 'Швеція',
    'FR-SK': 'Словаччина',     'FR-US': 'США',
    'FOREIGN': 'Іноземні філії',

    # Київські управління → ключове слово функції
    'KY-01': 'Організація',    'KY-02': 'Фінанси',
    'KY-03': 'Персонал',       'KY-04': 'ІТ',
    'KY-05': 'Правове',        'KY-06': 'Матеріальне',

    'HQ': 'Центральний офіс',  'KYIV': 'Київ',
    'MOBILE': 'Мобільний офіс',
}


def fill_short_names(apps, schema_editor):
    Branch = apps.get_model('branches', 'Branch')
    # update() по коду: идемпотентно (повторный прогон не меняет данные)
    # и молча пропускает коды, которых в базе нет.
    for code, short in SHORT.items():
        Branch.objects.filter(code=code).update(short_name=short)


def clear_short_names(apps, schema_editor):
    Branch = apps.get_model('branches', 'Branch')
    Branch.objects.all().update(short_name='')


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_short_name'),
    ]

    operations = [
        migrations.RunPython(fill_short_names, clear_short_names),
    ]
