# Generated by Django 6.0.5 on 2026-06-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_taskchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaudeUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[('chat', 'Chat'), ('meeting', 'Meeting'), ('dictate', 'Dictate')], max_length=10)),
                ('model', models.CharField(max_length=50)),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_assistant.chatmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
