# Generated by Django 6.0.5 on 2026-07-01 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_employeechangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='chat_files/%Y/%m/')),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('parsed_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attached_file', to='ai_assistant.chatmessage')),
            ],
        ),
    ]
