# Generated by Django 6.0.5 on 2026-07-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_chatfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='claudeusagelog',
            name='endpoint',
            field=models.CharField(choices=[('chat', 'Chat'), ('meeting', 'Meeting'), ('dictate', 'Dictate')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='employeechangelog',
            name='employee_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='taskchangelog',
            name='task_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
