# Generated by Django 6.0.5 on 2026-09-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_alter_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeechangelog',
            name='undone_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
