# Generated by Django 6.0.5 on 2026-09-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_chatmessage_archived_at_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfile',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
