# Generated by Django 6.0.5 on 2026-09-12 14:04

import django.db.models.deletion
from django.db import migrations, models
from boss_project.migration_operations import PreserveSequenceAddField


def refuse_task_history_loss(apps,schema_editor):
    Task=apps.get_model('tasks','Task')
    rows=Task.objects.using(schema_editor.connection.alias)
    if rows.filter(models.Q(assignee_employee_id__isnull=False)|models.Q(sales_order_id__isnull=False)|models.Q(archived_at__isnull=False)|(models.Q(result__isnull=False)&~models.Q(result=''))).exists():
        raise RuntimeError('Відкат C01 видалив би відповідальність, результат чи архів; зупинено до DDL.')


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_user'),
        ('erp', '0005_source_corrections'),
        ('tasks', '0004_task_branch'),
    ]

    operations = [
        PreserveSequenceAddField(
            model_name='task',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        PreserveSequenceAddField(
            model_name='task',
            name='assignee_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='employees.employee'),
        ),
        PreserveSequenceAddField(
            model_name='task',
            name='result',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        PreserveSequenceAddField(
            model_name='task',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_tasks', to='erp.salesorder'),
        ),
        migrations.RunPython(migrations.RunPython.noop,refuse_task_history_loss),
    ]
