const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const babel=require(path.join(root,'assets/babel.js'));
let html=fs.readFileSync(path.join(root,'frontend/boss_app_source.html'),'utf8');
const bos3Content=JSON.parse(fs.readFileSync(path.join(root,'frontend/bos3_content.json'),'utf8'));
if(bos3Content.schema!=='bos.training.content.v1'||!Array.isArray(bos3Content.cases))throw new Error('Invalid BoS 3 learning content registry');
const contentScript='<script>window.BOS3_CONTENT='+JSON.stringify(bos3Content).replace(/</g,'\\u003c')+';</script>';
if(!html.includes('<!-- BOS3_CONTENT_PLACEHOLDER -->'))throw new Error('BoS 3 content placeholder missing');
html=html.replace('<!-- BOS3_CONTENT_PLACEHOLDER -->',contentScript);
const design=fs.readFileSync(path.join(root,'frontend/bos_design.css'),'utf8');
if(!html.includes('<!-- BOS_DESIGN_STYLES -->'))throw new Error('BoS design placeholder missing');
html=html.replace('<!-- BOS_DESIGN_STYLES -->','<style id="bos-product-design">'+design+'</style>');
const match=html.match(/<script type="text\/babel">([\s\S]*?)<\/script>/);
if(!match)throw new Error('JSX entrypoint missing');
const jsx=match[1].replace('{% verbatim %}','').replace('{% endverbatim %}','');
const compiled=babel.transform(jsx,{presets:['react'],filename:'bos-app.jsx',compact:false}).code;
fs.writeFileSync(path.join(root,'assets/app.js'),compiled);
html=html.replace(match[0],'<script src="/assets/app.js"></script>');
const map={'react.production.min.js':'react.js','react-dom.production.min.js':'react-dom.js','marked.min.js':'marked.js','purify.min.js':'purify.js'};
html=html.replace(/<script src="([^"]+)"[\s\S]*?<\/script>/g,(tag,url)=>{
 if(url.includes('babel.min.js'))return '';
 if(['/assets/app.js','/assets/network-map.js'].includes(url))return tag;
 const key=Object.keys(map).find(k=>url.endsWith('/'+k));
 if(!key)throw new Error('Unexpected script URL');
 return `<script src="/assets/${map[key]}"></script>`;
});
html=html.replace(/<link[^>]*href="https:\/\/fonts\.[^>]+>/g,'');
fs.writeFileSync(path.join(root,'frontend/boss_app_html.html'),html);
console.log('JSX compiled; local script assets wired.');
