// Actual JSX and actual global fetch wrapper, controlled hooks/storage/HTTP only.
// The server in the lost-response case is a model; this is not a DB/browser proof.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),babel=require(path.join(root,'assets/babel.js'));
const html=fs.readFileSync(path.join(root,'frontend/boss_app_source.html'),'utf8');
const moneySource=html.slice(html.indexOf('function erpAmount('),html.indexOf('const erpDateTime='));
assert(moneySource.includes('const erpMoney='),'Actual monetary formatter must be available');
const source=html.slice(html.indexOf('const ERP_ACTIONS='),html.indexOf('function purchaseRemaining('));
const code=babel.transform(source,{presets:['react'],compact:false}).code;
const wrapper=html.split('\n').find(line=>line.startsWith('window.fetch=(url,options={})=>'));
assert(wrapper,'Actual global fetch identity wrapper must be tested');
const id='11111111-1111-4111-8111-111111111111';
function storage(){const rows=new Map();return {rows,fail:false,get length(){return rows.size;},key(n){return [...rows.keys()][n]??null;},getItem(key){if(this.fail)throw Error('Storage disabled');return rows.get(key)??null;},setItem(key,value){if(this.fail)throw Error('Storage disabled');rows.set(key,value);},removeItem(key){rows.delete(key);}};}
function harness(opts={}){
 let hooks=[],cursor=0,dirty=true,tree,pendingEffects=[],unmounted=false,closed=0,done=0;const requests=[],events=new Map(),timers=new Map();let timerId=0;
 const store=opts.storage||storage(),document={cookie:'csrftoken='+(opts.csrf||'synthetic-csrf-token-one')};
 const window={BOS_RUNTIME:{user_id:1,mode:'working',role:opts.role||'ceo',access_revision:'r1'},crypto:{subtle:{digest:async(_,bytes)=>crypto.createHash('sha256').update(bytes).digest()}},Event:class{constructor(type){this.type=type;}}};
 window.addEventListener=(name,fn)=>{if(!events.has(name))events.set(name,new Set());events.get(name).add(fn);};window.removeEventListener=(name,fn)=>events.get(name)?.delete(fn);window.dispatchEvent=event=>{for(const fn of [...events.get(event.type)||[]])fn(event);};
 const React={createElement(type,props,...children){props=props||{};if(props.ref&&props.ref.current===null)props.ref.current={showModal(){},close(){closed++;}};return {type,props,children};},Fragment:'fragment'};
 const context={React,window,document,sessionStorage:store,console,TextEncoder,Uint8Array,AbortController,Headers,URL,location:{origin:'http://bos.test',href:'http://bos.test/'},
  bosHttpScope:()=>{const r=window.BOS_RUNTIME;return r?[r.user_id,r.mode,r.role,r.access_revision].join(':'):'';},bosRole:()=>window.BOS_RUNTIME?.role||'observer',bosCanAction:action=>window.BOS_RUNTIME?.role==='ceo'||(window.BOS_RUNTIME?.role==='manager'&&action!=='payment'),ERP_LABELS:{},erpNum:x=>x,
  Button:function Button(){},Input:function Input(){},Select:function Select(){},ImpactTable:function ImpactTable(){},
  setTimeout(fn){const n=++timerId;timers.set(n,fn);return n;},clearTimeout(n){timers.delete(n);},
  bosMeasuredFetch:(url,options)=>new Promise((resolve,reject)=>{requests.push({url,options,resolve,reject});if(!opts.ignoreAbort)options.signal?.addEventListener('abort',()=>reject(Object.assign(Error('Timed out'),{name:'AbortError'})));}),
  useState(initial){const i=cursor++;if(!hooks[i])hooks[i]={value:typeof initial==='function'?initial():initial};return [hooks[i].value,value=>{if(unmounted)return;hooks[i].value=typeof value==='function'?value(hooks[i].value):value;dirty=true;}];},
  useRef(initial){const i=cursor++;if(!hooks[i])hooks[i]={current:initial};return hooks[i];},
  useEffect(fn,deps){const i=cursor++,old=hooks[i];if(!old||deps.some((value,j)=>value!==old.deps[j])){hooks[i]={deps,cleanup:old?.cleanup};pendingEffects.push(()=>{hooks[i].cleanup?.();hooks[i].cleanup=fn();});}}
 };
 vm.createContext(context);vm.runInContext(moneySource,context);vm.runInContext(wrapper,context);context.fetch=(...args)=>window.fetch(...args);
 vm.runInContext(code+'\nthis.Component='+(opts.launcher?'ERPConfirmRecovery':'ERPActionDialog')+';this.readBinding=erpPendingBinding;this.readPending=erpPendingRead;',context);
 const data={items:[],lots:[],lines:[],orders:[],invoices:[{invoice_id:7,code:'INV-7',open:'999999999999.99',currency:'UAH'}],partners:[],employees:[],documents:[],jobs:[],reservations:[]};
 const props=opts.launcher?{}:{action:opts.action||'payment',preset:opts.preset||{invoice_id:7,amount:'1200.01',reference:'CONTROLLED-PAY'},recovery:opts.recovery||null,data,onClose(){closed++;},onDone:opts.onDone||(()=>{done++;})};
 function render(){if(unmounted)return;cursor=0;dirty=false;tree=context.Component(props);while(pendingEffects.length)pendingEffects.shift()();}
 async function flush(){for(let n=0;n<10;n++){await new Promise(resolve=>setImmediate(resolve));if(dirty)render();}}
 function all(node,out=[]){if(arguments.length===0)node=tree;if(node==null||node===false)return out;if(Array.isArray(node)){node.forEach(v=>all(v,out));return out;}if(typeof node==='object'){out.push(node);all(node.children,out);}return out;}
 function text(node){if(arguments.length===0)node=tree;if(node==null||node===false)return '';if(Array.isArray(node))return node.map(value=>text(value)).join(' ');return typeof node==='object'?text(node.children):String(node);}
 function button(label){const node=all().find(n=>typeof n.props?.onClick==='function'&&text(n)===label);assert(node,'Missing button '+label+' in '+text());return node;}
 function click(label){const node=button(label);assert(!node.props.disabled,'Disabled '+label);return node.props.onClick();}
 function reply(n,status,body,extra={}){assert(requests[n],'Missing request '+n);requests[n].resolve({ok:status>=200&&status<300,status,headers:new Headers(extra.headers||{'X-BoS-Access':'r1'}),json:async()=>{if(extra.unreadable)throw Error('Bad JSON');return body;}});}
 async function preview(){const form=all().find(n=>n.type==='form');assert(form,'No editable form');form.props.onSubmit({preventDefault(){}});await flush();}
 async function prepared(){await preview();const n=requests.length-1;assert.equal(requests[n]?.url,'/api/erp/preview/');const payload=JSON.parse(requests[n].options.body);reply(n,200,{id,payload,effect:{},impact:[]});await flush();return payload;}
 function unmount(){unmounted=true;hooks.forEach(h=>h?.cleanup?.());}
 render();return {window,document,store,requests,context,props,all,text,button,click,reply,preview,prepared,flush,render,unmount,emit:name=>window.dispatchEvent(new window.Event(name)),timeout:()=>{for(const fn of [...timers.values()])fn();},get closed(){return closed;},get done(){return done;}};
}
function receipt(extra={}){return {state:'succeeded',erp_event_id:31,invoice_id:7,paid:'1200.01',impact:[],...extra};}
function sent(h){return h.requests.filter(r=>r.url==='/api/operations/confirm/').map(r=>JSON.parse(r.options.body));}
function entries(h){return [...h.store.rows.values()].flatMap(value=>JSON.parse(value));}
// Render the actual parent and both actual dialog components with independent hook
// lifetimes. A parent render which drops a child runs its cleanup, aborting its
// pending request just as the component contract requires. This deliberately
// does not implement a DOM or claim React/browser acceptance.
const workpoints=html.slice(html.indexOf('// Workpoint facts are a separate'),html.indexOf('function BoSHome('));
const dialogRouter=html.split('\n').find(line=>line.startsWith('function BoSActionDialog('));
assert(dialogRouter,'Actual dialog router must be tested');
const integratedCode=babel.transform(source+'\n'+dialogRouter+'\n'+workpoints,{presets:['react'],compact:false}).code;
function integratedFixture(){
 const branch={id:1,code:'UA-KYIV',name:'Київ · контрольний приклад',short_name:'Київ',type:'regional',lat:50.45,lng:30.52};
 return {facts:{schema:'bos.workpoints.v1',access_revision:'r1',generated_at:'2026-09-20T12:00:00Z',scope:'visible_records',points:[{branch,location_ids:[],order_ids:[3],lot_ids:[],movement_ids:[],invoice_ids:[7],document_ids:[],stock:[],money:[],completeness:'complete',movement_scope:'latest_300_visible_global'}]},snapshot:{branches:[branch],orders:[{id:3,branch_id:1,code:'SO-CONTROLLED',status:'confirmed',currency:'UAH'}],invoices:[{invoice_id:7,code:'INV-7',currency:'UAH',open:'2000.00'}],locations:[],lots:[],movements:[],documents:[],items:[],employees:[],partners:[],lines:[],jobs:[],reservations:[]}};
}
function integratedHarness({ignoreAbort=false}={}){
 let tree,active=null,dirty=true,unmounted=false,cursor=0,closed=0,refetched=0,timerId=0;
 const instances=new Map(),requests=[],events=new Map(),timers=new Map(),store=storage();
 const document={cookie:'csrftoken=synthetic-csrf-token-one'};
 const window={BOS_RUNTIME:{user_id:1,mode:'working',role:'ceo',access_revision:'r1'},crypto:{subtle:{digest:async(_,bytes)=>crypto.createHash('sha256').update(bytes).digest()}},Event:class{constructor(type){this.type=type;}}};
 window.addEventListener=(name,fn)=>{if(!events.has(name))events.set(name,new Set());events.get(name).add(fn);};
 window.removeEventListener=(name,fn)=>events.get(name)?.delete(fn);
 window.dispatchEvent=event=>{for(const fn of [...events.get(event.type)||[]])fn(event);};
 const React={Fragment:'fragment',createElement(type,props,...children){return {type,props:props||{},children};}};
 const context={React,window,document,sessionStorage:store,console,TextEncoder,Uint8Array,AbortController,Headers,URL,location:{origin:'http://bos.test',href:'http://bos.test/'},
  bosHttpScope:()=>{const r=window.BOS_RUNTIME;return r?[r.user_id,r.mode,r.role,r.access_revision].join(':'):'';},bosRole:()=>window.BOS_RUNTIME?.role||'observer',bosCan:key=>key==='finance'?window.BOS_RUNTIME?.role==='ceo':true,bosCanAction:()=>window.BOS_RUNTIME?.role==='ceo',b03IsAction:()=>false,ERP_LABELS:{},erpDate:x=>x||'—',erpNum:x=>x,
  Button:function Button(){},Input:function Input(){},Select:function Select(){},Card:function Card(){},BoSLink:function BoSLink(){},NextAction:function NextAction(){},BoSInspector:function BoSInspector(){},DocViewer:function DocViewer(){},ImpactTable:function ImpactTable(){},
  setTimeout(fn){const n=++timerId;timers.set(n,fn);return n;},clearTimeout(n){timers.delete(n);},
  bosMeasuredFetch:(url,options)=>new Promise((resolve,reject)=>{const request={url,options,resolve,reject,aborted:false};requests.push(request);options.signal?.addEventListener('abort',()=>{request.aborted=true;if(!ignoreAbort)reject(Error('Aborted'));});}),
  useState(initial){assert(active,'Hook outside mounted component');const instance=active,i=cursor++;if(!instance.hooks[i])instance.hooks[i]={value:typeof initial==='function'?initial():initial};return [instance.hooks[i].value,value=>{if(unmounted||instance.removed)return;instance.hooks[i].value=typeof value==='function'?value(instance.hooks[i].value):value;dirty=true;}];},
  useRef(initial){assert(active);const i=cursor++;if(!active.hooks[i])active.hooks[i]={current:initial};return active.hooks[i];},
  useEffect(fn,deps){assert(active);const instance=active,i=cursor++,old=instance.hooks[i];if(!old||deps.some((value,j)=>value!==old.deps[j])){instance.hooks[i]={deps,cleanup:old?.cleanup};instance.effects.push(()=>{instance.hooks[i].cleanup?.();instance.hooks[i].cleanup=fn();});}}
 };
 vm.createContext(context);vm.runInContext(moneySource,context);vm.runInContext(wrapper,context);context.fetch=(...args)=>window.fetch(...args);
 vm.runInContext(integratedCode+'\nthis.components={WorkpointsPanel,BoSActionDialog,ERPActionDialog};',context);
 const executable=new Set(Object.values(context.components));
 function remove(instance){instance.removed=true;instance.hooks.forEach(h=>h?.cleanup?.());}
 function resolve(node,key,visited){
  if(node==null||node===false)return node;
  if(Array.isArray(node))return node.map((child,n)=>resolve(child,key+'/'+n,visited));
  if(typeof node!=='object')return node;
  if(executable.has(node.type)){
   const componentKey=key+':'+node.type.name+':'+(node.props.key||'');visited.add(componentKey);
   let instance=instances.get(componentKey);if(!instance){instance={hooks:[],effects:[],removed:false,type:node.type};instances.set(componentKey,instance);}
   const parent=active,previousCursor=cursor;active=instance;cursor=0;
   const output=node.type(node.props);active=parent;cursor=previousCursor;
   return {...node,children:[resolve(output,componentKey+'/output',visited)]};
  }
  if(node.props.ref&&node.props.ref.current===null)node.props.ref.current={showModal(){},close(){closed++;}};
  return {...node,children:resolve(node.children,key+'/children',visited)};
 }
 function render(){if(unmounted)return;dirty=false;const visited=new Set();tree=resolve({type:context.components.WorkpointsPanel,props:{onNavigate(){},refetchTasks(){refetched++;}},children:[]},'root',visited);for(const [key,instance] of instances){if(!visited.has(key)){remove(instance);instances.delete(key);}}for(const instance of instances.values())while(instance.effects.length)instance.effects.shift()();}
 async function flush(){for(let n=0;n<12;n++){await new Promise(resolve=>setImmediate(resolve));if(dirty)render();}}
 function all(node,out=[]){if(arguments.length===0)node=tree;if(node==null||node===false)return out;if(Array.isArray(node)){node.forEach(value=>all(value,out));return out;}if(typeof node==='object'){out.push(node);all(node.children,out);}return out;}
 function text(node){if(arguments.length===0)node=tree;if(node==null||node===false)return '';if(Array.isArray(node))return node.map(value=>text(value)).join(' ');return typeof node==='object'?text(node.children):String(node);}
 function click(label){const node=all().find(n=>typeof n.props?.onClick==='function'&&text(n)===label);assert(node,'Missing integrated button '+label+' in '+text());assert(!node.props.disabled);return node.props.onClick();}
 function reply(n,status,body,extra={}){assert(requests[n],'Missing integrated request '+n);requests[n].resolve({ok:status>=200&&status<300,status,headers:new Headers(extra.headers||{'X-BoS-Access':'r1'}),json:extra.json||async function(){return body;}});}
 async function pair(start=0){const fixture=integratedFixture();reply(start,200,fixture.facts);await flush();reply(start+1,200,fixture.snapshot);await flush();reply(start+2,200,fixture.facts);await flush();}
 async function prepared(){await pair();const next=all().find(n=>n.type===context.NextAction);assert(next);next.props.onAction('payment',{invoice_id:7,amount:'1200.01',reference:'CONTROLLED-PAY'});await flush();await pair(3);const form=all().find(n=>n.type==='form');assert(form);form.props.onSubmit({preventDefault(){}});await flush();assert.equal(requests[6].url,'/api/erp/preview/');reply(6,200,{id,payload:JSON.parse(requests[6].options.body),effect:{},impact:[]});await flush();}
 function unmount(){unmounted=true;for(const instance of instances.values())remove(instance);instances.clear();}
 render();return {context,window,store,requests,all,text,click,reply,pair,prepared,flush,unmount,emit:name=>window.dispatchEvent(new window.Event(name)),get refetched(){return refetched;},get closed(){return closed;},hasDialog:()=>[...instances.values()].some(instance=>instance.type===context.components.ERPActionDialog)};
}
const results=[];async function run(name,fn){await fn();results.push(name);console.log('PASS '+name);}
(async()=>{
 await run('lost success response replays exactly one controlled server operation',async()=>{const h=harness();await h.prepared();h.click('Погодити й виконати');await h.flush();let operations=0;const receipts=new Map();const server=request=>{const key=JSON.parse(request.options.body).proposal_id;if(!receipts.has(key)){operations++;receipts.set(key,receipt());}return receipts.get(key);};server(h.requests[1]);h.requests[1].reject(Error('Response lost'));await h.flush();assert.equal(operations,1);assert.match(h.text(),/Результат погодження невідомий/);assert(!h.all().some(n=>n.type==='form'));h.click('Повторити це саме погодження');await h.flush();h.reply(2,200,server(h.requests[2]));await h.flush();assert.equal(operations,1);assert.deepEqual(sent(h),[{proposal_id:id,confirmed:true},{proposal_id:id,confirmed:true}]);assert.equal(h.done,1);assert.match(h.text(),/Операцію виконано/);assert.equal(entries(h).length,0);h.unmount();});
 await run('repeated 503, generic 409 and unreadable 200 retain same pending identity',async()=>{const h=harness();await h.prepared();h.click('Погодити й виконати');await h.flush();h.reply(1,503,{error:'Unavailable'});await h.flush();for(const [status,extra] of [[409,{}],[200,{unreadable:true}]]){h.click('Повторити це саме погодження');await h.flush();h.reply(h.requests.length-1,status,{error:'Conflict'},extra);await h.flush();assert.equal(entries(h)[0].proposal_id,id);assert(!h.all().some(n=>n.type==='form'));}assert(sent(h).every(r=>r.proposal_id===id));assert.equal(h.done,0);h.unmount();});
 await run('close and reload keep IDs only; launcher never confirms automatically',async()=>{const h=harness();await h.prepared();h.click('Погодити й виконати');await h.flush();h.requests[1].reject(Error('Lost'));await h.flush();const raw=JSON.stringify([...h.store.rows]);assert(!raw.includes('1200.01')&&!raw.includes('CONTROLLED-PAY')&&!raw.includes('synthetic-csrf-token-one'));assert.deepEqual(Object.keys(entries(h)[0]).sort(),['action','proposal_id']);h.click('Закрити, зберігши відновлення');h.unmount();const launcher=harness({launcher:true,storage:h.store});await launcher.flush();assert.match(launcher.text(),/погодження без отриманої квитанції/);assert.equal(launcher.requests.length,0);launcher.click('Відновити погодження');await launcher.flush();const child=launcher.all().find(n=>n.props?.recovery);assert.equal(child.props.recovery.proposal_id,id);launcher.unmount();const restored=harness({storage:h.store,recovery:child.props.recovery});await restored.flush();assert.equal(restored.requests.length,0);restored.click('Повторити це саме погодження');await restored.flush();assert.deepEqual(sent(restored),[{proposal_id:id,confirmed:true}]);restored.reply(0,200,receipt());await restored.flush();assert.match(restored.text(),/Операцію виконано/);restored.unmount();});
 await run('double click sends one confirm and blocks stale editable handlers',async()=>{const h=harness();await h.prepared();const button=h.button('Погодити й виконати');button.props.onClick();button.props.onClick();await h.flush();assert.equal(sent(h).length,1);assert(!h.all().some(n=>n.type==='form'));h.reply(1,200,receipt());await h.flush();h.unmount();});
 await run('new dialog cannot create preview over same-action unfinished intent',async()=>{const h=harness();await h.prepared();h.click('Погодити й виконати');await h.flush();h.requests[1].reject(Error('Lost'));await h.flush();h.unmount();const second=harness({storage:h.store});await second.preview();assert.equal(second.requests.length,0);assert.match(second.text(),/Спершу перевірте незавершене/);assert(!second.all().some(n=>n.type==='form'));second.unmount();});
 await run('first definitive validation refusal permits explicit corrected preview',async()=>{const h=harness();await h.prepared();h.click('Погодити й виконати');await h.flush();h.reply(1,422,{error:'Payment exceeds balance'});await h.flush();assert.equal(entries(h).length,0);assert(h.all().some(n=>n.type==='form'));assert.equal(h.requests.length,2);await h.preview();assert.equal(h.requests.length,3);h.unmount();});
 await run('validation refusal after uncertain response does not erase prior commit possibility',async()=>{const h=harness();await h.prepared();h.click('Погодити й виконати');await h.flush();h.requests[1].reject(Error('Lost'));await h.flush();h.click('Повторити це саме погодження');await h.flush();h.reply(2,422,{error:'Current input no longer valid'});await h.flush();assert.equal(entries(h).length,1);assert(!h.all().some(n=>n.type==='form'));h.unmount();});
 await run('actual global wrapper 401 and access header mismatch clear IDs and suppress old receipt',async()=>{for(const extra of [{status:401,headers:{}},{status:200,headers:{'X-BoS-Access':'r2'}},{status:200,headers:{'X-BoS-Identity':'denied'}}]){const h=harness();await h.prepared();h.click('Погодити й виконати');await h.flush();assert.equal(h.requests[1].options.headers.get('X-CSRFToken'),'synthetic-csrf-token-one');h.reply(1,extra.status,receipt(),{headers:extra.headers});await h.flush();assert.match(h.text(),/Погодження недоступне/);assert.doesNotMatch(h.text(),/1200|CONTROLLED|INV-7/);assert.equal(entries(h).length,0);assert.equal(h.done,0);h.unmount();}});
 await run('permission 403 hides old values without interpreting body as success',async()=>{const h=harness();await h.prepared();h.click('Погодити й виконати');await h.flush();h.reply(1,403,receipt(),{unreadable:true});await h.flush();assert.match(h.text(),/Погодження недоступне/);assert.equal(h.done,0);h.unmount();});
 await run('role change without event suppresses late success and any retry',async()=>{const h=harness();await h.prepared();h.click('Погодити й виконати');await h.flush();h.window.BOS_RUNTIME.role='observer';h.reply(1,200,receipt());await h.flush();assert.match(h.text(),/Погодження недоступне/);assert.equal(h.done,0);h.unmount();});
 await run('late preview and confirmation after unmount cannot call onDone',async()=>{for(const confirming of [false,true]){const h=harness({ignoreAbort:true});if(confirming){await h.prepared();h.click('Погодити й виконати');await h.flush();}else await h.preview();const n=h.requests.length-1;h.unmount();h.reply(n,200,confirming?receipt():{id,payload:{action:'erp_payment'},effect:{},impact:[]});await h.flush();assert.equal(h.done,0);if(confirming)assert.equal(entries(h).length,1);}});
 await run('new CSRF session binding hides previous IDs and pending values',async()=>{const h=harness();await h.prepared();h.click('Погодити й виконати');await h.flush();h.requests[1].reject(Error('Lost'));await h.flush();h.unmount();const other=harness({launcher:true,storage:h.store,csrf:'new-synthetic-csrf'});await other.flush();assert.doesNotMatch(other.text(),new RegExp(id));assert.equal(other.requests.length,0);other.unmount();});
 await run('unavailable binding or storage prevents sending a new confirmation',async()=>{const h=harness();await h.prepared();h.store.fail=true;h.click('Погодити й виконати');await h.flush();assert.equal(sent(h).length,0);assert.match(h.text(),/Storage disabled/);h.unmount();const bad=harness();bad.document.cookie='';await bad.preview();assert.equal(bad.requests.length,0);assert.match(bad.text(),/Погодження недоступне|Не вдалося підготувати/);bad.unmount();});
 await run('timeout keeps pending ID and offers explicit retry',async()=>{const h=harness();await h.prepared();h.click('Погодити й виконати');await h.flush();h.timeout();await h.flush();assert.equal(entries(h).length,1);assert.match(h.text(),/Результат погодження невідомий/);assert.equal(sent(h).length,1);h.unmount();});
 await run('malformed or wrong-action receipt cannot clear pending ID',async()=>{for(const value of [receipt({state:'running'}),receipt({invoice_id:999}),{state:'succeeded',erp_event_id:31,reservation_id:7,impact:[]}]){const h=harness();await h.prepared();h.click('Погодити й виконати');await h.flush();h.reply(1,200,value);await h.flush();assert.equal(entries(h).length,1);assert.equal(h.done,0);assert.match(h.text(),/перевіреної квитанції/);h.unmount();}});
 await run('successful receipt survives synchronous or async refresh failure',async()=>{for(const onDone of [()=>{throw Error('Refresh');},async()=>{throw Error('Refresh');}]){const h=harness({onDone});await h.prepared();h.click('Погодити й виконати');await h.flush();h.reply(1,200,receipt());await h.flush();assert.match(h.text(),/Операцію виконано, але/);assert.equal(entries(h).length,0);assert.equal(sent(h).length,1);assert(!h.all().some(n=>n.type==='form'));h.unmount();}});
 await run('Decimal input is preserved and manager can recover allowed reserve receipt',async()=>{const h=harness({preset:{invoice_id:7,amount:'999999999999.99',reference:'EXACT'}});const payload=await h.prepared();assert.equal(payload.amount,'999999999999.99');h.unmount();const manager=harness({role:'manager',action:'reserve',preset:{lot_id:2,line_id:3,quantity:'0.125'}});const reserve=await manager.prepared();assert.equal(reserve.quantity,'0.125');manager.click('Погодити й виконати');await manager.flush();manager.reply(1,200,{state:'succeeded',erp_event_id:32,reservation_id:4,quantity:'0.125',impact:[]});await manager.flush();assert.equal(manager.done,1);manager.unmount();});
 await run('session end during pending request clears only ERP recovery storage',async()=>{const h=harness({ignoreAbort:true});h.store.setItem('unrelated','preserved');await h.prepared();h.click('Погодити й виконати');await h.flush();h.emit('bos:session-ended');h.reply(1,200,receipt());await h.flush();assert.equal(h.done,0);assert.equal(h.store.getItem('unrelated'),'preserved');assert.equal([...h.store.rows.keys()].filter(k=>k.startsWith('bos:erp-confirm:')).length,0);h.unmount();});
 await run('actual parent keeps confirming dialog mounted across success headers before delayed body',async()=>{for(const refreshStatus of [409,503]){const h=integratedHarness();await h.prepared();h.click('Погодити й виконати');await h.flush();assert.equal(sent(h).length,1);let deliverBody,bodyRead=false;const body=new Promise(resolve=>{deliverBody=resolve;});h.reply(7,200,null,{json(){bodyRead=true;return body;}});await h.flush();assert(bodyRead);assert(h.hasDialog(),'Parent invalidation unmounted the confirming dialog before receipt');assert(!h.requests[7].aborted,'Parent cleanup aborted the confirming request');assert.match(h.text(),/Дані змінилися/);assert.doesNotMatch(h.text(),/SO-CONTROLLED/);assert.match(h.text(),new RegExp(id));assert.equal(entries(h).length,1);assert.equal(h.requests.length,8);deliverBody(receipt());await h.flush();assert.equal(entries(h).length,0);assert.equal(h.requests[8].url,'/api/erp/workpoints/');h.reply(8,refreshStatus,{error:'Controlled refresh failure'});await h.flush();assert.match(h.text(),/Операцію збережено/);assert.match(h.text(),refreshStatus===409?/Записи змінилися/:/Не вдалося перевірити/);assert.doesNotMatch(h.text(),/SO-CONTROLLED/);assert(!h.hasDialog());assert.equal(h.refetched,1);assert.equal(sent(h).length,1);h.unmount();}});
 await run('actual parent preserves pending dialog on unrelated invalidation and explicit same-ID recovery',async()=>{const h=integratedHarness();await h.prepared();h.click('Погодити й виконати');await h.flush();h.emit('bos:data-changed');await h.flush();assert(h.hasDialog());assert(!h.requests[7].aborted);h.requests[7].reject(Error('Response lost'));await h.flush();h.click('Повторити це саме погодження');await h.flush();assert.deepEqual(sent(h),[{proposal_id:id,confirmed:true},{proposal_id:id,confirmed:true}]);h.reply(8,200,receipt());await h.flush();h.reply(9,503,{error:'Refresh unavailable'});await h.flush();assert.match(h.text(),/Операцію збережено/);assert.equal(entries(h).length,0);assert.equal(h.refetched,1);h.unmount();});
 await run('actual parent discards unsubmitted or definitively refused dialog on data invalidation',async()=>{for(const refused of [false,true]){const h=integratedHarness();await h.prepared();if(refused){h.click('Погодити й виконати');await h.flush();h.reply(7,422,{error:'Validation refused'});await h.flush();assert(h.all().some(n=>n.type==='form'));assert.equal(entries(h).length,0);}h.emit('bos:data-changed');await h.flush();assert(!h.hasDialog());assert.doesNotMatch(h.text(),/CONTROLLED-PAY|INV-7|SO-CONTROLLED/);assert.equal(sent(h).length,refused?1:0);h.unmount();}});
 await run('actual parent auth revocation before delayed receipt hides data and blocks late onDone',async()=>{const h=integratedHarness({ignoreAbort:true});await h.prepared();h.click('Погодити й виконати');await h.flush();let deliverBody;h.reply(7,200,null,{json:()=>new Promise(resolve=>{deliverBody=resolve;})});await h.flush();assert(h.hasDialog());h.emit('bos:session-ended');await h.flush();assert(!h.hasDialog());deliverBody(receipt());await h.flush();assert.equal(h.refetched,0);assert.equal(h.requests.length,8);assert.equal(entries(h).length,0);assert.doesNotMatch(h.text(),/Операцію збережено|CONTROLLED-PAY|INV-7|SO-CONTROLLED/);h.unmount();});
 console.log(JSON.stringify({schema:'bos.confirmation-recovery-controlled.v1',passed:results.length,scope:'controlled actual JSX/global fetch, including nested WorkpointsPanel and dialog lifetimes; no browser, DOM, Django, database or TCP execution'},null,2));
})().catch(error=>{console.error(error.stack);process.exitCode=1;});
