// Actual PurchaseDocumentMatch JSX, controlled read scheduling; no browser claim.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const raw=fs.readFileSync(path.join(__dirname,'check_flow_projections.cjs'),'utf8'),end=raw.indexOf('const results=[]');assert(end>0);
const context={require,__dirname,console,setImmediate,setTimeout,clearTimeout,AbortController};vm.createContext(context);vm.runInContext(raw.slice(0,end)+'\nthis.make=harness;',context);
function fixture(){const sha='a'.repeat(64),claim=value=>({value,evidence:{page:1,source:'Сторінка 1',start:0,end:value.length,quote:value,source_sha256:sha}});return {schema:'bos.document-match-read.v1',purchase_id:31,document_id:41,access_revision:'r1',generated_at:'2026-09-20',draft:{schema:'bos.document-match.v1',provider:'mock.synthetic-invoice.v1',source:{document_id:41,code:'SYN-DOCUMENT',revision:'A',sha256:sha},decision:'accept_draft',operation_proposal:null,exceptions:[],fields:{supplier_edrpou:claim('30900001'),invoice_number:claim('SOURCE-EXACT'),invoice_date:claim('2026-09-20'),currency:claim('UAH'),tax_basis:claim('excluding_VAT'),total:claim('12000.01'),lines:[{item_code:claim('SYN-ITEM'),revision:claim('A'),unit:claim('pcs'),quantity:claim('10.000'),unit_price:claim('1200.00'),line_total:claim('12000.01')}]},matches:{supplier_id:11,item_id:21,purchase_id:31,receipt_ids:[51,52]},comparison:null}};}
function harness(role='ceo'){const documents=[],h=context.make('document',role,{purchase:{id:31,code:'SYN-PO'},data:{documents:[{id:41,code:'SYN-DOCUMENT',revision:'A',title:'Synthetic'}],partners:[{id:11,type:'supplier',name:'Explicit supplier'}],items:[{id:21,code:'SYN-ITEM',revision:'A',name:'Synthetic'}]},onDocument:id=>documents.push(id)});h.openedDocuments=documents;return h;}
async function selected(h){await h.choose(0,'41');await h.choose(1,'11');await h.choose(2,'21');assert.equal(h.requests.length,0);h.button('Зіставити документ').props.onClick();await h.flush();}
const results=[];async function run(name,fn){await fn();results.push({name,status:'PASS'});console.log('PASS '+name);}
(async()=>{
 await run('explicit IDs and user click; actual source claims, no posting control',async()=>{const h=harness();await selected(h);assert.equal(h.requests[0].url,'/api/erp/purchases/31/document-match/?document_id=41&supplier_id=11&item_id=21');h.reply(0,fixture());await h.flush();assert.match(h.text(),/Синтетична чернетка узгоджена/);assert.match(h.text(),/SOURCE-EXACT/);assert.match(h.text(),/12000\.01/);assert.match(h.text(),/SHA-256/);assert.match(h.text(),/Приймання:\s+№51, №52/);assert.doesNotMatch(h.text(),/Погодити й виконати/);h.button('Відкрити оригінал документа').props.onClick();assert.equal(h.openedDocuments[0],41);assert(h.requests.every(r=>!r.options.method||r.options.method==='GET'));h.unmount();});
 await run('ordinary source has explicit unsupported result and no invented fields',async()=>{const h=harness();await selected(h);const f=fixture();f.draft.fields=null;f.draft.matches=null;f.draft.decision='needs_information';f.draft.exceptions=['unsupported_document'];h.reply(0,f);await h.flush();assert.match(h.text(),/Формат змісту не підтримується/);assert.doesNotMatch(h.text(),/SOURCE-EXACT|12000\.01|чернетка узгоджена/);h.unmount();});
 await run('selection change suppresses old in-flight source without auto-retry',async()=>{const h=harness();await selected(h);await h.choose(1,'');h.reply(0,fixture());await h.flush();assert.equal(h.requests.length,1);assert.doesNotMatch(h.text(),/SOURCE-EXACT|12000\.01/);h.unmount();});
 await run('revoked session suppresses late private claim',async()=>{const h=harness();await selected(h);h.emit('bos:session-ended');h.reply(0,fixture());await h.flush();assert.doesNotMatch(h.text(),/SOURCE-EXACT|12000\.01/);h.unmount();});
 await run('wrong evidence hash, wrong source, nonnull proposal and nonCEO fail closed',async()=>{for(const bad of ['hash','source','proposal','role']){const h=harness(bad==='role'?'observer':'ceo');await selected(h);const f=fixture();if(bad==='hash')f.draft.fields.total.evidence.source_sha256='b'.repeat(64);if(bad==='source')f.draft.source.document_id=42;if(bad==='proposal')f.draft.operation_proposal={id:'forbidden'};h.reply(0,f);await h.flush();assert.doesNotMatch(h.text(),/SOURCE-EXACT|12000\.01|чернетка узгоджена/);h.unmount();}});
 console.log(JSON.stringify({scope:'5 actual JSX controlled cases, not browser or posting acceptance',results},null,2));
})().catch(error=>{console.error(error);process.exitCode=1;});
