// Actual JSX + controlled hooks/network. This is not browser acceptance.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),babel=require(path.join(root,'assets/babel.js'));
const html=fs.readFileSync(path.join(root,'frontend/boss_app_source.html'),'utf8');
const section=html.slice(html.indexOf('// Scoped order facts;'),html.indexOf('function BoSInspector('));
const compiled=babel.transform(section,{presets:['react']}).code;
function supply(target=null){return {schema:'bos.supply-options.v1',access_revision:'r1',generated_at:'2026-09-20T12:00:00Z',scope:'visible_sources',line:{id:3,item_id:8,unit:'шт.',revision:'A'},target_location:target?{id:target}:null,supported:true,completeness:'complete',basis:'Очікуване не є гарантованим запасом',quantities:{remaining:'9007199254740993.125',reserved_usable:'0.000',quantity_to_cover:'5.000',available_all_locations:'2.000',available_target:target?'0.000':null,target_gap:target?'5.000':null,uncovered_after_stock:'3.000',unallocated_expected:'2.000',indicative_after_expected:'1.000'},stock:[{lot_id:4,code:'LOT-EXACT',location:{id:2,code:'WH-SOURCE'},revision:'A',quantity:'2.000',available:'2.000',eligible:true,unit:'шт.',reason:'available',document_ids:[]}],waiting:[],purchases:[],limits:{has_more:{}}};}
function settlement(){const money={currency:'UAH',gross_invoiced:'10.01',credited:'0.00',invoiced:'10.01',paid:'0.01',open:'10.00',customer_credit:'0.00'};return {schema:'bos.order-settlement.v1',access_revision:'r1',generated_at:'2026-09-20T12:00:00Z',scope:'linked_invoices',order:{id:7},totals:[money],invoices:[{...money,invoice_id:9,code:'INV-EXACT',due_date:'2026-10-01',payment_history:{status:'complete',recorded_total:'0.01',difference:'0.00',entries:[{event_id:10,amount:'0.01',currency:'UAH',reference:'REF-10',issues:[],created_at:'2026-09-20'}]},adjustments:[],has_more:{}}],payment_history_status:'complete',limits:{has_more:{}},basis:'Облікова оплата, без конвертації'};}
function harness(kind='supply',role='ceo'){
 let hooks=[],cursor=0,dirty=true,pending=[],tree,unmounted=false;
 const requests=[],events=new Map(),actions=[],window={BOS_RUNTIME:{user_id:1,mode:'working',role,access_revision:'r1'}};
 window.addEventListener=(name,fn)=>{if(!events.has(name))events.set(name,new Set());events.get(name).add(fn);};window.removeEventListener=(name,fn)=>events.get(name)?.delete(fn);
 const context={window,console,AbortController,setTimeout,clearTimeout,React:{Fragment:'fragment',createElement(type,props,...children){return {type,props:props||{},children};}},Button:function Button(){},Select:function Select(){},erpDate:x=>x,bosRole:()=>window.BOS_RUNTIME.role,bosCanAction:a=>window.BOS_RUNTIME.role==='ceo',c03Scope:()=>Object.values(window.BOS_RUNTIME).join(':'),
 fetch:(url,options)=>new Promise((resolve,reject)=>{requests.push({url,options,resolve,reject});}),
 useState(initial){const i=cursor++;if(!hooks[i])hooks[i]={value:typeof initial==='function'?initial():initial};return [hooks[i].value,value=>{if(!unmounted){hooks[i].value=typeof value==='function'?value(hooks[i].value):value;dirty=true;}}];},
 useRef(initial){const i=cursor++;if(!hooks[i])hooks[i]={current:initial};return hooks[i];},
 useEffect(fn,deps){const i=cursor++,old=hooks[i];if(!old||deps.some((v,j)=>v!==old.deps[j])){hooks[i]={deps,cleanup:old?.cleanup};pending.push(()=>{hooks[i].cleanup?.();hooks[i].cleanup=fn();});}}};
 vm.createContext(context);vm.runInContext(compiled+'\nthis.Component='+(kind==='supply'?'OrderSupplyOptions':'OrderSettlement')+';',context);
 const props={orderId:7,data:{lines:[{id:3,order_id:7,item_id:8,revision:'A'}],items:[{id:8,code:'ITEM',method:'buy'}],locations:[{id:2,code:'WH-SOURCE'},{id:5,code:'WH-TARGET'}]},onAction:(...args)=>actions.push(args)};
 function render(){cursor=0;dirty=false;tree=context.Component(props);while(pending.length)pending.shift()();}
 async function flush(){for(let i=0;i<8;i++){await new Promise(resolve=>setImmediate(resolve));if(dirty)render();}}
 function walk(node,out){if(node==null||node===false)return out;if(Array.isArray(node)){node.forEach(n=>walk(n,out));return out;}if(typeof node==='object'){out.push(node);walk(node.children,out);}return out;}
 function all(){return walk(tree,[]);}
 function words(node){if(node==null||node===false)return '';if(Array.isArray(node))return node.map(words).join(' ');return typeof node==='object'?words(node.children):String(node);}
 function text(node=tree){return words(node);}
 function button(label){const result=all().find(n=>n.props?.onClick&&text(n).includes(label));assert(result,'Missing '+label);return result;}
 function reply(i,body,status=200){requests[i].resolve({ok:status===200,status,headers:{get:()=>body.access_revision||'r1'},json:async()=>body});}
 async function choose(index,value){all().filter(n=>n.type===context.Select)[index].props.onChange({target:{value}});await flush();}
 function emit(name){for(const fn of events.get(name)||[])fn();}
 function unmount(){unmounted=true;hooks.forEach(h=>h?.cleanup?.());}
 render();return {requests,actions,window,context,flush,all,text,button,reply,choose,emit,unmount};
}
const results=[];async function run(name,fn){await fn();results.push({name,status:'PASS'});console.log('PASS '+name);}
(async()=>{
 await run('explicit position and destination; exact Decimal and safe action presets',async()=>{const h=harness();assert.equal(h.requests.length,0);await h.choose(0,'3');assert.equal(h.requests[0].url,'/api/erp/lines/3/supply-options/');h.reply(0,supply());await h.flush();assert.match(h.text(),/9007199254740993\.125/);assert(!h.all().some(n=>n.props.onClick&&h.text(n).includes('Перемістити ·')));h.button('Підготувати закупівлю').props.onClick();const [a,p]=h.actions[0];assert.equal(a,'purchase');for(const key of ['price','supplier_id','due_date'])assert.equal(p[key],'');assert.equal(p.quantity,'3.000');await h.choose(1,'5');assert.equal(h.requests[1].url,'/api/erp/lines/3/supply-options/?target_location_id=5');h.reply(1,supply(5));await h.flush();h.button('Перемістити ·').props.onClick();assert.equal(h.actions[1][0],'transfer');assert.equal(h.actions[1][1].location_id,5);assert.equal(h.actions[1][1].quantity,'');h.unmount();});
 await run('changed selection rejects delayed old target response',async()=>{const h=harness();await h.choose(0,'3');await h.choose(1,'5');h.reply(0,supply());await h.flush();assert.doesNotMatch(h.text(),/LOT-EXACT/);h.reply(1,supply(5));await h.flush();assert.match(h.text(),/LOT-EXACT/);h.unmount();});
 await run('read conflict clears sources with no automatic retry',async()=>{const h=harness();await h.choose(0,'3');h.reply(0,{},409);await h.flush();assert.equal(h.requests.length,1);assert.doesNotMatch(h.text(),/LOT-EXACT/);h.button('Оновити забезпечення').props.onClick();assert.equal(h.requests.length,2);h.unmount();});
 await run('session revocation clears finance and rejects delayed response',async()=>{const h=harness('settlement');h.emit('bos:session-ended');h.reply(0,settlement());await h.flush();assert.doesNotMatch(h.text(),/INV-EXACT|10\.01/);h.unmount();});
 await run('data change clears loaded facts and actions without automatic read',async()=>{const h=harness('settlement');h.reply(0,settlement());await h.flush();assert.match(h.text(),/INV-EXACT/);h.emit('bos:data-changed');await h.flush();assert.doesNotMatch(h.text(),/INV-EXACT/);assert.equal(h.requests.length,1);h.unmount();});
 await run('settlement links exact invoice into ordinary payment confirmation',async()=>{const h=harness('settlement');h.reply(0,settlement());await h.flush();assert.match(h.text(),/REF-10/);h.button('Зареєструвати оплату ·').props.onClick();assert.equal(h.actions[0][0],'payment');assert.equal(h.actions[0][1].invoice_id,9);assert.equal(h.actions[0][1].amount,'10.00');h.unmount();});
 await run('restricted supply never renders inferred availability or controls',async()=>{const h=harness('supply','observer');await h.choose(0,'3');const f=supply();f.completeness='restricted';for(const key of Object.keys(f.quantities))if(key!=='remaining')f.quantities[key]=null;f.stock[0].available=null;f.stock[0].eligible=null;h.reply(0,f);await h.flush();assert.match(h.text(),/LOT-EXACT/);assert.doesNotMatch(h.text(),/Резервувати ·|Підготувати закупівлю/);h.unmount();});
 await run('financial role mismatch and numeric money fail closed',async()=>{for(const role of ['observer','ceo']){const h=harness('settlement',role),f=settlement();if(role==='ceo')f.totals[0].open=10;h.reply(0,f);await h.flush();assert.doesNotMatch(h.text(),/INV-EXACT|10\.01/);h.unmount();}});
 console.log(JSON.stringify({scope:'8 actual JSX controlled tests; not browser acceptance',results},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
