// Actual JSX with controlled hooks and network scheduling; no browser/DOM/E2E claim.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),babel=require(path.join(root,'assets/babel.js'));
const html=fs.readFileSync(path.join(root,'frontend/boss_app_source.html'),'utf8');
const section=html.slice(html.indexOf('// Workpoint facts are a separate'),html.indexOf('function BoSHome('));
const formSection=html.slice(html.indexOf('const ERP_ACTIONS='),html.indexOf('function purchaseRemaining('));
const compiled=babel.transform(section,{presets:['react'],compact:false}).code;
const compiledForm=babel.transform(formSection,{presets:['react'],compact:false}).code;
function fixture(){const branch={id:1,code:'UA-KYIV',name:'Київ · навчальна точка',short_name:'Київ',type:'regional',lat:50.45,lng:30.52};return {facts:{schema:'bos.workpoints.v1',access_revision:'r1',generated_at:'2026-09-20T12:00:00Z',scope:'visible_records',points:[{branch,location_ids:[2],order_ids:[3],lot_ids:[4],movement_ids:[5],invoice_ids:[6],document_ids:[7],stock:[{item_id:8,code:'ITEM-8',name:'Виріб',unit:'шт.',quantity:'9007199254740993.125',reserved:'1.000',available:'9007199254740992.125',lot_ids:[4]}],money:[{currency:'UAH',invoiced:'0.03',paid:'0.02',open:'0.01',gross_invoiced:'0.04',credited:'0.01',customer_credit:'0.00',invoice_ids:[6]}],completeness:'complete',movement_scope:'latest_300_visible_global'}]},snapshot:{branches:[branch],locations:[{id:2,branch_id:1,code:'WH-UA',name:'Склад'}],orders:[{id:3,branch_id:1,code:'SO-UA',status:'confirmed',currency:'UAH'}],lots:[{id:4,code:'LOT-UA',item_id:8}],movements:[{id:5,lot_id:4,quantity:'0.125',kind:'shipment'}],invoices:[{invoice_id:6,code:'INV-UA',currency:'UAH'}],documents:[{id:7,code:'SPEC-UA',revision:'A',title:'Навчальне джерело'}],items:[{id:8,code:'ITEM-8',name:'Виріб',unit:'шт.'}],employees:[],partners:[],lines:[],jobs:[],events:[]}};}
function harness(role='ceo',form=null){
 let hooks=[],cursor=0,dirty=true,tree=null,pending=[],unmounted=false;const requests=[],events=new Map();
 const window={BOS_RUNTIME:{user_id:1,mode:'demo',role,access_revision:'r1'}};
 window.addEventListener=(name,fn)=>{if(!events.has(name))events.set(name,new Set());events.get(name).add(fn);};window.removeEventListener=(name,fn)=>events.get(name)?.delete(fn);
 const React={createElement(type,props,...children){props=props||{};if(props.ref&&props.ref.current===null)props.ref.current={showModal(){},close(){}};if(type===context.ERPTable&&!form)return {type:'table',props,children:props.rows.map(r=>props.columns.map(([,field])=>typeof field==='function'?field(r):r[field]))};return {type,props,children};},Fragment:'fragment'};
 const context={React,window,console,AbortController,setTimeout,clearTimeout,Number,Object,Array,Error,Set,Math,bosHttpScope:()=>{const r=window.BOS_RUNTIME;return r?[r.user_id,r.mode,r.role,r.access_revision].join(':'):'';},bosRole:()=>window.BOS_RUNTIME?.role||'observer',bosCan:key=>key==='finance'?window.BOS_RUNTIME?.role==='ceo':true,bosCanAction:()=>window.BOS_RUNTIME?.role!=='observer',ERP_LABELS:{confirmed:'Підтверджено'},erpDate:x=>x||'—',erpNum:x=>x,Button:function Button(){},Input:function Input(){},Select:function Select(){},Card:function Card(){},BoSLink:function BoSLink(){},ERPTable:function ERPTable(){},NextAction:function NextAction(){},BoSInspector:function BoSInspector(){},BoSActionDialog:function BoSActionDialog(){},DocViewer:function DocViewer(){},ImpactTable:function ImpactTable(){},fetch:(url,options={})=>new Promise((resolve,reject)=>{requests.push({url,options,resolve,reject});options.signal?.addEventListener('abort',()=>reject(Error('aborted')));}),useState(initial){const i=cursor++;if(!hooks[i])hooks[i]={value:typeof initial==='function'?initial():initial};return [hooks[i].value,value=>{if(unmounted)return;hooks[i].value=typeof value==='function'?value(hooks[i].value):value;dirty=true;}];},useRef(initial){const i=cursor++;if(!hooks[i])hooks[i]={current:initial};return hooks[i];},useEffect(fn,deps){const i=cursor++,old=hooks[i];if(!old||deps.some((v,j)=>v!==old.deps[j])){hooks[i]={deps,cleanup:old?.cleanup};pending.push(()=>{hooks[i].cleanup?.();hooks[i].cleanup=fn();});}}};
 context.erpFetch=(url,payload)=>{requests.push({url,payload});return Promise.resolve({id:'p1',payload,effect:{},impact:[]});};
 vm.createContext(context);vm.runInContext((form?compiledForm:compiled)+'\nthis.Component='+(form?'ERPActionDialog':'WorkpointsPanel')+';',context);
 const props=form?{action:form.action||'order',preset:form.preset||{},data:fixture().snapshot,onClose(){},onDone(){}}:{onNavigate(){},refetchTasks(){}};
 function render(){if(unmounted)return;cursor=0;dirty=false;tree=context.Component(props);while(pending.length)pending.shift()();}
 async function flush(){for(let n=0;n<12;n++){await new Promise(resolve=>setImmediate(resolve));if(dirty)render();}}
 function all(node=tree,out=[]){if(node==null||node===false)return out;if(Array.isArray(node)){node.forEach(x=>all(x,out));return out;}if(typeof node==='object'){out.push(node);all(node.children,out);}return out;}
 function text(node=tree){if(node==null||node===false)return '';if(Array.isArray(node))return node.map(text).join(' ');return typeof node==='object'?text(node.children):String(node);}
 function button(label){const found=all().find(n=>typeof n.props?.onClick==='function'&&text(n).includes(label));assert(found,'Missing button '+label);return found;}
 function reply(index,status,body,revision='r1'){requests[index].resolve({ok:status>=200&&status<300,status,headers:{get:name=>name==='X-BoS-Access'?revision:null},json:async()=>body});}
 async function pair(start=0,f=fixture(),status=200,last=f.facts){reply(start,status,f.facts);await flush();if(status!==200)return;reply(start+1,200,f.snapshot);await flush();reply(start+2,200,last);await flush();}
 function emit(name){for(const fn of events.get(name)||[])fn();}
 function unmount(){unmounted=true;hooks.forEach(h=>h?.cleanup?.());}
 render();return {requests,window,render,flush,text,all,button,reply,pair,emit,unmount,context};
}
const results=[];async function run(name,fn){await fn();results.push({name,status:'PASS'});console.log('PASS '+name);}
(async()=>{
 await run('exact Decimal strings and grouped sources render without aggregation',async()=>{const h=harness();await h.pair();await h.flush();assert.match(h.text(),/9007199254740993\.125/);assert.match(h.text(),/0\.03/);assert.match(h.text(),/UAH/);assert.match(h.text(),/останніх 300/);assert.match(h.text(),/SPEC-UA/);h.unmount();});
 await run('restricted role renders unavailable balances without financial totals',async()=>{const h=harness('observer'),f=fixture();f.facts.points[0].money=null;f.facts.points[0].stock[0].available=null;f.facts.points[0].completeness='restricted';await h.pair(0,f);await h.flush();assert.match(h.text(),/Недоступно/);assert.match(h.text(),/Грошові показники недоступні/);assert.doesNotMatch(h.text(),/0\.03|Нове замовлення/);h.unmount();});
 await run('money accidentally returned to observer fails closed',async()=>{const h=harness('observer');await h.pair();await h.flush();assert.match(h.text(),/Не вдалося перевірити/);assert.doesNotMatch(h.text(),/SO-UA|0\.03/);h.unmount();});
 await run('unknown snapshot reference rejects entire paired read',async()=>{const h=harness(),f=fixture();f.facts.points[0].order_ids=[999];await h.pair(0,f);await h.flush();assert.match(h.text(),/Не вдалося перевірити/);assert.doesNotMatch(h.text(),/SPEC-UA/);h.unmount();});
 await run('body identity mismatch and numeric money rejected',async()=>{for(const edit of [f=>f.facts.access_revision='old',f=>f.facts.points[0].money[0].paid=0.02]){const h=harness(),f=fixture();edit(f);await h.pair(0,f);await h.flush();assert.match(h.text(),/Не вдалося перевірити/);assert.doesNotMatch(h.text(),/SO-UA/);h.unmount();}});
 await run('changed amount with the same IDs between public brackets fails closed',async()=>{const h=harness(),f=fixture(),last=JSON.parse(JSON.stringify(f.facts));last.points[0].money[0].paid='0.03';last.points[0].money[0].open='0.00';await h.pair(0,f,200,last);assert.match(h.text(),/Записи змінилися/);assert.doesNotMatch(h.text(),/SO-UA|0\.03/);assert.equal(h.requests.map(r=>r.url).join(','),'/api/erp/workpoints/,/api/erp/snapshot/,/api/erp/workpoints/');h.unmount();});
 await run('generated timestamp alone may change between optimistic brackets',async()=>{const h=harness(),f=fixture(),last=JSON.parse(JSON.stringify(f.facts));last.generated_at='2026-09-20T12:00:02Z';await h.pair(0,f,200,last);assert.match(h.text(),/SO-UA/);assert.doesNotMatch(h.text(),/Записи змінилися/);h.unmount();});
 await run('409 yields manual refresh only and clears previous data',async()=>{const h=harness();await h.pair();await h.flush();h.button('Оновити робочі точки').props.onClick();await h.pair(3,fixture(),409);await h.flush();assert.equal(h.requests.length,4);assert.match(h.text(),/Записи змінилися/);assert.doesNotMatch(h.text(),/SO-UA/);h.unmount();});
 await run('late response after role change cannot reveal facts',async()=>{const h=harness();h.window.BOS_RUNTIME=null;h.emit('bos:session-ended');h.reply(0,200,fixture().facts);await h.flush();assert.doesNotMatch(h.text(),/SO-UA|9007199254740993/);h.unmount();});
 await run('mutation invalidates data without retry or retaining old selection',async()=>{const h=harness();await h.pair();await h.flush();h.emit('bos:data-changed');await h.flush();assert.equal(h.requests.length,3);assert.doesNotMatch(h.text(),/SO-UA|SPEC-UA/);assert.match(h.text(),/Дані змінилися/);h.unmount();});
 await run('source open uses fresh pair and double-click sends one pair',async()=>{const h=harness();await h.pair();await h.flush();const b=h.button('SO-UA');b.props.onClick();b.props.onClick();assert.equal(h.requests.length,4);await h.pair(3);await h.flush();const inspector=h.all().find(n=>n.type===h.context.BoSInspector);assert.equal(inspector.props.selection.id,3);h.unmount();});
 await run('revoked source disappears before inspector opens',async()=>{const h=harness();await h.pair();await h.flush();h.button('SO-UA').props.onClick();const f=fixture();f.facts.points[0].order_ids=[];f.snapshot.orders=[];await h.pair(3,f);await h.flush();assert(!h.all().some(n=>n.type===h.context.BoSInspector));assert.doesNotMatch(h.text(),/SO-UA/);h.unmount();});
 await run('new order uses selected branch through existing action dialog',async()=>{const h=harness();await h.pair();await h.flush();h.button('Нове замовлення').props.onClick();await h.pair(3);await h.flush();const dialog=h.all().find(n=>n.type===h.context.BoSActionDialog);assert.equal(dialog.props.action,'order');assert.equal(dialog.props.preset.branch_id,1);h.unmount();});
 await run('network rejection is not a successful empty state',async()=>{const h=harness();h.requests[0].reject(Error('network'));await h.flush();assert.match(h.text(),/Не вдалося перевірити/);assert.doesNotMatch(h.text(),/Доступних робочих точок ще немає/);h.unmount();});
 await run('header access mismatch never accepts matching body',async()=>{const h=harness();h.reply(0,200,fixture().facts,'r2');await h.flush();assert.match(h.text(),/Доступ змінився/);assert.doesNotMatch(h.text(),/SO-UA/);h.unmount();});
 await run('point change clears inspector and retains accessible unassigned group',async()=>{const h=harness(),f=fixture();f.facts.points.push({branch:null,location_ids:[],order_ids:[],lot_ids:[],movement_ids:[],invoice_ids:[],document_ids:[],stock:[],money:[],completeness:'complete',movement_scope:'latest_300_visible_global'});await h.pair(0,f);await h.flush();h.button('SO-UA').props.onClick();await h.pair(3,f);await h.flush();h.all().find(n=>n.type===h.context.Select).props.onChange({target:{value:'unassigned'}});await h.flush();assert(!h.all().some(n=>n.type===h.context.BoSInspector));assert.doesNotMatch(h.text(),/SO-UA/);assert.match(h.text(),/Без прив’язки/);h.unmount();});
 await run('confirmed receipt remains visible if subsequent refresh fails',async()=>{const h=harness();await h.pair();await h.flush();h.button('Нове замовлення').props.onClick();await h.pair(3);await h.flush();const dialog=h.all().find(n=>n.type===h.context.BoSActionDialog);h.emit('bos:data-changed');const done=dialog.props.onDone({impact:[]});await h.pair(6,fixture(),409);await done;await h.flush();assert.match(h.text(),/Операцію збережено/);assert.match(h.text(),/Записи змінилися/);h.unmount();});
 await run('unmount aborts pending read without rendering later facts',async()=>{const h=harness();h.unmount();h.reply(0,200,fixture().facts);await h.flush();assert.doesNotMatch(h.text(),/SO-UA/);});
 await run('new form defaults UAH; existing preset EUR survives; optional branch numeric',async()=>{for(const preset of [{},{currency:'EUR',branch_id:1}]){const h=harness('ceo',{preset});const currency=h.all().find(n=>n.type===h.context.Select&&n.children.flat().some(x=>x?.type==='option'&&h.text(x)==='UAH'));assert.equal(currency.props.value,preset.currency||'UAH');const form=h.all().find(n=>n.type==='form');await form.props.onSubmit({preventDefault(){}});const payload=h.requests[0].payload;assert.equal(payload.currency,preset.currency||'UAH');assert.equal(payload.branch_id,preset.branch_id);h.unmount();}});
 const telemetry=html.slice(html.indexOf('const API_BASE ='),html.indexOf('// Відображення повторює серверні права'));
 await run('HTTP observations keep only actual bounded session samples and clear on revocation',async()=>{let time=0;const calls=[],events=new Map();const window={BOS_RUNTIME:{user_id:1,role:'ceo',mode:'demo',access_revision:'r1'},Event:class Event{constructor(type){this.type=type;}},fetch:()=>new Promise(resolve=>calls.push(resolve)),addEventListener:(n,f)=>events.set(n,f),dispatchEvent:e=>events.get(e.type)?.()};const context={window,location:{href:'https://bos.test/',origin:'https://bos.test'},URL,Headers,document:{cookie:''},performance:{now:()=>time},Number,Math};vm.createContext(context);vm.runInContext(telemetry+'\nthis.readSamples=()=>bosHttp.samples;',context);const response={ok:true,status:200,headers:{get:()=>null}};for(let n=0;n<23;n++){const p=window.fetch('/api/erp/orders/123/trace/?secret=token');time+=7;calls.shift()(response);await p;}assert.equal(context.readSamples().length,20);const sample=context.readSamples()[0];assert.equal(sample.ms,7);assert.deepEqual(Object.keys(sample).sort(),['family','ms','ok']);assert(!JSON.stringify(context.readSamples()).includes('123'));const pending=window.fetch('/api/erp/snapshot/');window.dispatchEvent(new window.Event('bos:session-ended'));calls.shift()(response);await pending;assert.equal(context.readSamples().length,0);});
 const fixturesFlag=process.argv.indexOf('--api-fixtures');
 if(fixturesFlag!==-1){const file=process.argv[fixturesFlag+1];assert(file,'--api-fixtures needs a file');const raw=JSON.parse(fs.readFileSync(file,'utf8')),fixtures=Array.isArray(raw)?raw:raw.fixtures;assert(Array.isArray(fixtures)&&fixtures.length,'Expected nonempty fixtures array');for(const f of fixtures)await run('captured Django HTTP contract: '+f.role,async()=>{assert(['ceo','manager','observer'].includes(f.role));assert.equal(typeof f.access_revision,'string');assert(f.capabilities&&typeof f.capabilities.finance==='boolean');const context={bosCan:key=>f.capabilities[key]===true};vm.createContext(context);vm.runInContext(compiled+'\nthis.verify=workpointVerify;',context);context.verify(f.workpoints,f.snapshot,f.access_revision);if(f.role!=='ceo')assert(f.workpoints.points.every(p=>p.money===null&&p.completeness==='restricted'));});}
 console.log(JSON.stringify({scope:'Actual JSX with controlled hooks/network; no browser/DOM/E2E',results},null,2));
})().catch(error=>{console.error(error);process.exitCode=1;});
