function ControlledTask({taskId=null,mode='create',preset={},requestCode,defaultEmployee,onDone,onClose,importPayload,recovery=null}){
 const imported=importPayload||{},seed={...preset,...imported},targetId=taskId||imported.task_id||recovery?.task_id||null;
 const initialMode=c01Own(imported,'archived')?(imported.archived?'archive':'restore'):mode==='view'?'view':['archive','restore'].includes(mode)?mode:targetId?'edit':'create';
 const sourceRequest=imported.request_code||requestCode;
 const ref=useRef(null),heading=useRef(null),alive=useRef(true),lock=useRef(false),controllers=useRef(new Set()),draftReady=useRef(false);
 const [task,setTask]=useState(null),[employees,setEmployees]=useState([]),[orders,setOrders]=useState([]),[asOf,setAsOf]=useState(''),[ready,setReady]=useState(false),[values,setValues]=useState(c01Form(null,seed)),[changed,setChanged]=useState(C01_FIELDS.filter(k=>c01Own(seed,k)));
 const [proposal,setProposal]=useState(null),[pending,setPending]=useState(recovery),[outcome,setOutcome]=useState(null),[receipt,setReceipt]=useState(null),[terminal,setTerminal]=useState(null),[noChange,setNoChange]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[readError,setReadError]=useState('');
 const [history,setHistory]=useState([]),[historyCursor,setHistoryCursor]=useState(null),[historyLoaded,setHistoryLoaded]=useState(false),[orderOpen,setOrderOpen]=useState(false),[scopeDenied,setScopeDenied]=useState(false);
 const writable=bosCan('write'),archiveMode=['archive','restore'].includes(initialMode),canEdit=writable&&initialMode!=='view'&&(!task?.archived||initialMode==='restore');
 useEffect(()=>{alive.current=true;ref.current.showModal();load();return()=>{alive.current=false;controllers.current.forEach(c=>c.abort());};},[]);
 async function request(url,options={}){const controller=new AbortController();controllers.current.add(controller);const timer=setTimeout(()=>controller.abort(),30000);try{const response=await fetch(url,{...options,signal:controller.signal});let body;try{body=await response.json();}catch{throw Error('Сервер не повернув читабельну відповідь.');}return {ok:response.ok,status:response.status,body};}finally{clearTimeout(timer);controllers.current.delete(controller);}}
 function close(){if(busy==='confirm')return;alive.current=false;controllers.current.forEach(c=>c.abort());ref.current.close();}
 function denyScope(){setTask(null);setHistory([]);setHistoryCursor(null);setHistoryLoaded(false);setOrders([]);setOrderOpen(false);setReady(false);setScopeDenied(true);}
 async function load(){if(lock.current)return;lock.current=true;setBusy('load');setReadError('');try{
  const recordId=receipt?.task_id||targetId;const responses=await Promise.all([recordId?request('/api/tasks/'+recordId+'/'):Promise.resolve(null),request('/api/employees/'),request('/api/erp/snapshot/')]);if(!alive.current)return;
  for(const r of responses.filter(Boolean))if(!r.ok){if([403,404].includes(r.status))denyScope();throw Error(r.body.error||'Не вдалося прочитати доручення або доступні джерела.');}
  const row=responses[0]?.body??null,directory=responses[1].body,snapshot=responses[2].body;
  if((recordId&&row?.id!==recordId)||!Array.isArray(directory)||!Array.isArray(snapshot.orders)||!c01Date(snapshot.as_of))throw Error('Сервер повернув неповні дані доручення.');
  setTask(row);setEmployees(directory);setOrders(snapshot.orders);setAsOf(snapshot.as_of);setReady(true);setScopeDenied(false);
  if(!draftReady.current){const form=c01Form(row,seed,snapshot.as_of,defaultEmployee||'');if(!row&&!c01Own(seed,'category'))form.category=sourceRequest?'Закупівлі':'Загальне';setValues(form);draftReady.current=true;}
 }catch(e){if(alive.current){setReadError(e.name==='AbortError'?'Читання не завершилося. Спробуйте ще раз.':e.message);setReady(false);}}finally{lock.current=false;if(alive.current)setBusy('');}}
 function change(key,value){if(lock.current||pending||receipt)return;setValues(v=>({...v,[key]:value,...(key==='status'&&value==='done'&&task?.status!=='done'?{result:''}:{})}));setChanged(keys=>Array.from(new Set([...keys,key,...(key==='status'&&value==='done'&&task?.status!=='done'?['result']:[])])));setProposal(null);setNoChange(null);setTerminal(null);setError('');}
 async function prepare(event){event?.preventDefault();if(lock.current||pending||receipt||!canEdit||!ready)return;setError('');setNoChange(null);try{const payload=c01BuildPayload({task,values,changed,mode:initialMode,requestCode:sourceRequest,asOf});lock.current=true;setBusy('preview');const r=await request('/api/operations/preview/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!alive.current)return;if(!r.ok){if([403,404].includes(r.status))denyScope();throw Error(r.body.error||'Не вдалося перевірити доручення.');}if(r.body.state==='no_change'){if(r.body.id!==null)throw Error('Некоректна відповідь перевірки.');setNoChange(r.body);setProposal(null);return;}if(!c01UUID(r.body.id)||r.body.payload?.action!==payload.action||r.body.effect?.entity!=='task'||(task&&r.body.effect.task_id!==task.id))throw Error('Не отримано погодження саме цього доручення.');setProposal(r.body);setTerminal(null);heading.current?.focus();}catch(e){if(alive.current)setError(e.name==='AbortError'?'Перевірка не завершилася. Чернетка збережена у формі.':e.message);}finally{lock.current=false;if(alive.current)setBusy('');}}
 function accept(result,entry){if(result?.state!=='succeeded'||!c01Id(result.task_id)||!c01UUID(result.audit_id)||(entry.task_id!==null&&result.task_id!==entry.task_id)||!Array.isArray(result.impact))throw Error('Немає підтвердженого результату саме цього погодження.');setReceipt(result);setTask(null);setScopeDenied(false);setPending(null);setProposal(null);setOutcome(null);setError('');setHistory([]);setHistoryLoaded(false);setHistoryCursor(null);try{c01PendingRemove(entry.proposal_id);}catch{setReadError('Зміни збережено. Не вдалося прибрати локальний ідентифікатор; повторна перевірка безпечна.');}try{Promise.resolve(onDone?.(result)).catch(()=>{if(alive.current)setReadError('Зміни збережено, але оновлення списку не завершилося.');});}catch{setReadError('Зміни збережено, але оновлення списку не завершилося.');}heading.current?.focus();}
 async function commit(){if(lock.current||receipt||!writable)return;const entry=pending||(proposal?{proposal_id:proposal.id,action:proposal.payload.action,task_id:proposal.payload.task_id??null,user_id:window.BOS_RUNTIME?.user_id}:null);if(!entry)return;if(pending&&outcome?.same_session!==true){setError('Спочатку перевірте результат і доступність початкової сесії.');return;}setError('');try{c01PendingSave(entry);}catch(e){setError('Погодження не надіслано: '+e.message);return;}setPending(entry);setOutcome({same_session:true});lock.current=true;setBusy('confirm');try{const r=await request('/api/operations/confirm/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({proposal_id:entry.proposal_id,confirmed:true})});if(!alive.current)return;if(!r.ok){if([403,404].includes(r.status))denyScope();if(c01Terminal(r.status,r.body)){try{c01PendingRemove(entry.proposal_id);}catch{setReadError('Сервер підтвердив відмову без змін, але локальний ідентифікатор лишився.');}setTerminal({code:r.body.code,message:r.body.error});setPending(null);setProposal(null);setOutcome(null);return;}setError((r.body.error||'Результат не отримано.')+' Ідентифікатор збережено; перевірте результат або повторіть це погодження.');return;}accept(r.body,entry);}catch(e){if(alive.current)setError('Результат запиту невідомий. Ідентифікатор збережено. Перевірте результат або повторіть те саме погодження.');}finally{lock.current=false;if(alive.current)setBusy('');}}
 async function recover(){if(lock.current||!pending)return;const entry=pending;lock.current=true;setBusy('outcome');setError('');try{const r=await request('/api/operations/task-proposals/'+encodeURIComponent(entry.proposal_id)+'/');if(!alive.current)return;if(!r.ok){if([403,404].includes(r.status)){denyScope();setOutcome(null);}throw Error(r.body.error||'Результат не знайдений або недоступний. Ідентифікатор збережено.');}if(r.body.proposal_id!==entry.proposal_id||r.body.action!==entry.action||typeof r.body.same_session!=='boolean')throw Error('Отримано відповідь для іншого погодження.');setOutcome(r.body);if(r.body.state==='succeeded')accept(r.body.receipt,entry);else setError(r.body.same_session?'Підтвердженого результату поки немає. Остаточна перевірка — повтор того самого погодження.':'Початкова сесія недоступна. Можна перевіряти збережений результат, але виконання цього погодження з нової сесії не дозволене.');}catch(e){if(alive.current)setError(e.name==='AbortError'?'Читання не завершилося. Ідентифікатор збережено.':e.message);}finally{lock.current=false;if(alive.current)setBusy('');}}
 async function refreshRecord(){const id=receipt?.task_id||task?.id||targetId;if(lock.current||!id)return;lock.current=true;setBusy('record');setReadError('');try{const [r,related]=await Promise.all([request('/api/tasks/'+id+'/'),request('/api/erp/snapshot/')]);if(!alive.current)return;for(const response of [r,related])if(!response.ok){if([403,404].includes(response.status))denyScope();throw Error(response.body.error||'Поточне доручення або джерела недоступні.');}if(r.body.id!==id||!Array.isArray(related.body.orders))throw Error('Не отримано актуального доручення з джерелами.');setTask(r.body);setOrders(related.body.orders);setOrderOpen(false);setScopeDenied(false);setReady(true);}catch(e){if(alive.current)setReadError(e.name==='AbortError'?'Оновлення не завершилося. Квитанція збережена.':e.message);}finally{lock.current=false;if(alive.current)setBusy('');}}
 async function loadHistory(more=false){const id=receipt?.task_id||task?.id||targetId;if(lock.current||!id)return;lock.current=true;setBusy('history');setReadError('');try{const r=await request('/api/tasks/'+id+'/history/?limit=20'+(more&&historyCursor?'&cursor='+encodeURIComponent(historyCursor):''));if(!alive.current)return;if(!r.ok){if([403,404].includes(r.status))denyScope();throw Error(r.body.error||'Історія доручення недоступна.');}if(r.body.task_id!==id||!Array.isArray(r.body.items))throw Error('Некоректна відповідь історії доручення.');setScopeDenied(false);setHistory(items=>more?[...items,...r.body.items]:r.body.items);setHistoryCursor(r.body.next_cursor);setHistoryLoaded(true);}catch(e){if(alive.current){setHistory([]);setHistoryCursor(null);setHistoryLoaded(false);setReadError(e.name==='AbortError'?'Читання історії не завершилося.':e.message);}}finally{lock.current=false;if(alive.current)setBusy('');}}
 const order=orders.find(o=>o.id===task?.order_id),selectedEmployee=employees.find(e=>e.id===Number(values.assignee_id)),activeEmployees=employees.filter(e=>!e.archived_at),currentResultLabel=task?.status==='done'?'Зафіксований результат':'Попередній результат';
 const currentCard=task&&<section className="c01-current"><h3>Доручення №{task.id} · останній прочитаний стан</h3><p className="c01-text"><strong>{task.title}</strong></p><div className="bos-facts"><div><span>Відповідальний</span><strong>{c01Assignee(task)||'Історично не призначено'}{task.assignee_id?' · ID '+task.assignee_id:''}</strong></div><div><span>Строк</span><strong>{task.deadline||'Історично не задано'}{task.is_overdue?' · прострочено':''}</strong></div><div><span>Стан</span><strong>{C01_STATUS[task.status]||task.status}{task.archived?' · в архіві':''}</strong></div></div>{task.archived_at&&<p className="op-muted">В архіві з {new Date(task.archived_at).toLocaleString('uk-UA')}. Статус і результат збережені.</p>}{task.order_id&&<><Button disabled={!!busy} onClick={()=>setOrderOpen(v=>!v)}>Замовлення {task.order_code||'№'+task.order_id} · деталі</Button>{orderOpen&&(order?<div className="bos-next"><div><strong>{order.code} · ID {order.id}</strong><p>Строк: {order.due_date||'—'} · {ERP_LABELS[order.status]||order.status}</p><p className="op-muted">Джерело: поточний доступний запис замовлення продажу. Виконання доручення не проводить відвантаження або оплату.</p></div></div>:<p className="erp-error">Замовлення зараз недоступне. Оновіть доступні джерела.</p>)}</>}<h4>{currentResultLabel}</h4><p className="c01-text">{task.result===null?'Історичний результат не був записаний.':task.result||'Результат ще не записаний.'}</p>{task.status!=='done'&&task.result_recorded&&<p className="op-muted">Це текст попереднього виконання; нове завершення потребує явно введеного результату.</p>}</section>;
 return <dialog ref={ref} className="bos-dialog c01-dialog" aria-labelledby="c01-task-title" onClose={()=>{alive.current=false;controllers.current.forEach(c=>c.abort());onClose();}} onCancel={e=>{if(busy==='confirm')e.preventDefault();else{alive.current=false;controllers.current.forEach(c=>c.abort());}}}>
  <div className="erp-row"><h2 id="c01-task-title" ref={heading} tabIndex={-1}>{receipt?'Результат погодження':pending?'Перевірка погодження':initialMode==='view'?'Доручення та історія':initialMode==='archive'?'Архівувати доручення':initialMode==='restore'?'Відновити доручення':targetId?'Змінити доручення':'Нове доручення'}</h2><Button disabled={busy==='confirm'} onClick={close}>Закрити</Button></div>
  <p className="op-muted">Відповідальний, строк і результат мають історію. Доручення не створює складських рухів або платежів.</p>
  {busy==='load'&&<p role="status">Читаємо поточні дані…</p>}{readError&&<p className="erp-error" role="alert">{readError}</p>}{!ready&&!busy&&<Button onClick={load}>Повторити читання джерел</Button>}
  {receipt?<section><p role="status" className="erp-notice">Зміни збережено. Доручення №{receipt.task_id} · подія {receipt.audit_id}.</p><h3>Незмінний результат цього погодження</h3>{scopeDenied?<p className="erp-error">Результат виконання збережено, але текст змін зараз недоступний. Перевірте поточний доступ до доручення.</p>:<C01Impact changes={receipt.impact}/>}<p className="op-muted">Пізніші зміни не додаються до цієї квитанції.</p><Button disabled={!!busy} onClick={refreshRecord}>Прочитати поточне доручення</Button></section>:pending?<section className="erp-confirm"><h3>Ідентифікатор погодження збережено</h3><p className="c01-text">{pending.proposal_id}</p><p className="op-muted">Стани «очікує», «строк минув» або відсутня відповідь ще не доводять, що паралельне виконання не відбулося. Новий намір автоматично не створюється.</p>{outcome&&<p>Початкова сесія: {outcome.same_session?'доступна':'недоступна'}. {outcome.expires_at?'Строк погодження: '+new Date(outcome.expires_at).toLocaleString('uk-UA'):''}</p>}<div className="actions"><Button disabled={!!busy} onClick={recover}>Перевірити результат</Button>{outcome?.same_session===true&&writable&&<Button disabled={!!busy} onClick={commit}>Повторити те саме погодження</Button>}</div></section>:proposal&&!scopeDenied?<section><h3>Перевірте зміни перед погодженням</h3><C01Impact changes={proposal.impact}/>{proposal.payload.reason&&<p className="c01-text">Причина: {proposal.payload.reason}</p>}<p className="op-muted">{proposal.effect.task_id?'Доручення №'+proposal.effect.task_id:'Нове доручення ще не збережено.'} Погодження чинне до {new Date(proposal.expires_at).toLocaleString('uk-UA')}.</p><div className="actions"><Button disabled={!!busy} onClick={()=>setProposal(null)}>До форми</Button><Button variant="primary" disabled={!!busy||!writable} onClick={commit}>Погодити й виконати</Button></div></section>:ready&&canEdit?<form id="c01-task-form" onSubmit={prepare}>
   {terminal&&<p role="status" className="erp-notice">{terminal.message||'Погодження втратило чинність.'} Сервер підтвердив відмову без застосування. Перевірте чернетку й явно створіть новий попередній перегляд.</p>}{noChange&&<p role="status">{noChange.effect?.note||'Зміни не потрібні.'} Нове погодження та подію не створено.</p>}
   <fieldset disabled={!!busy} className="b03-fieldset"><div className="erp-form">
    {!archiveMode&&<><label>Зміст доручення<Input required minLength={3} maxLength={200} value={values.title} onChange={e=>change('title',e.target.value)}/></label><label>Відповідальний<Select value={values.assignee_id} required={!targetId} onChange={e=>change('assignee_id',e.target.value)}><option value="">{targetId?'Історичне призначення — без зміни':'Оберіть співробітника'}</option>{selectedEmployee?.archived_at&&<option value={selectedEmployee.id} disabled>{c01EmployeeLabel(selectedEmployee)} · архівне призначення</option>}{targetId&&values.assignee_id&&!selectedEmployee&&<option value={values.assignee_id} disabled>{task?.assignee_name||'Історичний виконавець'} · ID {values.assignee_id}</option>}{activeEmployees.map(e=><option key={e.id} value={e.id}>{c01EmployeeLabel(e)}</option>)}</Select></label><label>Строк виконання<Input type="date" required={!targetId||changed.includes('deadline')} min={!targetId?asOf:undefined} value={values.deadline} onChange={e=>change('deadline',e.target.value)}/></label><label>Пріоритет<Select value={values.priority} onChange={e=>change('priority',e.target.value)}><option value="high">Високий</option><option value="medium">Середній</option><option value="low">Низький</option><option value="">Без пріоритету</option></Select></label><label>Категорія<Input maxLength={50} value={values.category} onChange={e=>change('category',e.target.value)}/></label><label>Замовлення продажу<Select value={values.order_id} onChange={e=>change('order_id',e.target.value)}><option value="">Без прив’язки</option>{orders.map(o=><option key={o.id} value={o.id}>{o.code} · ID {o.id}</option>)}</Select></label>{targetId&&<><label>Робочий статус<Select value={values.status} onChange={e=>change('status',e.target.value)}>{!['active','process','done'].includes(values.status)&&<option value={values.status} disabled>{C01_STATUS[values.status]||values.status}</option>}{['active','process','done'].map(s=><option key={s} value={s}>{C01_STATUS[s]}</option>)}</Select></label><label className="c01-wide">{task?.status==='done'?'Уточнення результату':'Результат виконання'}<textarea maxLength={2000} required={values.status==='done'&&task?.status!=='done'} value={values.result} onChange={e=>change('result',e.target.value)} className="c01-textarea"/></label></>}</>}
    {targetId&&<label className="c01-wide">Причина {archiveMode?'архівування / відновлення':'зміни'}<textarea required minLength={3} maxLength={1000} value={values.reason} onChange={e=>change('reason',e.target.value)} className="c01-textarea"/></label>}
   </div>{sourceRequest&&<p>Джерело: заявка {sourceRequest}. Прив’язка буде зафіксована в історії.</p>}{task?.status==='done'&&['active','process'].includes(values.status)&&<p className="op-muted">Повернення до роботи зберігає попередній результат без змін. Новий текст результату погоджується окремо після відкриття доручення.</p>}{archiveMode?<p className="op-muted">{initialMode==='archive'?'Доручення зникне з робочого списку; його статус, результат, джерела й історія збережуться.':'Доручення повернеться з тим самим статусом, строком і результатом. Старий минулий строк знову враховуватиметься як прострочення.'}</p>:targetId&&<p className="op-muted">Змінюються лише явно відредаговані поля. При новому завершенні сервер прибере пріоритет, якщо ви не зазначили його явно; це видно перед погодженням.</p>}<div className="actions"><Button type="submit" variant="primary">{busy==='preview'?'Перевіряємо…':terminal?'Новий попередній перегляд':'Переглянути зміни'}</Button></div></fieldset>
  </form>:ready&&!pending&&!receipt&&!writable&&initialMode!=='view'?<p className="erp-error">Доступ лише для перегляду.</p>:null}
  {error&&<p className="erp-error" role="alert">{error}</p>}{currentCard}
  {(task?.id||receipt?.task_id||targetId)&&<section><div className="erp-row"><h3>Історія доручення</h3><Button disabled={!!busy} onClick={()=>loadHistory(false)}>{historyLoaded?'Оновити історію':'Прочитати історію'}</Button></div>{historyLoaded&&!history.length&&<p>Збережених подій для цього доручення немає.</p>}{history.map(item=><article className="c01-history" key={item.id}><h4>{C01_TRANSITIONS[item.transition]||'Історична подія'} · {new Date(item.created_at).toLocaleString('uk-UA')}</h4><p className="op-muted">{item.actor?.display||'Автор історично не записаний'}{item.actor?.id?' · ID '+item.actor.id:''}{item.actor?.role?' · '+({ceo:'Керівник',manager:'Менеджер',observer:'Спостерігач'}[item.actor.role]||item.actor.role):''}</p>{item.reason&&<p className="c01-text">{item.reason}</p>}{item.legacy?<p className="op-muted">{item.note||'Структурований diff раніше не збережено.'}</p>:<C01Impact changes={item.changes}/>}</article>)}{historyCursor&&<Button disabled={!!busy} onClick={()=>loadHistory(true)}>Попередні події</Button>}</section>}
 </dialog>;
}
