function Topbar({nav,setNav,tasks,employees,contracts,counterparties,onCreated}){
 const [query,setQuery]=useState(''),[taskDialog,setTaskDialog]=useState(null);const search=useRef(null);
 useEffect(()=>{const key=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search.current?.focus();}if(e.key==='Escape')setQuery('');};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[]);
 const section=bosNavigation().find(n=>n.id===nav.section),title=section?.subs.find(x=>x.id===nav.sub)?.label||section?.label;
 const entries=[...tasks.filter(x=>!x.archived).map(x=>({label:x.title,detail:c01Assignee(x),target:{section:'hr',sub:'tasks'}})),...employees.map(x=>({label:x.name,detail:x.role,target:{section:'hr',sub:'employees'}})),...contracts.map(x=>({label:x.name,detail:x.number,target:{section:'finance',sub:'contracts'}})),...counterparties.map(x=>({label:x.name,detail:'Контрагент',target:{section:'finance',sub:'contractors'}}))];
 const results=query.trim()?entries.filter(x=>bosCanView(x.target.section,x.target.sub)).filter(x=>(x.label+' '+x.detail).toLowerCase().includes(query.trim().toLowerCase())).slice(0,8):[];
 return <><div className="bos-topbar" style={{height:72,padding:'0 24px',borderBottom:'1px solid '+T.border,display:'flex',alignItems:'center',gap:16,flexShrink:0}}>
 <div><div style={{fontSize:20,fontWeight:650}}>{title}</div><div style={{fontSize:12,color:T.textMuted}}>{new Date().toLocaleDateString('uk-UA',{day:'numeric',month:'long',year:'numeric'})}</div></div>
 <div className="bos-search"><label className="bos-sr" htmlFor="bos-search">Пошук доручень, людей і договорів</label><input id="bos-search" ref={search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Доручення, люди, договори…" aria-describedby="bos-search-hint"/><span id="bos-search-hint" className="bos-sr">Ctrl або Command K. Результат відкриває відповідний розділ.</span>{query.trim()&&<div className="bos-results">{results.length?results.map((x,i)=><button key={i} onClick={()=>{setNav(x.target);setQuery('');}}><strong>{x.label}</strong><div style={{fontSize:12,color:T.textMuted}}>{x.detail} · відкрити розділ</div></button>):<div style={{padding:12,color:T.textMuted}}>Нічого не знайдено</div>}</div>}</div>
 {bosCan('write')&&<button className="ui-btn" onClick={()=>setTaskDialog({key:'new-'+Date.now()})} style={{padding:'10px 16px',background:T.primary,color:T.bg,border:0,borderRadius:10,fontWeight:650,marginLeft:'auto',whiteSpace:'nowrap'}}>+ Нове доручення</button>}
 </div><C01PendingLauncher onRecover={entry=>setTaskDialog({key:entry.proposal_id,recovery:entry})}/>{taskDialog&&<ControlledTask key={taskDialog.key} recovery={taskDialog.recovery} onClose={()=>setTaskDialog(null)} onDone={()=>{onCreated?.();}}/>}</>;
}
