function Tasks({tasks,setTasks,loading,error,refetchTasks}){
 const [filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[sortBy,setSortBy]=useState('priority'),[tab,setTab]=useState('active'),[dialog,setDialog]=useState(null),[archive,setArchive]=useState([]),[archiveError,setArchiveError]=useState(''),[archiveLoading,setArchiveLoading]=useState(false);const sequence=useRef(0),archiveAbort=useRef(null),live=useRef(true);
 useEffect(()=>()=>{live.current=false;archiveAbort.current?.abort();},[]);
 useEffect(()=>{if(tab==='archive')loadArchive();return()=>{archiveAbort.current?.abort();sequence.current++;};},[tab]);
 async function loadArchive(){const n=++sequence.current;archiveAbort.current?.abort();const controller=new AbortController();archiveAbort.current=controller;setArchiveLoading(true);setArchiveError('');try{const r=await fetch('/api/tasks/?archived=true',{signal:controller.signal}),body=await r.json();if(!live.current||n!==sequence.current)return;if(!r.ok||!Array.isArray(body))throw Error(body.error||'Архів недоступний.');setArchive(body);}catch(e){if(live.current&&n===sequence.current){setArchive([]);setArchiveError(e.name==='AbortError'?'Читання архіву не завершилося.':e.message);}}finally{if(live.current&&n===sequence.current)setArchiveLoading(false);}}
 function open(task,mode='edit',preset={}){setDialog({taskId:task?.id||null,mode,preset,key:(task?.id||'new')+':'+mode+':'+Date.now()});}
 function refresh(){refetchTasks();if(tab==='archive')loadArchive();}
 const rows=tab==='archive'?archive:tasks.filter(t=>!t.archived),counts={all:rows.length,active:0,process:0,done:0,overdue:0};rows.forEach(t=>{const k=c01TaskSegment(t);if(k in counts)counts[k]++;});
 const term=search.trim().toLowerCase(),priorityOrder={high:0,medium:1,low:2};const filtered=rows.filter(t=>tab==='archive'||filter==='all'||c01TaskSegment(t)===filter).filter(t=>!term||[t.title,c01Assignee(t),t.category,t.order_code].some(s=>(s||'').toLowerCase().includes(term))).sort((a,b)=>sortBy==='priority'?(priorityOrder[a.priority]??3)-(priorityOrder[b.priority]??3):(a.deadline||'9999').localeCompare(b.deadline||'9999'));
 const pageError=tab==='archive'?archiveError:error,pageLoading=tab==='archive'?archiveLoading:loading;
 return <div style={{padding:24}}><div className="erp-row"><div><h2>Доручення команді</h2><p className="op-muted">{tab==='archive'?rows.length+' в архіві':rows.length+' у робочому списку · '+counts.overdue+' прострочено'}</p></div><div className="erp-actions"><Button onClick={refresh}>Оновити</Button>{bosCan('write')&&<Button variant="primary" onClick={()=>open(null,'create')}>+ Нове доручення</Button>}</div></div>
  <div className="erp-row"><SegmentedControl value={tab} onChange={value=>{setTab(value);setFilter('all');}} options={[{key:'active',label:'Робочі доручення'},{key:'archive',label:'Архів'}]}/><div className="erp-actions"><Input aria-label="Пошук доручень" placeholder="Назва, відповідальний, замовлення…" value={search} onChange={e=>setSearch(e.target.value)}/><Select aria-label="Сортування доручень" value={sortBy} onChange={e=>setSortBy(e.target.value)}><option value="priority">За пріоритетом</option><option value="deadline">За терміном</option></Select></div></div>
  {tab==='active'&&<SegmentedControl value={filter} onChange={setFilter} options={[['all','Усі'],['active','Відкриті'],['process','У роботі'],['done','Виконані'],['overdue','Прострочені']].map(([key,label])=>({key,label:label+' · '+counts[key]}))}/>}
  {pageError&&<p className="erp-error" role="alert">{pageError} <Button onClick={refresh}>Спробувати знову</Button></p>}{pageLoading&&<p role="status">Завантажуємо доручення…</p>}
  {tab==='archive'&&<p className="op-muted">Архівні доручення зберігають джерела, статус, результат та історію. Відновлення окремо погоджується.</p>}
  <div className="op-table c01-task-table"><table><thead><tr>{['Доручення','Відповідальний','Термін','Пріоритет','Статус','Дії'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(t=><tr key={t.id}><td><BoSLink onClick={()=>open(t,'view')}>{t.title}</BoSLink><p className="op-muted">№{t.id} · {t.category||'Без категорії'}{t.order_code?' · '+t.order_code:''}</p></td><td>{c01Assignee(t)||'Історично не призначено'}{t.assignee_id&&<p className="op-muted">ID {t.assignee_id}</p>}</td><td>{t.deadline||'Без терміну'}{t.is_overdue&&<p className="erp-error">Прострочено</p>}</td><td>{bosCan('write')&&!t.archived?<PillSelect value={t.priority||''} color={priorityMeta(t.priority).color} onChange={e=>open(t,'edit',{priority:e.target.value||null})} options={[{value:'high',label:'Високий'},{value:'medium',label:'Середній'},{value:'low',label:'Низький'},{value:'',label:'Без пріоритету'}]}/>:({high:'Високий',medium:'Середній',low:'Низький'}[t.priority]||'Без пріоритету')}</td><td>{bosCan('write')&&!t.archived?<PillSelect value={t.status} color={t.is_overdue?T.red:t.status==='done'?T.primary:T.text} onChange={e=>open(t,'edit',{status:e.target.value})} options={[...(!['active','process','done'].includes(t.status)?[{value:t.status,label:C01_STATUS[t.status]||t.status}]:[]),...['active','process','done'].map(s=>({value:s,label:C01_STATUS[s]}))]}/>:C01_STATUS[t.status]||t.status}</td><td><div className="erp-actions"><Button onClick={()=>open(t,'view')}>Історія</Button>{bosCan('write')&&(t.archived?<Button onClick={()=>open(t,'restore')}>Відновити</Button>:<><Button onClick={()=>open(t)}>Редагувати</Button><Button onClick={()=>open(t,'archive')}>Архівувати</Button></>)}</div></td></tr>)}</tbody></table>{!filtered.length&&!pageLoading&&<p className="op-muted">{search?'Нічого не знайдено за цим пошуком.':tab==='archive'?'Архівних доручень немає.':'Доручень у цьому списку немає.'}</p>}</div>
  {dialog&&<ControlledTask key={dialog.key} taskId={dialog.taskId} mode={dialog.mode} preset={dialog.preset} onClose={()=>setDialog(null)} onDone={refresh}/>}
 </div>;
}
