const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto'),path=require('path');
const root=__dirname,s=fs.readFileSync(path.join(root,'frontend/boss_app_source.html'),'utf8'),base=fs.readFileSync(path.join(root,'base/boss_app_source.html'),'utf8'),out=process.argv[2]||path.join(root,'UI_PROOF.json');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),helpers=s.match(/\/\/ C01_HELPERS_BEGIN\n([\s\S]*?)\/\/ C01_HELPERS_END/)[1],dialog=s.slice(s.indexOf('function ControlledTask('),s.indexOf('function ProcurementEntry('));
const identities=s.slice(s.indexOf('function bosRole()'),s.indexOf('function bosCanView('));
const proposalId='a0000000-0000-4000-8000-000000000001',auditId='b0000000-0000-4000-8000-000000000001';
function context(){const map=new Map(),state={},calls=[];const c={JSON,Date,Number,TextEncoder,Promise,console,window:{BOS_RUNTIME:{user_id:7,role:'manager',mode:'demo'},Event:function Event(name){this.type=name;},dispatchEvent:()=>{}},sessionStorage:{getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)},lock:{current:false},alive:{current:true},controllers:{current:new Set()},ref:{current:{close:()=>{state.closed=true;}}},heading:{current:{focus:()=>{}}},writable:true,ready:true,canEdit:true,busy:'',task:{id:5,status:'active',assignee_id:3},targetId:5,initialMode:'edit',sourceRequest:undefined,asOf:'2026-09-12',values:{title:'Доручення',reason:'Змінено строк',deadline:'2026-09-13'},changed:['deadline'],proposal:{id:proposalId,payload:{action:'update_task',task_id:5}},pending:null,outcome:null,receipt:null,historyCursor:'signed/cursor',state,calls,map};for(const key of ['Receipt','Task','Pending','Proposal','Outcome','Error','ReadError','History','HistoryLoaded','HistoryCursor','Terminal','NoChange','Busy','Orders','OrderOpen','Ready','ScopeDenied'])c['set'+key]=value=>{state[key]=value;};c.onDone=()=>{};c.request=async(url,options={})=>{calls.push({url,options});throw Error('reply lost');};vm.createContext(c);vm.runInContext(identities+'\n'+helpers,c);for(const name of ['close','denyScope','accept','commit','recover','prepare','refreshRecord','loadHistory']){const line=dialog.split('\n').find(l=>l.trimStart().startsWith((['close','denyScope','accept'].includes(name)?'function ':'async function ')+name+'('));assert.ok(line,name);vm.runInContext(line,c);}return c;}
const checks=[];async function check(name,fn){try{await fn();checks.push({name,passed:true});}catch(e){checks.push({name,passed:false,error:e.message});}}
(async()=>{
await check('result title category text remains literal',()=>{const c=context();assert.equal(c.c01ImpactValue('done','result'),'done');assert.equal(c.c01ImpactValue('active','title'),'active');assert.equal(c.c01ImpactValue('process','category'),'process');assert.equal(c.c01ImpactValue('done','status'),'Виконане');});
await check('root clarified active draft accepts short and spaces',()=>{const c=context();for(const result of ['OK','  '])assert.equal(c.c01TaskPayload({action:'update_task',task_id:5,reason:'Чернетка результату',result}).result,result);});
await check('record refresh updates linked order snapshot',async()=>{const c=context();c.receipt={task_id:5};c.request=async url=>url.includes('/tasks/')?{ok:true,status:200,body:{id:5,order_id:9,order_code:'SO-NEW'}}:{ok:true,status:200,body:{orders:[{id:9,code:'SO-NEW',due_date:'2026-09-30'}]}};await c.refreshRecord();assert.equal(c.state.Orders?.[0]?.code,'SO-NEW');});
for(const method of ['refreshRecord','loadHistory'])for(const status of [403,404])await check(method+' '+status+' clears source panels but retains receipt success',async()=>{const c=context();c.receipt={task_id:5,audit_id:auditId,state:'succeeded'};c.history=[{after:{result:'PRIVATE-OLD'}}];c.orders=[{id:9,code:'PRIVATE-ORDER'}];c.request=async()=>({ok:false,status,body:{error:'Source denied'}});await c[method]();assert.equal(c.state.Task,null);assert.equal(c.state.History?.length,0);assert.equal(c.state.Orders?.length,0);assert.equal(c.state.OrderOpen,false);assert.equal(c.state.ScopeDenied,true);assert.equal(c.state.Ready,false);assert.equal(c.state.Receipt,undefined);});
await check('transient scope read does not erase draft',async()=>{const c=context();const values=c.values;c.request=async()=>({ok:false,status:500,body:{error:'temporary'}});await c.loadHistory();assert.equal(c.values,values);assert.notEqual(c.state.ScopeDenied,true);assert.notEqual(c.state.Ready,false);});
const report={scope:'Known C01 review findings only; actual source helper/read closures, controlled replies; no browser/API/DB',source_sha256:hash(s),checks,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length};fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));process.exitCode=report.failed?1:0;})();
