const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto'),path=require('path');
const root=__dirname,s=fs.readFileSync(path.join(root,'frontend/boss_app_source.html'),'utf8'),base=fs.readFileSync(path.join(root,'base/boss_app_source.html'),'utf8'),out=process.argv[2]||path.join(root,'UI_PROOF.json');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),helpers=s.match(/\/\/ C01_HELPERS_BEGIN\n([\s\S]*?)\/\/ C01_HELPERS_END/)[1],dialog=s.slice(s.indexOf('function ControlledTask('),s.indexOf('function ProcurementEntry('));
const identities=s.slice(s.indexOf('function bosRole()'),s.indexOf('function bosCanView('));
const proposalId='a0000000-0000-4000-8000-000000000001',auditId='b0000000-0000-4000-8000-000000000001';
function context(){const map=new Map(),state={},calls=[];const c={JSON,Date,Number,TextEncoder,Promise,console,window:{BOS_RUNTIME:{user_id:7,role:'manager',mode:'demo'},Event:function Event(name){this.type=name;},dispatchEvent:()=>{}},sessionStorage:{getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)},lock:{current:false},alive:{current:true},controllers:{current:new Set()},ref:{current:{close:()=>{state.closed=true;}}},heading:{current:{focus:()=>{}}},writable:true,ready:true,canEdit:true,busy:'',task:{id:5,status:'active',assignee_id:3},targetId:5,initialMode:'edit',sourceRequest:undefined,asOf:'2026-09-12',values:{title:'Доручення',reason:'Змінено строк',deadline:'2026-09-13'},changed:['deadline'],proposal:{id:proposalId,payload:{action:'update_task',task_id:5}},pending:null,outcome:null,receipt:null,historyCursor:'signed/cursor',state,calls,map};for(const key of ['Receipt','Task','Pending','Proposal','Outcome','Error','ReadError','History','HistoryLoaded','HistoryCursor','Terminal','NoChange','Busy','Orders','OrderOpen','Ready','ScopeDenied'])c['set'+key]=value=>{state[key]=value;};c.onDone=()=>{};c.request=async(url,options={})=>{calls.push({url,options});throw Error('reply lost');};vm.createContext(c);vm.runInContext(identities+'\n'+helpers,c);for(const name of ['close','denyScope','accept','commit','recover','prepare','refreshRecord','loadHistory']){const line=dialog.split('\n').find(l=>l.trimStart().startsWith((['close','denyScope','accept'].includes(name)?'function ':'async function ')+name+'('));assert.ok(line,name);vm.runInContext(line,c);}return c;}
const checks=[];async function check(name,fn){try{await fn();checks.push({name,passed:true});}catch(e){checks.push({name,passed:false,error:e.message});}}
function stored(c){return JSON.parse([...c.map.values()][0]||'[]');}
function success(){return {state:'succeeded',task_id:5,audit_id:auditId,impact:[{kind:'tasks',id:5,field:'deadline',label:'Строк',before:'2026-09-12',after:'2026-09-13'}]};}
(async()=>{
 await check('unknown confirm retains exact proposal before send',async()=>{const c=context();c.request=async(url,options)=>{assert.equal(stored(c)[0].proposal_id,proposalId);c.calls.push({url,options});throw Error('lost after commit');};await c.commit();assert.equal(stored(c)[0].proposal_id,proposalId);assert.equal(c.state.Pending.proposal_id,proposalId);assert.equal(c.state.Proposal,undefined);assert.equal(JSON.parse(c.calls[0].options.body).proposal_id,proposalId);assert.equal(c.state.Receipt,undefined);});
 await check('storage refusal prevents confirm request',async()=>{const c=context();c.sessionStorage.setItem=()=>{throw Error('quota');};await c.commit();assert.equal(c.calls.length,0);assert.match(c.state.Error,/не надіслано/);});
 await check('generic 409 preserves pending intent',async()=>{const c=context();c.request=async()=>({ok:false,status:409,body:{code:'write_conflict',error:'busy'}});await c.commit();assert.equal(stored(c)[0].proposal_id,proposalId);assert.notEqual(c.state.Pending,null);assert.equal(c.state.Terminal,undefined);});
 for(const code of ['proposal_stale','proposal_expired'])await check('locked '+code+' allows explicit new preview',async()=>{const c=context();c.request=async()=>({ok:false,status:409,body:{code,error:'outdated'}});await c.commit();assert.equal(stored(c).length,0);assert.equal(c.state.Pending,null);assert.equal(c.state.Proposal,null);assert.equal(c.state.Terminal.code,code);assert.equal(c.state.Receipt,undefined);});
 await check('successful receipt survives parent refresh failure',async()=>{const c=context();c.request=async()=>({ok:true,status:200,body:success()});c.onDone=()=>{throw Error('refresh failed');};await c.commit();assert.equal(c.state.Receipt.audit_id,auditId);assert.equal(c.state.Task,null);assert.equal(stored(c).length,0);assert.equal(c.state.Error,'');assert.match(c.state.ReadError,/збережено/);});
 await check('double confirm cannot send concurrently',async()=>{const c=context();let resolve,count=0;c.request=()=>{count++;return new Promise(r=>resolve=r);};const first=c.commit();await c.commit();assert.equal(count,1);resolve({ok:true,status:200,body:success()});await first;});
 await check('same ID retry after lost confirm',async()=>{const c=context();await c.commit();c.pending=c.state.Pending;c.outcome=c.state.Outcome;let sent;c.request=async(u,o)=>{sent=JSON.parse(o.body);return {ok:true,status:200,body:success()};};await c.commit();assert.equal(sent.proposal_id,proposalId);assert.equal(c.state.Receipt.task_id,5);assert.equal(stored(c).length,0);});
 await check('expired GET is not definitive failure',async()=>{const c=context();await c.commit();c.pending=c.state.Pending;c.request=async()=>({ok:true,status:200,body:{proposal_id:proposalId,action:'update_task',state:'expired',receipt:null,same_session:true,expires_at:'2026-09-11T00:00:00Z'}});await c.recover();assert.equal(stored(c)[0].proposal_id,proposalId);assert.equal(c.state.Terminal,undefined);assert.equal(c.state.Receipt,undefined);});
 await check('new session cannot replay old proposal',async()=>{const c=context();c.pending={proposal_id:proposalId,action:'update_task',task_id:5,user_id:7};c.outcome={same_session:false};await c.commit();assert.equal(c.calls.length,0);});
 await check('lookup receipt uses exact proposal identity',async()=>{const c=context();c.pending={proposal_id:proposalId,action:'update_task',task_id:5,user_id:7};c.c01PendingSave(c.pending);c.request=async()=>({ok:true,status:200,body:{proposal_id:proposalId,action:'update_task',state:'succeeded',receipt:success(),same_session:false}});await c.recover();assert.equal(c.state.Receipt.audit_id,auditId);assert.equal(stored(c).length,0);});
 await check('Escape cancels read and discards late preview response',async()=>{const c=context();c.proposal=null;let resolve,aborted=false;c.controllers.current.add({abort:()=>{aborted=true;}});c.request=()=>new Promise(r=>resolve=r);const wait=c.prepare({preventDefault(){}});c.close();assert.equal(c.alive.current,false);assert.equal(aborted,true);resolve({ok:true,status:200,body:{id:proposalId,payload:{action:'update_task'},effect:{entity:'task',task_id:5}}});await wait;assert.equal(c.state.Proposal,undefined);});
 await check('archive payload excludes status/result changes',()=>{const c=context(),p=c.c01BuildPayload({task:{id:5,status:'done',result:'Старий результат'},values:{reason:'Прибрано з робочого списку',status:'active',result:''},changed:['status','result'],mode:'archive'});assert.deepEqual(JSON.parse(JSON.stringify(p)),{action:'update_task',task_id:5,reason:'Прибрано з робочого списку',archived:true});});
 await check('legacy metadata edit does not backfill null FK/result/date',()=>{const c=context(),p=c.c01BuildPayload({task:{id:5,assignee_id:null,result:null,deadline:null,status:'done'},values:{title:'Уточнена назва',reason:'Уточнено назву',assignee_id:'',result:'',deadline:''},changed:['title'],mode:'edit'});assert.deepEqual(Object.keys(p).sort(),['action','reason','task_id','title']);});
 await check('new completion requires explicit result and FK',()=>{const c=context();assert.throws(()=>c.c01BuildPayload({task:{id:5,status:'active',assignee_id:3},values:{reason:'Виконано роботу',status:'done',result:'Старий текст'},changed:['status'],mode:'edit'}),/явно/);assert.throws(()=>c.c01BuildPayload({task:{id:5,status:'active',assignee_id:null},values:{reason:'Виконано роботу',status:'done',result:'Новий результат'},changed:['status','result'],mode:'edit'}),/відповідального/);});
 await check('reopen omits previous result and priority',()=>{const c=context(),p=c.c01BuildPayload({task:{id:5,status:'done',assignee_id:3,result:'Попереднє виконання'},values:{reason:'Потрібно доопрацювати',status:'process'},changed:['status'],mode:'edit'});assert.equal(p.status,'process');assert.equal('result' in p,false);assert.equal('priority' in p,false);});
 await check('server-derived task segments preserve legacy status',()=>{const c=context();assert.equal(c.c01TaskSegment({status:'overdue',is_overdue:false,archived:false}),'active');assert.equal(c.c01TaskSegment({status:'process',is_overdue:true,archived:false}),'overdue');assert.equal(c.c01TaskSegment({status:'done',is_overdue:false,archived:true}),'archive');});
 await check('FK impact displays verified identity not object string',()=>{const c=context();assert.equal(c.c01ImpactValue({id:7,name:'Однакове ім’я'}),'Однакове ім’я · ID 7');assert.equal(c.c01ImpactValue({id:8,code:'SO-8'}),'SO-8 · ID 8');});
 await check('JSON rejects duplicate keys and raw assignee',()=>{const c=context();assert.throws(()=>c.c01TaskJSON('{"action":"create_task","title":"Назва","title":"Інша"}'),/повторний/);assert.throws(()=>c.c01TaskPayload({action:'create_task',title:'Доручення',assignee_id:4,deadline:'2026-09-13',assignee:'Ім’я'}),/невідомі/);});
 await check('literal result newlines and nullable priority preserved',()=>{const c=context(),result='  Звіт\nНаступний рядок  ',p=c.c01TaskPayload({action:'update_task',task_id:5,reason:'Зафіксовано результат',result,priority:'none'});assert.equal(p.result,result);assert.equal(p.priority,null);});
 await check('pending queue is IDs-only and not hidden by access revision',()=>{const c=context();c.c01PendingSave({proposal_id:proposalId,action:'update_task',task_id:5,user_id:7,result:'НЕ КЕШУВАТИ'});assert.deepEqual(Object.keys(stored(c)[0]).sort(),['action','proposal_id','task_id','user_id']);c.window.BOS_RUNTIME.access_revision='new';assert.equal(c.c01PendingRead()[0].proposal_id,proposalId);});
 await check('task entrypoints have no raw Task writes',()=>{const tasks=s.slice(s.indexOf('function Tasks('),s.indexOf('function Employees(')),top=s.slice(s.indexOf('function Topbar('),s.indexOf('// AI-панель справа'));assert.ok(tasks.includes('<ControlledTask'));assert.ok(top.includes('<ControlledTask'));assert.ok(!/method:'(?:POST|PUT|PATCH|DELETE)'/.test(tasks+top));assert.ok(s.includes('setPayload(c01TaskJSON(raw))'));assert.ok(!s.includes("status:t.status!=='done'&&t.deadline&&t.deadline<date?'overdue':t.status"));});
 await check('ERP B02 B03 immutable action and dialog sections unchanged',()=>{for(const [start,end] of [['const ERP_ACTIONS=','const IMPORT_ENTITIES='],['const IMPORT_ENTITIES=','// C01_HELPERS_BEGIN'],['// B03_HELPERS_BEGIN','function ERPWorkspace(']]){if(start==='const IMPORT_ENTITIES=')continue;const chunk=(t)=>t.slice(t.indexOf(start),t.indexOf(end,t.indexOf(start)));assert.equal(hash(chunk(s)),hash(chunk(base)),start);}const imports=t=>t.slice(t.indexOf('const IMPORT_ENTITIES='),t.indexOf('// B03_HELPERS_BEGIN'));assert.equal(hash(imports(s)),hash(imports(base)));});
 await check('exact Babel compile matches final app',()=>{const babel=require(path.join(root,'assets/babel.js')),jsx=s.match(/<script type="text\/babel">([\s\S]*?)<\/script>/)[1].replace('{% verbatim %}','').replace('{% endverbatim %}','');assert.equal(babel.transform(jsx,{presets:['react'],filename:'bos-app.jsx'}).code,fs.readFileSync(path.join(root,'assets/app.js'),'utf8'));});
 const report={scope:'Actual extracted source JS helper/command closures, controlled transport and storage; no browser/API/DB acceptance',source_sha256:hash(s),compiled_sha256:hash(fs.readFileSync(path.join(root,'assets/app.js'))),checks,passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length};fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));process.exitCode=report.failed?1:0;
})();
