# Generated by Django 6.0.5 on 2026-09-10 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_employee_branch'),
        ('finance', '0003_transaction_branch'),
        ('tasks', '0004_task_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('receipt', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('revision', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('content', models.BinaryField(default=bytes)),
                ('text', models.TextField(blank=True)),
                ('sections', models.JSONField(default=list)),
                ('status', models.CharField(default='needs_review', max_length=30)),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.contract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('due_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('part', models.CharField(max_length=120)),
                ('revision', models.CharField(max_length=40)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(default='шт.', max_length=20)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('required_by', models.DateField()),
                ('details', models.JSONField(default=dict)),
                ('status', models.CharField(default='review', max_length=30)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('terms', models.JSONField(default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.document')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='operations.procurementrequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.counterparty')),
            ],
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('code', 'revision'), name='bos_document_version'),
        ),
    ]
