# Generated by Django 6.0.5 on 2026-09-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_loginattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'permissions': [('download_document', 'Завантажувати доступні документи'), ('export_workspace', 'Експортувати доступний робочий контекст')]},
        ),
        migrations.AddField(
            model_name='document',
            name='access_level',
            field=models.CharField(choices=[('operational', 'Операційний'), ('management', 'Менеджмент'), ('ceo', 'Лише керівник')], default='ceo', max_length=20),
        ),
    ]
