# Generated by Django 6.0.5 on 2026-09-11 22:12

import operations.private_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_invoice_boundaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_file',
            field=models.FileField(blank=True, max_length=255, null=True, storage=operations.private_storage.PrivateDocumentStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
