# Generated by Django 6.0.5 on 2026-09-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_actionproposal_dependency_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrequest',
            name='currency',
            field=models.CharField(default='UAH', max_length=3),
        ),
    ]
