/* CORE-WORKSPACE-VIEWS: bounded Node component/contract checks, not browser E2E. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'frontend/boss_app_source.html'),'utf8');
const babel=require(path.join(root,'assets/babel.js'));
const fragment=html.slice(html.indexOf('// CORE_MODULE_VIEWS_BEGIN'),html.indexOf('// CORE_MODULE_VIEWS_END'));
const authAction=html.slice(html.indexOf('function bosCanAction('),html.indexOf('function bosCanView('));
const actions=html.slice(html.indexOf('const ERP_ACTIONS='),html.indexOf('\nfunction ERPTable'));
const catalogs=Object.fromEntries(['ceo','manager','observer'].map(role=>[role,JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/module_catalog',role+'.json'),'utf8'))]));
let role='ceo',slots=[],hook=0,effects=[],checks=0;
const React={createElement:(type,props,...children)=>({type,props:props||{},children})};
const noop=()=>{},c={console,React,Intl,Number,BigInt,Math,Map,Set,Promise,AbortController,JSON,URLSearchParams,
 useState(initial){const n=hook++;if(!(n in slots))slots[n]=typeof initial==='function'?initial():initial;return [slots[n],v=>slots[n]=typeof v==='function'?v(slots[n]):v];},
 useRef(initial){const n=hook++;if(!(n in slots))slots[n]={current:initial};return slots[n];},useEffect(fn){effects.push(fn);},
 bosRole:()=>role,bosCan:key=>key==='finance'?role==='ceo':key==='write'||key==='export_workspace'?role!=='observer':true,
 window:{BOS_RUNTIME:{employee_id:1}},
 Button:'Button',Select:'Select',Input:'Input',Card:'Card',ERPTable:'ERPTable',NetworkMap:'NetworkMap',
 ERP_LABELS:{approved:'Дозволено',blocked:'Заблоковано',pending:'Очікує перевірки',ordered:'Замовлено',received:'Отримано',partial:'Частково отримано',done:'Завершено',warehouse:'Склад'},erpDate:value=>value||'—',
 networkQuery(branch,point,currency,table){const q=new URLSearchParams({currency});if(branch)q.set('branch_id',branch);if(point)q.set('location_id',point);if(table)q.set('table',table);return q.toString();},
};
vm.createContext(c);vm.runInContext(babel.transform(authAction+'\n'+actions+'\n'+fragment,{presets:['react']}).code,c);
function nodes(tree){if(tree==null||typeof tree!=='object')return [];return [tree,...(tree.children||[]).flat(Infinity).flatMap(nodes)];}
function text(tree){return typeof tree!=='object'||tree==null?String(tree??''):(tree.children||[]).flat(Infinity).map(text).join('');}
function render(name,props,initial=[]){slots=initial;hook=0;effects=[];return c[name](props);}
function rerender(name,props){hook=0;effects=[];return c[name](props);}
function check(label,fn){fn();checks++;console.log('PASS '+label);}
const points=[{id:1,code:'KYI-WH',name:'Київ склад',branch_id:11,map_lat:50.45,map_lng:30.52},{id:2,code:'LVI-SV',name:'Львів сервіс',branch_id:12,map_lat:49.83,map_lng:24.02}];
const network={schema:'bos.network.v1',as_of:'2026-09-21',currency:'UAH',locations:points,capabilities:{write:true,finance:true,export:true},rows:{points,
 lots:[{id:10,code:'LOT-A',item_name:'Підшипник',quality:'approved',available:'10.000',quantity:'12.000',location_id:1,currency:'UAH',value:'4800.00'},{id:11,code:'LOT-B',quality:'blocked',available:'0.000',quantity:'3.000',location_id:2,currency:'UAH',value:'1440.00',missing_documents:['certificate']}],
 purchases:[{id:20,code:'PO-OPEN',effective_status:'open',open_quantity:'2.000',due_date:'2026-09-20',location_id:1,destination_id:1,price:'480.00',currency:'UAH'},{id:21,code:'PO-CLOSED',effective_status:'closed_cancelled',open_quantity:'0.000',due_date:'2026-09-01',location_id:2,currency:'UAH'}],
 orders:[{id:30,code:'SO-CLOSED',status:'confirmed',open_line_count:0,due_date:'2026-09-01',location_id:1,currency:'UAH'}],
 jobs:[{id:40,code:'MO-DONE',status:'done',due_date:'2026-09-01',location_id:1,currency:'UAH'}],
 transfers:[{id:50,code:'TR-OPEN',status:'in_transit',source_location_id:1,destination_id:2,source_location_name:'Київ склад',destination_name:'Львів сервіс',quantity:'2.000',due_date:'2026-09-20',total_cost:'960.00',currency:'UAH'},{id:51,code:'TR-DONE',status:'received',source_location_id:2,destination_id:1,received_lot_id:10,quantity:'1.000',due_date:'2026-09-01',currency:'UAH'}],
 invoices:[{invoice_id:60,code:'INV-HELD',currency:'UAH',due_date:'2026-09-20',receivable:'20.00',retained:'20.00',collectible:'0.00',location_id:1},{invoice_id:61,code:'INV-PAY',currency:'UAH',due_date:'2026-09-24',receivable:'9007199254740993.01',retained:'0.00',collectible:'9007199254740993.01',location_id:2}],
 retentions:[{id:70,code:'RET-ONE',invoice_id:60,status:'held',amount:'20.00',currency:'UAH',reason:'Договірне утримання'}],
}};
const model=id=>catalogs.ceo.models.find(x=>x.id===id);
const props={catalog:catalogs.ceo,network,table:'lots',view:'control',search:'',branch:'11',point:'1',currency:'UAH',onTable:noop,onView:noop,onSearch:noop,onPoint:noop,onSelect:noop,onAction:noop};
check('actual server descriptors for all three roles are accepted',()=>{for(const catalog of Object.values(catalogs))assert(c.moduleCatalogValid(catalog));assert(!c.moduleCatalogValid({...catalogs.ceo,schema:'other'}));});
check('search works on displayed descriptor fields without copying records',()=>{const result=c.moduleRows(network,model('lots'),'lot-a');assert.equal(result.length,1);assert.strictEqual(result[0],network.rows.lots[0]);assert.equal(c.moduleRows(network,model('lots'),'немає').length,0);});
check('kanban uses real quality/effective states and does not invent an invoice stage',()=>{assert.deepEqual(Array.from(c.moduleLanes(model('lots'),network.rows.lots),x=>x.id),['approved','blocked']);assert.deepEqual(Array.from(c.moduleLanes(model('purchases'),network.rows.purchases),x=>x.id),['closed_cancelled','open']);assert.equal(c.moduleLanes(model('invoices'),network.rows.invoices)[0].id,'__unset');});
check('focus excludes fulfilled orders/jobs/purchases and identifies actual quality and transit',()=>{assert.equal(c.moduleInbox(model('orders'),network.rows.orders,network.as_of).length,0);assert.equal(c.moduleInbox(model('jobs'),network.rows.jobs,network.as_of).length,0);assert.equal(c.moduleInbox(model('purchases'),network.rows.purchases,network.as_of).length,1);assert.equal(c.moduleInbox(model('lots'),network.rows.lots,network.as_of)[0].row.id,11);assert.equal(c.moduleInbox(model('transfers'),network.rows.transfers,network.as_of)[0].row.id,50);});
check('money formatting and focus reasons preserve exact decimal strings beyond binary precision',()=>{assert.equal(c.moduleMoney('9007199254740993.01','UAH'),'9\u00a0007\u00a0199\u00a0254\u00a0740\u00a0993,01\u00a0грн');assert(!c.modulePositive('0.00'));assert(!c.modulePositive('1e3'));const held=c.moduleReasons(model('invoices'),network.rows.invoices[0],network.as_of);assert(held.reasons.some(x=>x.includes('утримано')));assert(!held.reasons.some(x=>x.includes('Доступно до оплати')));});
check('map uses actual relationships and preserves records without invented coordinates',()=>{const mapped=c.moduleMapRows(network,model('lots'),[network.rows.lots[0]]);assert.equal(mapped.points.length,1);assert.strictEqual(mapped.points[0],points[0]);assert.equal(mapped.transfers.length,0);const transfer=c.moduleMapRows(network,model('transfers'),[network.rows.transfers[0]]);assert.equal(transfer.points.length,2);assert.strictEqual(transfer.transfers[0],network.rows.transfers[0]);assert.equal(c.moduleMapRows(network,model('lots'),[{id:99}]).points.length,0);});
check('map destination selection reconciles branch and point while preserving view model and search',()=>{const next=c.modulePointSelection(points,'11','2');assert.equal(next.branch,'12');assert.equal(next.point,'2');assert(points.some(p=>String(p.id)===next.point&&String(p.branch_id)===next.branch));assert.equal(c.modulePointSelection(points,'','2').branch,'');assert.equal(c.modulePointSelection(points,'unassigned','2').branch,'12');const missing=c.modulePointSelection([{id:3,branch_id:null}],'11','3');assert.equal(missing.branch,'unassigned');assert.equal(c.modulePointSelection(points,'11','unknown').point,'');const start=html.indexOf('function chooseWorkspacePoint('),end=html.indexOf('\n',start),handler=html.slice(start,end);assert(handler.includes('setBranch(next.branch)'));assert(handler.includes('setPoint(next.point)'));assert(!/setTable|setModuleView|setModuleSearch/.test(handler));assert(html.includes('onPoint={chooseWorkspacePoint}'));});
check('list opens existing inspector using actual model key',()=>{let selected;const tree=render('CoreModuleSurface',{...props,table:'invoices',onSelect:value=>selected=value});const table=nodes(tree).find(x=>x.type==='ERPTable');table.props.onRow(network.rows.invoices[0]);assert.equal(selected.kind,'invoices');assert.equal(selected.id,60);});
check('list paginates the same immutable rows',()=>{const rows=Array.from({length:25},(_,i)=>({...network.rows.lots[0],id:100+i}));const p={...props,network:{...network,rows:{...network.rows,lots:rows}}};let tree=render('CoreModuleSurface',p);assert.equal(nodes(tree).find(x=>x.type==='ERPTable').props.rows.length,20);nodes(tree).find(x=>x.type==='Button'&&text(x)==='Далі').props.onClick();tree=rerender('CoreModuleSurface',p);assert.equal(nodes(tree).find(x=>x.type==='ERPTable').props.rows.length,5);assert.equal(rows.length,25);});
check('transfer details open inline and Escape closes without mutation',()=>{const p={...props,table:'transfers'};let tree=render('CoreModuleSurface',p);nodes(tree).find(x=>x.type==='ERPTable').props.onRow(network.rows.transfers[0]);tree=rerender('CoreModuleSurface',p);const inline=nodes(tree).find(x=>x.props.className==='module-inline');assert(inline);assert.equal(inline.props.tabIndex,-1);inline.props.onKeyDown({key:'Escape'});tree=rerender('CoreModuleSurface',p);assert(!nodes(tree).some(x=>x.props.className==='module-inline'));assert.equal(network.rows.transfers[0].status,'in_transit');});
check('four view buttons delegate layout only while model search remains shared',()=>{let view,search;const tree=render('CoreModuleSurface',{...props,search:'LOT-A',onView:v=>view=v,onSearch:v=>search=v});for(const name of ['Контроль','Потік','Мережа','Фокус'])assert(nodes(tree).some(x=>x.type==='Button'&&text(x)===name));nodes(tree).find(x=>x.type==='Button'&&text(x)==='Фокус').props.onClick();assert.equal(view,'focus');nodes(tree).find(x=>x.type==='Input').props.onChange({target:{value:'LOT-B'}});assert.equal(search,'LOT-B');});
check('map and kanban render the same searched model rows',()=>{const p={...props,search:'LOT-A'};let tree=render('CoreModuleSurface',{...p,view:'flow'});assert.equal(nodes(tree).filter(x=>x.props.className==='module-record').length,1);tree=render('CoreModuleSurface',{...p,view:'network'});assert.equal(nodes(tree).find(x=>x.type==='NetworkMap').props.points.length,1);assert(text(tree).includes('реальні точки'));});
check('focus has native keyboard details and factual reasons',()=>{const tree=render('CoreModuleSurface',{...props,table:'transfers',view:'focus'});assert.equal(nodes(tree).filter(x=>x.type==='details').length,1);assert(text(tree).includes('очікує фактичного приймання'));assert(!nodes(tree).some(x=>x.props.draggable));});
check('current financial permission removes amounts and focus in stale CEO catalog for manager',()=>{role='manager';let tree=render('CoreModuleSurface',{...props,table:'invoices'});const table=nodes(tree).find(x=>x.type==='ERPTable');assert(table);assert(!table.props.columns.some(x=>['Залишилось сплатити','Утримано','Доступно до оплати'].includes(x[0])));tree=render('CoreModuleSurface',{...props,table:'invoices',view:'focus'});assert.equal(nodes(tree).filter(x=>x.type==='details').length,0);assert(!text(tree).includes('900719925'));tree=render('CoreModuleSurface',{...props,table:'retentions'});assert(!nodes(tree).some(x=>x.type==='ERPTable'));role='ceo';});
check('record actions delegate same original row ID and decimal quantity to existing form',()=>{let action;const tree=render('ModuleRecordActions',{catalog:catalogs.ceo,network,model:model('purchases'),row:network.rows.purchases[0],onAction:(...args)=>action=args});nodes(tree).find(x=>x.type==='Button'&&text(x)==='Прийняти поставку').props.onClick();assert.equal(action[0],'receive');assert.equal(action[1].purchase_id,20);assert.equal(action[1].quantity,'2.000');assert.equal(action[1].location_id,1);assert.equal(network.rows.purchases[0].open_quantity,'2.000');});
check('observer sees no mutations even if descriptor and network are stale CEO copies',()=>{role='observer';assert.equal(render('ModuleRecordActions',{catalog:catalogs.ceo,network,model:model('lots'),row:network.rows.lots[0],onAction:noop}),null);assert.equal(render('ModuleCreateActions',{catalog:catalogs.ceo,network,model:model('purchases'),onAction:noop}),null);role='ceo';});
check('current finance permissions conceal invoice and opening even with stale CEO descriptors',()=>{role='manager';assert.equal(c.bosCanAction('invoice'),true,'Use actual frontend policy, which allows manager invoice');const p={catalog:catalogs.ceo,network,model:model('orders'),row:network.rows.orders[0],onAction:noop};let tree=render('ModuleRecordActions',p);assert(!nodes(tree).some(x=>x.type==='Button'&&text(x)==='Рахунок за відвантаження'));role='ceo';tree=render('ModuleRecordActions',{...p,network:{...network,capabilities:{...network.capabilities,finance:false}}});assert(!nodes(tree).some(x=>x.type==='Button'&&text(x)==='Рахунок за відвантаження'));tree=render('ModuleCreateActions',{catalog:catalogs.ceo,network:{...network,capabilities:{...network.capabilities,finance:false}},model:model('lots'),onAction:noop});assert(!nodes(tree).some(x=>x.type==='Button'&&text(x)==='Початкова партія'));tree=render('ModuleRecordActions',{...p,catalog:{...catalogs.ceo,permissions:{...catalogs.ceo.permissions,finance:false}}});assert(!nodes(tree).some(x=>x.type==='Button'&&text(x)==='Рахунок за відвантаження'));});
check('create action keeps current currency and destination context',()=>{let action;const tree=render('ModuleCreateActions',{catalog:catalogs.ceo,network,model:model('purchases'),branch:'11',point:'1',currency:'UAH',onAction:(...a)=>action=a});nodes(tree).find(x=>x.type==='Button').props.onClick();assert.equal(action[0],'purchase');assert.equal(action[1].currency,'UAH');assert.equal(action[1].destination_id,'1');});
check('CSV preserves branch point currency model and never implies client search filtering',()=>{let tree=render('CoreModuleSurface',props);assert.equal(nodes(tree).find(x=>x.type==='a').props.href,'/api/erp/network/export/?currency=UAH&branch_id=11&location_id=1&table=lots');tree=render('CoreModuleSurface',{...props,search:'LOT-A'});assert(!nodes(tree).some(x=>x.type==='a'));assert(text(tree).includes('Очистіть пошук'));});
check('KPI CSS keeps full amount and currency together with responsive card sizing',()=>{const css=html.slice(html.indexOf('/* CORE_MODULE_VIEWS_STYLE_BEGIN */'),html.indexOf('/* CORE_MODULE_VIEWS_STYLE_END */'));assert(css.includes('white-space:nowrap'));assert(css.includes('overflow-wrap:normal'));assert(css.includes('font-size:clamp(12px,7cqi,29px)'));assert(css.includes('minmax(min(100%,220px),1fr)'));assert(!css.includes('text-overflow:ellipsis'));assert(css.includes('@media(max-width:650px)'));});
check('new layouts preserve existing four usefulness groups and do not introduce a browser ledger',()=>{for(const label of ['Огляд','Операції','Документи й звірки','Контроль строків'])assert(html.includes(label));assert(html.includes('view={moduleView} onView={setModuleView} search={moduleSearch} onSearch={setModuleSearch}'));assert(!fragment.includes('localStorage'));assert(!fragment.includes('BoSNetwork.create'));assert(!fragment.includes('method:'));assert(!fragment.includes('draggable='));});
(async()=>{
 let called;c.fetch=async(url,options)=>{called={url,options};return {ok:true,json:async()=>catalogs.ceo};};
 const catalog=await c.moduleFetchCatalog(new AbortController().signal);check('registry GET fetch uses actual endpoint and accepts server catalog only',()=>{assert.strictEqual(catalog,catalogs.ceo);assert.equal(called.url,'/api/erp/modules/');assert(called.options.signal);});
 c.fetch=async()=>({ok:false,json:async()=>({error:'Denied'})});await assert.rejects(()=>c.moduleFetchCatalog(),/Denied/);checks++;console.log('PASS registry HTTP failure does not construct fallback catalog');
 c.fetch=async()=>({ok:true,json:async()=>({schema:'fake'})});await assert.rejects(()=>c.moduleFetchCatalog(),/невідому/);checks++;console.log('PASS registry schema failure does not construct fallback catalog');
 const errorTree=render('CoreModuleWorkspace',props,[null,'Denied',0]);check('registry failure renders alert and retry without data view',()=>{assert(nodes(errorTree).some(x=>x.props.role==='alert'));assert(!nodes(errorTree).some(x=>x.type===c.CoreModuleSurface));assert(nodes(errorTree).some(x=>x.type==='Button'&&text(x)==='Спробувати ще раз'));});
 console.log(JSON.stringify({result:'PASS',checks,scope:'new bounded module-view component/contract checks; no browser or existing suite rerun'},null,2));
})().catch(error=>{console.error(error);process.exitCode=1;});
