/* Bounded component/contract harness. Not a browser or end-to-end test. */
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'frontend/boss_app_source.html'),'utf8'),babel=require(path.join(root,'assets/babel.js'));
const component=html.slice(html.indexOf('// NETWORK_WORKSPACE_BEGIN'),html.indexOf('// NETWORK_WORKSPACE_END'));
const confirms=html.slice(html.indexOf('// NETWORK_CONFIRM_BEGIN'),html.indexOf('\nfunction purchaseRemaining',html.indexOf('// NETWORK_CONFIRM_BEGIN')));
const actions=html.slice(html.indexOf('const ERP_ACTIONS='),html.indexOf('\nfunction ERPTable'));
let count=0;function check(label,fn){fn();count++;console.log('PASS '+label);}
const elements=[],store=new Map(),events=[];let role='ceo',hook=0,slots=[],pendingEffects=[];
const React={createElement(type,props,...children){return {type,props:props||{},children};}};
const noop=()=>{},button='Button',c={console,React,Number,Intl,URLSearchParams,AbortController,JSON,Math,BigInt,Promise,window:{BOS_RUNTIME:{employee_id:1},Event:class{constructor(type){this.type=type}},dispatchEvent(e){events.push(e.type)}},sessionStorage:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v)},useState(initial){const i=hook++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return [slots[i],value=>slots[i]=typeof value==='function'?value(slots[i]):value];},useRef(initial){const i=hook++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useEffect(fn){pendingEffects.push(fn);},bosRole:()=>role,bosCan:key=>key==='finance'?role==='ceo':key==='write'?role!=='observer':true,bosCanAction:a=>role==='ceo'||role==='manager'&&!['hold_payment','release_payment','location_update','order_network','purchase_network','payment'].includes(a),bosCanView:()=>true,bosStorageKey:x=>'test:'+role+':'+x,Button:button,Input:'Input',Select:'Select',Card:'Card',ERPTable:'ERPTable',ImpactTable:'ImpactTable',ERP_LABELS:{pending:'Очікує перевірки'},OP_STATUS:{approved:'Дозволено'},erpNum:x=>String(x),erpDate:x=>x||'—',b03OpenPurchase:r=>r.open_quantity||'1.000',b03Positive:x=>Number(x)>0};
vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(root,'assets/network-map.js'),'utf8'),c);vm.runInContext(babel.transform(actions+'\n'+confirms+'\n'+component,{presets:['react']}).code,c);
function nodes(tree){if(!tree||typeof tree!=='object')return [];return [tree,...(tree.children||[]).flat(Infinity).flatMap(nodes)];}
function text(tree){return (tree?.children||[]).flat(Infinity).map(x=>typeof x==='object'?text(x):x??'').join('');}
function render(name,props,overrides=[]){slots=overrides;hook=0;pendingEffects=[];return c[name](props);}
function rerender(name,props){hook=0;pendingEffects=[];return c[name](props);}
const rowPoint={id:1,code:'K-WH',name:'Склад Київ',branch_id:1,branch_name:'Київ',map_lat:50.45466,map_lng:30.5238,coordinate_basis:'branch',kind:'warehouse',lot_count:1,inventory_value:'100.00'};
const network={schema:'bos.network.v1',as_of:'2026-09-20',data_mode:'demo',currency:'UAH',branches:[{id:1,name:'Київ'}],locations:[rowPoint],capabilities:{finance:true,write:true,export:true},metrics:{point_count:1,lot_count:1,in_transit_count:0,inventory_value:'100.00',in_transit_value:'0.00',receivable:'200.00',retained:'20.00'},rows:{points:[rowPoint],lots:[{id:1,code:'L1',quality:'approved',quantity:'10',available:'5',value:'100.00'}],purchases:[],orders:[],jobs:[],transfers:[],invoices:[{invoice_id:1,open:'200.00',retained:'20.00',collectible:'180.00'}],retentions:[{id:1,status:'held',code:'H1',amount:'20.00'}]},workflow:{requests:[],metrics:{request_count:0,timed_request_count:0,median_processing_hours:null},comparison:{available:false,reason:'Недостатньо даних'},reconciliations:[]},documents:[]};
const data={branches:network.branches,locations:network.locations,items:[],invoices:network.rows.invoices,partners:[],employees:[],orders:[],lines:[],reservations:[],lots:[],jobs:[],transfers:[],retentions:[],events:[]};
function state(table='points',group='operations'){return ['', '', 'UAH',table,network,'',0,false,false,'EUR','',group];}
check('sourced map has 27 named admin regions',()=>{assert.equal(c.window.BOS_NETWORK_MAP.paths.length,27);assert(c.window.BOS_NETWORK_MAP.paths.every(x=>x.code&&x.name&&x.d));assert(c.window.BOS_NETWORK_MAP.paths.some(x=>x.name.includes('Крим')));});
check('Mercator Kyiv and Crimea map coordinates are inside geographic view',()=>{for(const xy of [c.networkProject(50.45466,30.5238),c.networkProject(44.95,34.1)])assert(xy[0]>0&&xy[0]<960&&xy[1]>0&&xy[1]<570);assert.equal(c.networkProject(null,30),null);assert.equal(c.networkProject(90,30),null);});
check('same location coalesces without invented point offset',()=>{const g=c.networkClusters([rowPoint,{...rowPoint,id:2}]);assert.equal(g.length,1);assert.equal(g[0].points.length,2);});
check('currency/branch/point are encoded into server query',()=>assert.equal(c.networkQuery('unassigned','12','UAH','lots'),'currency=UAH&branch_id=unassigned&location_id=12&table=lots'));
check('reference conversion validates positive manually entered rate',()=>{assert.equal(c.networkEquivalent('400.00','40.000000'),10);for(const rate of ['', '0','-1','NaN','Infinity','1e2','0.0000001','1000000'])assert.equal(c.networkEquivalent('400.00',rate),null);assert.equal(c.networkEquivalent(null,'40'),null);});
check('UAH is new form first currency without EUR relabel',()=>{assert(actions.includes('enum:UAH,EUR,USD'));assert(!actions.includes('enum:EUR,UAH,USD'));assert(html.includes('Валюта наявних записів'));});
check('CEO invoices expose retained and collectible, not invented invoice totals',()=>{const t=render('ERPNetwork',{data,onSelect:noop,onAction:noop},state('invoices'));const table=nodes(t).find(x=>x.type==='ERPTable');assert(table.props.columns.some(x=>x[0]==='Зокрема утримано'));assert.strictEqual(table.props.rows,network.rows.invoices);});
check('manager sees no invoice money and no retention register',()=>{role='manager';const t=render('ERPNetwork',{data,onSelect:noop,onAction:noop},state('invoices'));const table=nodes(t).find(x=>x.type==='ERPTable');assert.equal(table.props.columns.length,3);assert(!nodes(t).some(x=>x.type==='Button'&&text(x).startsWith('Утримання')));role='ceo';});
check('registered transfer action invokes server form with selected lot',()=>{let captured;const t=render('ERPNetwork',{data,onSelect:noop,onAction:(...args)=>captured=args},state('lots'));const table=nodes(t).find(x=>x.type==='ERPTable');const actions=table.props.columns.find(x=>x[0]==='Дії')[1](network.rows.lots[0]);nodes(actions).find(x=>x.type==='Button'&&text(x)==='Відправити').props.onClick();assert.equal(captured[0],'transfer_dispatch');assert.equal(captured[1].lot_id,1);});
check('all four workspace blocks are present',()=>{const t=render('ERPNetwork',{data,onSelect:noop,onAction:noop},state());const labels=nodes(t).filter(x=>x.type==='Button').map(text);for(const label of ['Огляд','Операції','Документи й звірки','Контроль строків'])assert(labels.includes(label));});
check('unknown timing remains missing and not zero acceleration',()=>{const t=render('NetworkWorkflow',{network,onNavigate:noop,onDocument:noop,onSelect:noop});assert(text(t).includes('Недостатньо даних'));assert(!text(t).includes('Спостережуване скорочення'));});
check('fulfilled past-due sales orders are excluded from overdue work',()=>{const scoped={...network,rows:{...network.rows,orders:[{id:81,code:'NET-HIST-1',status:'confirmed',due_date:'2026-09-01',open_line_count:0},{id:82,code:'NET-OPEN-1',status:'confirmed',due_date:'2026-09-01',open_line_count:1}]}};const t=render('NetworkWorkflow',{network:scoped,onNavigate:noop,onDocument:noop,onSelect:noop});const overdue=nodes(t).filter(x=>x.type==='ERPTable').at(-1).props.rows;assert.equal(overdue.length,1);assert.equal(overdue[0].id,82);});
check('document access levels use actual BoS Ukrainian labels with unknown fallback',()=>{const t=render('NetworkDocuments',{network,onNavigate:noop,onDocument:noop});const columns=nodes(t).find(x=>x.type==='ERPTable').props.columns;const access=columns.find(x=>x[0]==='Доступ')[1];for(const [value,label] of [['operational','Операційний'],['management','Управлінський'],['ceo','Лише керівник'],['future_level','future_level']])assert.equal(access({access_level:value}),label);const type=columns.find(x=>x[0]==='Тип')[1];assert.equal(type({document_type:'Пропозиція постачальника'}),'Пропозиція постачальника');});
check('only known terminal statuses allow new review',()=>{assert.equal(c.erpConfirmTerminal(409,{code:'proposal_stale'}),true);assert.equal(c.erpConfirmTerminal(409,{}),false);assert.equal(c.erpConfirmTerminal(500,{}),false);assert.equal(c.erpConfirmTerminal(403,{}),true);});
check('pending IDs omit business payload',()=>{c.erpPendingSave('transfer_dispatch','12345678-1234-1234-1234-123456789012');assert.equal(c.erpPendingRead().length,1);assert.deepEqual(Object.keys(c.erpPendingRead()[0]).sort(),['action','proposal_id']);c.erpPendingRemove('12345678-1234-1234-1234-123456789012');assert.equal(c.erpPendingRead().length,0);});
(async()=>{
 const proposal={id:'12345678-1234-1234-1234-123456789012',payload:{action:'erp_transfer_dispatch',lot_id:1,quantity:'1.000',location_id:2,code:'TR1',reason:'Move'},effect:{},impact:[]};
 let calls=[],done=0,close=0,attempt=0;c.fetch=async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});attempt++;if(attempt===1)throw Error('timeout');return {ok:true,status:200,json:async()=>({erp_event_id:9,impact:[]})};};
 const props={action:'transfer_dispatch',data,onClose:noop,onDone:()=>done++};
 render('ERPActionDialog',props);slots[0]={current:{close(){close++},showModal:noop}};slots[3]=proposal;
 let t=rerender('ERPActionDialog',props);let confirm=nodes(t).find(x=>x.type==='Button'&&text(x)==='Погодити й виконати');await confirm.props.onClick();
 check('ambiguous confirmation preserves proposal ID and hides re-preview',()=>{assert.strictEqual(slots[3],proposal);assert.equal(c.erpPendingRead()[0].proposal_id,proposal.id);t=rerender('ERPActionDialog',props);assert(!nodes(t).some(x=>x.type==='Button'&&text(x)==='Переглянути дані'));});
 await nodes(t).find(x=>x.type==='Button'&&text(x)==='Повторити це погодження').props.onClick();
 check('retry uses exact original ID and consumes one server receipt',()=>{assert.equal(calls.length,2);assert.equal(calls[0].body.proposal_id,calls[1].body.proposal_id);assert.equal(done,1);assert.equal(close,1);assert.equal(c.erpPendingRead().length,0);});
 let metadataPayload;c.erpFetch=async(path,payload)=>{metadataPayload=payload;return {id:'12345678-1234-1234-1234-123456789013',payload,effect:{},impact:[]};};
 const metadataProps={action:'location_update',preset:{location_id:1,branch_id:'',lat:'',lng:'',address:'',reason:'Очистити реквізити'},data,onClose:noop,onDone:noop};
 const metadataTree=render('ERPActionDialog',metadataProps);await nodes(metadataTree).find(x=>x.type==='form').props.onSubmit({preventDefault:noop});
 check('blank metadata address stays string while nullable links/coordinates clear',()=>{assert.equal(metadataPayload.address,'');for(const field of ['branch_id','lat','lng'])assert.strictEqual(metadataPayload[field],null);assert.equal(metadataPayload.location_id,1);});
 check('renderer has no simulation engine, embedded datasets or runtime CDN for map',()=>{assert(!component.includes('BoSNetwork.create'));assert(!component.includes('localStorage'));assert(html.includes('src="/assets/network-map.js"'));});
 console.log(JSON.stringify({result:'PASS',checks:count,scope:'bounded Node/React-element and API-contract harness; no browser or E2E verification'},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
